import { StyleSheet, Platform } from "react-native"
import { theme } from "@/lib/theme"

export const formStyles = StyleSheet.create({
  formScrollContent: {
    padding: 16,
    paddingBottom: 40,
  },
  amountCard: {
    backgroundColor: theme.colors.surfaceElevated,
    borderRadius: theme.radius.xl,
    padding: 16,
    borderWidth: 1,
    borderColor: theme.colors.border,
    marginBottom: 12,
  },
  fieldSectionLabel: {
    fontSize: 11,
    fontWeight: "700",
    color: theme.colors.textMuted,
    letterSpacing: 0.6,
    marginBottom: 6,
  },
  amountInputRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  amountCurrencyPrefix: {
    fontSize: 34,
    fontWeight: "800",
    marginRight: 4,
    fontFamily: Platform.OS === "ios" ? "Menlo" : "monospace",
  },
  amountInput: {
    flex: 1,
    fontSize: 34,
    fontWeight: "800",
    padding: 0,
    fontFamily: Platform.OS === "ios" ? "Menlo" : "monospace",
  },
  currencySelectButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: theme.radius.md,
    backgroundColor: theme.colors.background,
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  currencySelectCode: {
    fontSize: 13,
    fontWeight: "700",
    color: theme.colors.textPrimary,
    letterSpacing: 0.5,
  },
  conversionBox: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
    padding: 12,
    borderRadius: theme.radius.lg,
    backgroundColor: theme.colors.primarySubtle,
    borderWidth: 1,
    borderColor: "rgba(99, 102, 241, 0.2)",
  },
  conversionBoxLabel: {
    fontSize: 10,
    fontWeight: "700",
    color: theme.colors.primary,
    letterSpacing: 0.5,
  },
  conversionBoxAmount: {
    fontSize: 14,
    fontWeight: "800",
    color: theme.colors.textPrimary,
    marginTop: 2,
  },
  conversionBoxRate: {
    fontSize: 11,
    fontFamily: Platform.OS === "ios" ? "Menlo" : "monospace",
    color: theme.colors.textMuted,
    marginTop: 2,
  },
  conversionAlert: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
    padding: 12,
    borderRadius: theme.radius.lg,
    backgroundColor: "rgba(245, 158, 11, 0.1)",
    borderWidth: 1,
    borderColor: "rgba(245, 158, 11, 0.25)",
    marginBottom: 12,
  },
  conversionAlertTitle: {
    fontSize: 11,
    fontWeight: "700",
    color: "#f59e0b",
    textTransform: "uppercase",
    letterSpacing: 0.3,
  },
  conversionAlertText: {
    fontSize: 12,
    color: theme.colors.textMuted,
    marginTop: 2,
    lineHeight: 16,
  },
  specialSelectorCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    padding: 12,
    borderRadius: theme.radius.lg,
    backgroundColor: theme.colors.surfaceElevated,
    borderWidth: 1,
    borderColor: theme.colors.border,
    marginBottom: 12,
  },
  specialSelectorIcon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
  },
  specialSelectorLabel: {
    fontSize: 11,
    fontWeight: "600",
    color: theme.colors.textMuted,
    textTransform: "uppercase",
  },
  specialSelectorValue: {
    fontSize: 14,
    fontWeight: "600",
    color: theme.colors.textPrimary,
    marginTop: 2,
  },
  borrowingActionToggle: {
    flexDirection: "row",
    gap: 8,
  },
  borrowingActionBtn: {
    flex: 1,
    paddingVertical: 9,
    borderRadius: theme.radius.md,
    borderWidth: 1,
    borderColor: theme.colors.border,
    backgroundColor: theme.colors.surfaceElevated,
    alignItems: "center",
    justifyContent: "center",
  },
  borrowingActionActive: {
    borderColor: "#f59e0b",
    backgroundColor: "rgba(245, 158, 11, 0.15)",
  },
  borrowingActionText: {
    fontSize: 12,
    fontWeight: "600",
    color: theme.colors.textMuted,
  },
  borrowingActionTextActive: {
    color: "#f59e0b",
    fontWeight: "700",
  },
  formGroupCard: {
    padding: 0,
    borderRadius: theme.radius.xl,
    overflow: "hidden",
  },
  formRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 14,
    gap: 12,
  },
  formRowLabelGroup: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    flexShrink: 0,
  },
  formRowLabel: {
    fontSize: 14,
    fontWeight: "500",
    color: theme.colors.textMuted,
  },
  formRowInput: {
    flex: 1,
    fontSize: 14,
    fontWeight: "500",
    color: theme.colors.textPrimary,
    textAlign: "right",
    paddingVertical: 0,
    paddingHorizontal: 0,
    marginLeft: 16,
  },
  formRowValueGroup: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 6,
  },
  formRowValueText: {
    fontSize: 14,
    fontWeight: "600",
    color: theme.colors.textPrimary,
    textAlign: "right",
    flexShrink: 1,
  },
  placeholderText: {
    fontSize: 14,
    color: theme.colors.textMuted,
  },
  selectedBudgetChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    borderWidth: 1,
    maxWidth: 200,
  },
  selectedBudgetText: {
    fontSize: 13,
    fontWeight: "600",
    flexShrink: 1,
  },
  selectedBudgetCurrencyBadge: {
    paddingHorizontal: 4,
    paddingVertical: 1,
    borderRadius: 4,
    borderWidth: 1,
  },
  selectedBudgetCurrencyTag: {
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 0.5,
  },
  rowDivider: {
    height: 1,
    backgroundColor: theme.colors.border,
    marginLeft: 42,
  },
  errorBox: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    padding: 10,
    borderRadius: theme.radius.md,
    backgroundColor: theme.colors.destructiveSubtle,
    borderWidth: 1,
    borderColor: "rgba(244, 63, 94, 0.3)",
    marginTop: 12,
  },
  errorText: {
    fontSize: 12,
    color: theme.colors.destructive,
    fontWeight: "500",
    flex: 1,
  },
  bottomDock: {
    paddingHorizontal: 16,
    paddingTop: 10,
    backgroundColor: theme.colors.background,
    borderTopWidth: 1,
    borderTopColor: theme.colors.border,
  },
  submitBtn: {
    width: "100%",
  },
  submitBtnExpense: {
    backgroundColor: theme.colors.destructive,
  },
  submitBtnIncome: {
    backgroundColor: theme.colors.success,
  },
  submitBtnTransfer: {
    backgroundColor: theme.colors.primary,
  },
  submitBtnScheduled: {
    backgroundColor: "#6366f1",
  },
  submitBtnBorrowing: {
    backgroundColor: "#d97706",
  },
})
