version: "2"
run:
  tests: true
linters:
  settings:
    errcheck:
      exclude-functions:
        - (*database/sql.Tx).Rollback
        - (*github.com/masterkeysrd/saturn/internal/platform/db.TxController).Rollback
        - (github.com/masterkeysrd/saturn/internal/platform/db.Transactor).Rollback
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
      - ^tools/
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
      - ^tools/
