// Code generated by protoc-gen-go-scheduler. DO NOT EDIT.
// Source: backup.proto

package backupv1

import (
	"context"
	"encoding/json"
	"time"

	"github.com/masterkeysrd/saturn/internal/platform/scheduler"
)

// RunDatabaseBackupPayloadHandler is the strongly-typed callback signature for the 'backup.RunDatabaseBackup' job.
type RunDatabaseBackupPayloadHandler func(ctx context.Context, payload *RunDatabaseBackupPayload) error

// RegisterRunDatabaseBackupPayload binds the handler callback to the scheduler engine.
func RegisterRunDatabaseBackupPayload(engine *scheduler.Engine, handler RunDatabaseBackupPayloadHandler) {
	engine.Register("backup.RunDatabaseBackup", func(ctx context.Context, payloadBytes []byte) error {
		var payload RunDatabaseBackupPayload
		if err := json.Unmarshal(payloadBytes, &payload); err != nil {
			return err
		}
		return handler(ctx, &payload)
	})
}

// RunDatabaseBackupPayloadJob represents the enqueue request options for 'backup.RunDatabaseBackup'.
type RunDatabaseBackupPayloadJob struct {
	Payload     *RunDatabaseBackupPayload
	RunAt       time.Time
	MaxAttempts int
}

// EnqueueRunDatabaseBackupPayload puts the job on the queue with compile-time type safety.
func EnqueueRunDatabaseBackupPayload(ctx context.Context, sched scheduler.Scheduler, job RunDatabaseBackupPayloadJob) error {
	return sched.Enqueue(ctx, scheduler.Job{
		JobType:     "backup.RunDatabaseBackup",
		RunAt:       job.RunAt,
		Payload:     job.Payload,
		MaxAttempts: job.MaxAttempts,
	})
}
