package codegen

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// File represents a generated Go source file with protogen-style ergonomics.
// It automatically manages deduplicated and sorted imports, and formats
// source code output with go/format.
type File struct {
	filename string
	pkgName  string
	header   string
	imports  map[string]string // importPath -> alias (empty string means default pkg name)
	buf      bytes.Buffer
}

// NewFile creates a new generated file buffer with the given destination path and package name.
func NewFile(filename, pkgName string) *File {
	return &File{
		filename: filename,
		pkgName:  pkgName,
		header:   "// Code generated by saturn codegen. DO NOT EDIT.\n",
		imports:  make(map[string]string),
	}
}

// SetHeader overrides the default header comment.
func (f *File) SetHeader(header string) {
	if header != "" && !strings.HasSuffix(header, "\n") {
		header += "\n"
	}
	f.header = header
}

// P writes arguments to the file buffer followed by a newline.
// Like protoc-gen-go/protogen, arguments are converted to strings and concatenated.
func (f *File) P(args ...any) {
	for _, arg := range args {
		fmt.Fprint(&f.buf, arg)
	}
	f.buf.WriteByte('\n')
}

// Import registers an import path and optional alias.
// Returns the local package identifier to be used in code (alias if provided, otherwise package name derived from path).
func (f *File) Import(importPath string, alias ...string) string {
	importPath = strings.Trim(importPath, `"`)
	var localAlias string
	if len(alias) > 0 && alias[0] != "" {
		localAlias = alias[0]
	}

	parts := strings.Split(importPath, "/")
	defaultPkg := parts[len(parts)-1]

	if localAlias != "" && localAlias != defaultPkg {
		f.imports[importPath] = localAlias
		return localAlias
	}

	if _, exists := f.imports[importPath]; !exists {
		f.imports[importPath] = ""
	}
	return defaultPkg
}

// AddImports registers a map of aliasOrPkgName -> importPath.
func (f *File) AddImports(imports map[string]string) {
	for alias, path := range imports {
		f.Import(path, alias)
	}
}

// QualifiedIdent registers the import path and returns "pkg.ident".
func (f *File) QualifiedIdent(importPath, ident string) string {
	pkg := f.Import(importPath)
	if pkg == "" {
		return ident
	}
	return pkg + "." + ident
}

// Content builds and formats the complete Go source code.
func (f *File) Content() ([]byte, error) {
	var out bytes.Buffer

	// Write header
	if f.header != "" {
		out.WriteString(f.header)
		out.WriteString("\n")
	}

	// Write package declaration
	out.WriteString("package ")
	out.WriteString(f.pkgName)
	out.WriteString("\n\n")

	// Write imports
	if len(f.imports) > 0 {
		var stdImports []string
		var thirdPartyImports []string

		for path := range f.imports {
			firstSegment := strings.Split(path, "/")[0]
			if strings.Contains(firstSegment, ".") {
				thirdPartyImports = append(thirdPartyImports, path)
			} else {
				stdImports = append(stdImports, path)
			}
		}

		sort.Strings(stdImports)
		sort.Strings(thirdPartyImports)

		out.WriteString("import (\n")
		for _, p := range stdImports {
			alias := f.imports[p]
			if alias != "" {
				fmt.Fprintf(&out, "\t%s %q\n", alias, p)
			} else {
				fmt.Fprintf(&out, "\t%q\n", p)
			}
		}

		if len(stdImports) > 0 && len(thirdPartyImports) > 0 {
			out.WriteString("\n")
		}

		for _, p := range thirdPartyImports {
			alias := f.imports[p]
			if alias != "" {
				fmt.Fprintf(&out, "\t%s %q\n", alias, p)
			} else {
				fmt.Fprintf(&out, "\t%q\n", p)
			}
		}
		out.WriteString(")\n\n")
	}

	// Write body
	out.Write(f.buf.Bytes())

	formatted, err := format.Source(out.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format source for %s: %w\nRaw Source:\n%s", f.filename, err, out.String())
	}

	return formatted, nil
}

// Save formats and writes the generated file to its target path.
func (f *File) Save() error {
	data, err := f.Content()
	if err != nil {
		return err
	}

	dir := filepath.Dir(f.filename)
	if dir != "" && dir != "." {
		if err := os.MkdirAll(dir, 0755); err != nil {
			return fmt.Errorf("create directory %s: %w", dir, err)
		}
	}

	if err := os.WriteFile(f.filename, data, 0644); err != nil {
		return fmt.Errorf("write file %s: %w", f.filename, err)
	}

	return nil
}
