package identity

import (
	"context"
	"strings"
)

type Provider interface {
	Name() ProviderType
	Authenticate(ctx context.Context, credentials map[string]string) (*UserProfile, error)
}

// UserProfile represents the profile information of an authenticated user
// obtained from an authentication provider (internal or external).
//
// Password-based authentication returns most of the fields empty, except for
// Provider and ID (that is, the username).
type UserProfile struct {
	// The provider with which the user authenticated (`password`, `facebook`, `twitter`, etc.).
	Provider ProviderType // Provider name

	// A unique identifier for the user, as generated by the service provider.
	ID SubjectID

	// The name of this user, suitable for display.
	DisplayName string

	// Username is the user's unique username, if available.
	Username string

	// Name contains the user's first and last name.
	Name UserProfileName

	// A list of email addresses associated with this user.
	Emails []string

	// Photos contains the URLs of the user's profile pictures.
	Photos []string
}

type ProviderType string

const (
	ProviderTypeVault ProviderType = "vault" // Internal password-based authentication provider.
)

func (pt ProviderType) String() string {
	return string(pt)
}

type UserProfileName struct {
	// The user's first name.
	FirstName string

	// The user's last name.
	LastName string
}

func (n UserProfileName) FullName() string {
	fullName := strings.TrimSpace(n.FirstName + " " + n.LastName)
	return fullName
}
