// Code generated by loggen. DO NOT EDIT.

package iam

import (
	"context"
	"time"

	"github.com/masterkeysrd/saturn/internal/domain/identity"
	"github.com/masterkeysrd/saturn/internal/platform/log"
	"github.com/masterkeysrd/saturn/internal/platform/paging"
)

// LoggingCoordinator wraps a Coordinator and logs operation durations and errors.
type LoggingCoordinator struct {
	next   Coordinator
	logger log.Logger
}

// NewLoggingCoordinator creates a new LoggingCoordinator decorator.
func NewLoggingCoordinator(next Coordinator, logger log.Logger) *LoggingCoordinator {
	return &LoggingCoordinator{
		next:   next,
		logger: logger,
	}
}

// Compile-time interface assertion.
var _ Coordinator = (*LoggingCoordinator)(nil)

// Authenticate executes next.Authenticate and logs execution duration and errors.
func (l *LoggingCoordinator) Authenticate(ctx context.Context, identifier string, password string) (*identity.User, error) {
	start := time.Now()
	res, err := l.next.Authenticate(ctx, identifier, password)
	duration := time.Since(start)

	if err != nil {
		l.logger.Error(ctx, "iam.Authenticate failed",
			log.String("component", "iam"),
			log.String("operation", "Authenticate"),
			log.Duration("duration", duration),
			log.Err(err),
		)
		return nil, err
	}

	l.logger.Info(ctx, "iam.Authenticate completed",
		log.String("component", "iam"),
		log.String("operation", "Authenticate"),
		log.Duration("duration", duration),
	)
	return res, nil
}

// GetAuthVersion executes next.GetAuthVersion and logs execution duration and errors.
func (l *LoggingCoordinator) GetAuthVersion(ctx context.Context, id identity.UserID) (int64, error) {
	start := time.Now()
	res, err := l.next.GetAuthVersion(ctx, id)
	duration := time.Since(start)

	if err != nil {
		l.logger.Error(ctx, "iam.GetAuthVersion failed",
			log.String("component", "iam"),
			log.String("operation", "GetAuthVersion"),
			log.Duration("duration", duration),
			log.Err(err),
		)
		return 0, err
	}

	l.logger.Info(ctx, "iam.GetAuthVersion completed",
		log.String("component", "iam"),
		log.String("operation", "GetAuthVersion"),
		log.Duration("duration", duration),
	)
	return res, nil
}

// GetCurrentUser executes next.GetCurrentUser and logs execution duration and errors.
func (l *LoggingCoordinator) GetCurrentUser(ctx context.Context, userID identity.UserID) (*identity.User, error) {
	start := time.Now()
	res, err := l.next.GetCurrentUser(ctx, userID)
	duration := time.Since(start)

	if err != nil {
		l.logger.Error(ctx, "iam.GetCurrentUser failed",
			log.String("component", "iam"),
			log.String("operation", "GetCurrentUser"),
			log.Duration("duration", duration),
			log.Err(err),
		)
		return nil, err
	}

	l.logger.Info(ctx, "iam.GetCurrentUser completed",
		log.String("component", "iam"),
		log.String("operation", "GetCurrentUser"),
		log.Duration("duration", duration),
	)
	return res, nil
}

// ListSecurityEvents executes next.ListSecurityEvents and logs execution duration and errors.
func (l *LoggingCoordinator) ListSecurityEvents(ctx context.Context, filter identity.SecurityEventFilter) (*paging.Page[*identity.SecurityEvent], error) {
	start := time.Now()
	res, err := l.next.ListSecurityEvents(ctx, filter)
	duration := time.Since(start)

	if err != nil {
		l.logger.Error(ctx, "iam.ListSecurityEvents failed",
			log.String("component", "iam"),
			log.String("operation", "ListSecurityEvents"),
			log.Duration("duration", duration),
			log.Err(err),
		)
		return nil, err
	}

	l.logger.Info(ctx, "iam.ListSecurityEvents completed",
		log.String("component", "iam"),
		log.String("operation", "ListSecurityEvents"),
		log.Duration("duration", duration),
	)
	return res, nil
}

// Login executes next.Login and logs execution duration and errors.
func (l *LoggingCoordinator) Login(ctx context.Context, req *LoginRequest) (*LoginResponse, error) {
	start := time.Now()
	res, err := l.next.Login(ctx, req)
	duration := time.Since(start)

	if err != nil {
		l.logger.Error(ctx, "iam.Login failed",
			log.String("component", "iam"),
			log.String("operation", "Login"),
			log.Duration("duration", duration),
			log.Err(err),
		)
		return nil, err
	}

	l.logger.Info(ctx, "iam.Login completed",
		log.String("component", "iam"),
		log.String("operation", "Login"),
		log.Duration("duration", duration),
	)
	return res, nil
}

// Logout executes next.Logout and logs execution duration and errors.
func (l *LoggingCoordinator) Logout(ctx context.Context, req *LogoutRequest) (*LogoutResponse, error) {
	start := time.Now()
	res, err := l.next.Logout(ctx, req)
	duration := time.Since(start)

	if err != nil {
		l.logger.Error(ctx, "iam.Logout failed",
			log.String("component", "iam"),
			log.String("operation", "Logout"),
			log.Duration("duration", duration),
			log.Err(err),
		)
		return nil, err
	}

	l.logger.Info(ctx, "iam.Logout completed",
		log.String("component", "iam"),
		log.String("operation", "Logout"),
		log.Duration("duration", duration),
	)
	return res, nil
}

// RefreshSession executes next.RefreshSession and logs execution duration and errors.
func (l *LoggingCoordinator) RefreshSession(ctx context.Context, req *RefreshSessionRequest) (*RefreshSessionResponse, error) {
	start := time.Now()
	res, err := l.next.RefreshSession(ctx, req)
	duration := time.Since(start)

	if err != nil {
		l.logger.Error(ctx, "iam.RefreshSession failed",
			log.String("component", "iam"),
			log.String("operation", "RefreshSession"),
			log.Duration("duration", duration),
			log.Err(err),
		)
		return nil, err
	}

	l.logger.Info(ctx, "iam.RefreshSession completed",
		log.String("component", "iam"),
		log.String("operation", "RefreshSession"),
		log.Duration("duration", duration),
	)
	return res, nil
}

// Register executes next.Register and logs execution duration and errors.
func (l *LoggingCoordinator) Register(ctx context.Context, req *RegisterUserRequest) (*RegisterUserResponse, error) {
	start := time.Now()
	res, err := l.next.Register(ctx, req)
	duration := time.Since(start)

	if err != nil {
		l.logger.Error(ctx, "iam.Register failed",
			log.String("component", "iam"),
			log.String("operation", "Register"),
			log.Duration("duration", duration),
			log.Err(err),
		)
		return nil, err
	}

	l.logger.Info(ctx, "iam.Register completed",
		log.String("component", "iam"),
		log.String("operation", "Register"),
		log.Duration("duration", duration),
	)
	return res, nil
}

// AdminCreateUser executes next.AdminCreateUser and logs execution duration and errors.
func (l *LoggingCoordinator) AdminCreateUser(ctx context.Context, req *AdminCreateUserRequest) (*AdminCreateUserResponse, error) {
	start := time.Now()
	res, err := l.next.AdminCreateUser(ctx, req)
	duration := time.Since(start)

	if err != nil {
		l.logger.Error(ctx, "iam.AdminCreateUser failed",
			log.String("component", "iam"),
			log.String("operation", "AdminCreateUser"),
			log.Duration("duration", duration),
			log.Err(err),
		)
		return nil, err
	}

	l.logger.Info(ctx, "iam.AdminCreateUser completed",
		log.String("component", "iam"),
		log.String("operation", "AdminCreateUser"),
		log.Duration("duration", duration),
	)
	return res, nil
}

// ApproveUser executes next.ApproveUser and logs execution duration and errors.
func (l *LoggingCoordinator) ApproveUser(ctx context.Context, req *ApproveUserRequest) (*ApproveUserResponse, error) {
	start := time.Now()
	res, err := l.next.ApproveUser(ctx, req)
	duration := time.Since(start)

	if err != nil {
		l.logger.Error(ctx, "iam.ApproveUser failed",
			log.String("component", "iam"),
			log.String("operation", "ApproveUser"),
			log.Duration("duration", duration),
			log.Err(err),
		)
		return nil, err
	}

	l.logger.Info(ctx, "iam.ApproveUser completed",
		log.String("component", "iam"),
		log.String("operation", "ApproveUser"),
		log.Duration("duration", duration),
	)
	return res, nil
}

// RejectUser executes next.RejectUser and logs execution duration and errors.
func (l *LoggingCoordinator) RejectUser(ctx context.Context, req *RejectUserRequest) (*RejectUserResponse, error) {
	start := time.Now()
	res, err := l.next.RejectUser(ctx, req)
	duration := time.Since(start)

	if err != nil {
		l.logger.Error(ctx, "iam.RejectUser failed",
			log.String("component", "iam"),
			log.String("operation", "RejectUser"),
			log.Duration("duration", duration),
			log.Err(err),
		)
		return nil, err
	}

	l.logger.Info(ctx, "iam.RejectUser completed",
		log.String("component", "iam"),
		log.String("operation", "RejectUser"),
		log.Duration("duration", duration),
	)
	return res, nil
}

// UnlockUser executes next.UnlockUser and logs execution duration and errors.
func (l *LoggingCoordinator) UnlockUser(ctx context.Context, req *UnlockUserRequest) (*UnlockUserResponse, error) {
	start := time.Now()
	res, err := l.next.UnlockUser(ctx, req)
	duration := time.Since(start)

	if err != nil {
		l.logger.Error(ctx, "iam.UnlockUser failed",
			log.String("component", "iam"),
			log.String("operation", "UnlockUser"),
			log.Duration("duration", duration),
			log.Err(err),
		)
		return nil, err
	}

	l.logger.Info(ctx, "iam.UnlockUser completed",
		log.String("component", "iam"),
		log.String("operation", "UnlockUser"),
		log.Duration("duration", duration),
	)
	return res, nil
}

// ListUsers executes next.ListUsers and logs execution duration and errors.
func (l *LoggingCoordinator) ListUsers(ctx context.Context, filter *ListUsersFilter) (*paging.Page[*identity.User], error) {
	start := time.Now()
	res, err := l.next.ListUsers(ctx, filter)
	duration := time.Since(start)

	if err != nil {
		l.logger.Error(ctx, "iam.ListUsers failed",
			log.String("component", "iam"),
			log.String("operation", "ListUsers"),
			log.Duration("duration", duration),
			log.Err(err),
		)
		return nil, err
	}

	l.logger.Info(ctx, "iam.ListUsers completed",
		log.String("component", "iam"),
		log.String("operation", "ListUsers"),
		log.Duration("duration", duration),
	)
	return res, nil
}

// UpdateUserRole executes next.UpdateUserRole and logs execution duration and errors.
func (l *LoggingCoordinator) UpdateUserRole(ctx context.Context, req *UpdateUserRoleRequest) (*UpdateUserRoleResponse, error) {
	start := time.Now()
	res, err := l.next.UpdateUserRole(ctx, req)
	duration := time.Since(start)

	if err != nil {
		l.logger.Error(ctx, "iam.UpdateUserRole failed",
			log.String("component", "iam"),
			log.String("operation", "UpdateUserRole"),
			log.Duration("duration", duration),
			log.Err(err),
		)
		return nil, err
	}

	l.logger.Info(ctx, "iam.UpdateUserRole completed",
		log.String("component", "iam"),
		log.String("operation", "UpdateUserRole"),
		log.Duration("duration", duration),
	)
	return res, nil
}

// ListActiveSessions executes next.ListActiveSessions and logs execution duration and errors.
func (l *LoggingCoordinator) ListActiveSessions(ctx context.Context, req *ListActiveSessionsRequest) (*ListActiveSessionsResponse, error) {
	start := time.Now()
	res, err := l.next.ListActiveSessions(ctx, req)
	duration := time.Since(start)

	if err != nil {
		l.logger.Error(ctx, "iam.ListActiveSessions failed",
			log.String("component", "iam"),
			log.String("operation", "ListActiveSessions"),
			log.Duration("duration", duration),
			log.Err(err),
		)
		return nil, err
	}

	l.logger.Info(ctx, "iam.ListActiveSessions completed",
		log.String("component", "iam"),
		log.String("operation", "ListActiveSessions"),
		log.Duration("duration", duration),
	)
	return res, nil
}

// RevokeSession executes next.RevokeSession and logs execution duration and errors.
func (l *LoggingCoordinator) RevokeSession(ctx context.Context, req *RevokeSessionRequest) (*RevokeSessionResponse, error) {
	start := time.Now()
	res, err := l.next.RevokeSession(ctx, req)
	duration := time.Since(start)

	if err != nil {
		l.logger.Error(ctx, "iam.RevokeSession failed",
			log.String("component", "iam"),
			log.String("operation", "RevokeSession"),
			log.Duration("duration", duration),
			log.Err(err),
		)
		return nil, err
	}

	l.logger.Info(ctx, "iam.RevokeSession completed",
		log.String("component", "iam"),
		log.String("operation", "RevokeSession"),
		log.Duration("duration", duration),
	)
	return res, nil
}

// RevokeAllSessions executes next.RevokeAllSessions and logs execution duration and errors.
func (l *LoggingCoordinator) RevokeAllSessions(ctx context.Context, req *RevokeAllSessionsRequest) (*RevokeAllSessionsResponse, error) {
	start := time.Now()
	res, err := l.next.RevokeAllSessions(ctx, req)
	duration := time.Since(start)

	if err != nil {
		l.logger.Error(ctx, "iam.RevokeAllSessions failed",
			log.String("component", "iam"),
			log.String("operation", "RevokeAllSessions"),
			log.Duration("duration", duration),
			log.Err(err),
		)
		return nil, err
	}

	l.logger.Info(ctx, "iam.RevokeAllSessions completed",
		log.String("component", "iam"),
		log.String("operation", "RevokeAllSessions"),
		log.Duration("duration", duration),
	)
	return res, nil
}

// ListMFAFactors executes next.ListMFAFactors and logs execution duration and errors.
func (l *LoggingCoordinator) ListMFAFactors(ctx context.Context, req *ListMFAFactorsRequest) (*ListMFAFactorsResponse, error) {
	start := time.Now()
	res, err := l.next.ListMFAFactors(ctx, req)
	duration := time.Since(start)

	if err != nil {
		l.logger.Error(ctx, "iam.ListMFAFactors failed",
			log.String("component", "iam"),
			log.String("operation", "ListMFAFactors"),
			log.Duration("duration", duration),
			log.Err(err),
		)
		return nil, err
	}

	l.logger.Info(ctx, "iam.ListMFAFactors completed",
		log.String("component", "iam"),
		log.String("operation", "ListMFAFactors"),
		log.Duration("duration", duration),
	)
	return res, nil
}

// DeleteMFAFactor executes next.DeleteMFAFactor and logs execution duration and errors.
func (l *LoggingCoordinator) DeleteMFAFactor(ctx context.Context, req *DeleteMFAFactorRequest) error {
	start := time.Now()
	err := l.next.DeleteMFAFactor(ctx, req)
	duration := time.Since(start)

	if err != nil {
		l.logger.Error(ctx, "iam.DeleteMFAFactor failed",
			log.String("component", "iam"),
			log.String("operation", "DeleteMFAFactor"),
			log.Duration("duration", duration),
			log.Err(err),
		)
		return err
	}

	l.logger.Info(ctx, "iam.DeleteMFAFactor completed",
		log.String("component", "iam"),
		log.String("operation", "DeleteMFAFactor"),
		log.Duration("duration", duration),
	)
	return nil
}

// SetPrimaryMFAFactor executes next.SetPrimaryMFAFactor and logs execution duration and errors.
func (l *LoggingCoordinator) SetPrimaryMFAFactor(ctx context.Context, req *SetPrimaryMFAFactorRequest) error {
	start := time.Now()
	err := l.next.SetPrimaryMFAFactor(ctx, req)
	duration := time.Since(start)

	if err != nil {
		l.logger.Error(ctx, "iam.SetPrimaryMFAFactor failed",
			log.String("component", "iam"),
			log.String("operation", "SetPrimaryMFAFactor"),
			log.Duration("duration", duration),
			log.Err(err),
		)
		return err
	}

	l.logger.Info(ctx, "iam.SetPrimaryMFAFactor completed",
		log.String("component", "iam"),
		log.String("operation", "SetPrimaryMFAFactor"),
		log.Duration("duration", duration),
	)
	return nil
}

// SetupTOTP executes next.SetupTOTP and logs execution duration and errors.
func (l *LoggingCoordinator) SetupTOTP(ctx context.Context, req *SetupTOTPRequest) (*SetupTOTPResponse, error) {
	start := time.Now()
	res, err := l.next.SetupTOTP(ctx, req)
	duration := time.Since(start)

	if err != nil {
		l.logger.Error(ctx, "iam.SetupTOTP failed",
			log.String("component", "iam"),
			log.String("operation", "SetupTOTP"),
			log.Duration("duration", duration),
			log.Err(err),
		)
		return nil, err
	}

	l.logger.Info(ctx, "iam.SetupTOTP completed",
		log.String("component", "iam"),
		log.String("operation", "SetupTOTP"),
		log.Duration("duration", duration),
	)
	return res, nil
}

// ConfirmTOTP executes next.ConfirmTOTP and logs execution duration and errors.
func (l *LoggingCoordinator) ConfirmTOTP(ctx context.Context, req *ConfirmTOTPRequest) (*ConfirmTOTPResponse, error) {
	start := time.Now()
	res, err := l.next.ConfirmTOTP(ctx, req)
	duration := time.Since(start)

	if err != nil {
		l.logger.Error(ctx, "iam.ConfirmTOTP failed",
			log.String("component", "iam"),
			log.String("operation", "ConfirmTOTP"),
			log.Duration("duration", duration),
			log.Err(err),
		)
		return nil, err
	}

	l.logger.Info(ctx, "iam.ConfirmTOTP completed",
		log.String("component", "iam"),
		log.String("operation", "ConfirmTOTP"),
		log.Duration("duration", duration),
	)
	return res, nil
}

// RegenerateBackupCodes executes next.RegenerateBackupCodes and logs execution duration and errors.
func (l *LoggingCoordinator) RegenerateBackupCodes(ctx context.Context, req *RegenerateBackupCodesRequest) (*RegenerateBackupCodesResponse, error) {
	start := time.Now()
	res, err := l.next.RegenerateBackupCodes(ctx, req)
	duration := time.Since(start)

	if err != nil {
		l.logger.Error(ctx, "iam.RegenerateBackupCodes failed",
			log.String("component", "iam"),
			log.String("operation", "RegenerateBackupCodes"),
			log.Duration("duration", duration),
			log.Err(err),
		)
		return nil, err
	}

	l.logger.Info(ctx, "iam.RegenerateBackupCodes completed",
		log.String("component", "iam"),
		log.String("operation", "RegenerateBackupCodes"),
		log.Duration("duration", duration),
	)
	return res, nil
}

// CreateAuthChallenge executes next.CreateAuthChallenge and logs execution duration and errors.
func (l *LoggingCoordinator) CreateAuthChallenge(ctx context.Context) (*CreateAuthChallengeResponse, error) {
	start := time.Now()
	res, err := l.next.CreateAuthChallenge(ctx)
	duration := time.Since(start)

	if err != nil {
		l.logger.Error(ctx, "iam.CreateAuthChallenge failed",
			log.String("component", "iam"),
			log.String("operation", "CreateAuthChallenge"),
			log.Duration("duration", duration),
			log.Err(err),
		)
		return nil, err
	}

	l.logger.Info(ctx, "iam.CreateAuthChallenge completed",
		log.String("component", "iam"),
		log.String("operation", "CreateAuthChallenge"),
		log.Duration("duration", duration),
	)
	return res, nil
}

// CreateDevice executes next.CreateDevice and logs execution duration and errors.
func (l *LoggingCoordinator) CreateDevice(ctx context.Context, req *CreateDeviceRequest) (*identity.Device, error) {
	start := time.Now()
	res, err := l.next.CreateDevice(ctx, req)
	duration := time.Since(start)

	if err != nil {
		l.logger.Error(ctx, "iam.CreateDevice failed",
			log.String("component", "iam"),
			log.String("operation", "CreateDevice"),
			log.Duration("duration", duration),
			log.Err(err),
		)
		return nil, err
	}

	l.logger.Info(ctx, "iam.CreateDevice completed",
		log.String("component", "iam"),
		log.String("operation", "CreateDevice"),
		log.Duration("duration", duration),
	)
	return res, nil
}

// ListDevices executes next.ListDevices and logs execution duration and errors.
func (l *LoggingCoordinator) ListDevices(ctx context.Context, req *ListDevicesRequest) (*ListDevicesResponse, error) {
	start := time.Now()
	res, err := l.next.ListDevices(ctx, req)
	duration := time.Since(start)

	if err != nil {
		l.logger.Error(ctx, "iam.ListDevices failed",
			log.String("component", "iam"),
			log.String("operation", "ListDevices"),
			log.Duration("duration", duration),
			log.Err(err),
		)
		return nil, err
	}

	l.logger.Info(ctx, "iam.ListDevices completed",
		log.String("component", "iam"),
		log.String("operation", "ListDevices"),
		log.Duration("duration", duration),
	)
	return res, nil
}

// RevokeDevice executes next.RevokeDevice and logs execution duration and errors.
func (l *LoggingCoordinator) RevokeDevice(ctx context.Context, req *RevokeDeviceRequest) error {
	start := time.Now()
	err := l.next.RevokeDevice(ctx, req)
	duration := time.Since(start)

	if err != nil {
		l.logger.Error(ctx, "iam.RevokeDevice failed",
			log.String("component", "iam"),
			log.String("operation", "RevokeDevice"),
			log.Duration("duration", duration),
			log.Err(err),
		)
		return err
	}

	l.logger.Info(ctx, "iam.RevokeDevice completed",
		log.String("component", "iam"),
		log.String("operation", "RevokeDevice"),
		log.Duration("duration", duration),
	)
	return nil
}

// ResetPassword executes next.ResetPassword and logs execution duration and errors.
func (l *LoggingCoordinator) ResetPassword(ctx context.Context, req *ResetPasswordRequest) (*ResetPasswordResponse, error) {
	start := time.Now()
	res, err := l.next.ResetPassword(ctx, req)
	duration := time.Since(start)

	if err != nil {
		l.logger.Error(ctx, "iam.ResetPassword failed",
			log.String("component", "iam"),
			log.String("operation", "ResetPassword"),
			log.Duration("duration", duration),
			log.Err(err),
		)
		return nil, err
	}

	l.logger.Info(ctx, "iam.ResetPassword completed",
		log.String("component", "iam"),
		log.String("operation", "ResetPassword"),
		log.Duration("duration", duration),
	)
	return res, nil
}

// ValidateResetToken executes next.ValidateResetToken and logs execution duration and errors.
func (l *LoggingCoordinator) ValidateResetToken(ctx context.Context, req *ValidateResetTokenRequest) (*ValidateResetTokenResponse, error) {
	start := time.Now()
	res, err := l.next.ValidateResetToken(ctx, req)
	duration := time.Since(start)

	if err != nil {
		l.logger.Error(ctx, "iam.ValidateResetToken failed",
			log.String("component", "iam"),
			log.String("operation", "ValidateResetToken"),
			log.Duration("duration", duration),
			log.Err(err),
		)
		return nil, err
	}

	l.logger.Info(ctx, "iam.ValidateResetToken completed",
		log.String("component", "iam"),
		log.String("operation", "ValidateResetToken"),
		log.Duration("duration", duration),
	)
	return res, nil
}

// CompleteResetPassword executes next.CompleteResetPassword and logs execution duration and errors.
func (l *LoggingCoordinator) CompleteResetPassword(ctx context.Context, req *CompleteResetPasswordRequest) error {
	start := time.Now()
	err := l.next.CompleteResetPassword(ctx, req)
	duration := time.Since(start)

	if err != nil {
		l.logger.Error(ctx, "iam.CompleteResetPassword failed",
			log.String("component", "iam"),
			log.String("operation", "CompleteResetPassword"),
			log.Duration("duration", duration),
			log.Err(err),
		)
		return err
	}

	l.logger.Info(ctx, "iam.CompleteResetPassword completed",
		log.String("component", "iam"),
		log.String("operation", "CompleteResetPassword"),
		log.Duration("duration", duration),
	)
	return nil
}

// ChangePassword executes next.ChangePassword and logs execution duration and errors.
func (l *LoggingCoordinator) ChangePassword(ctx context.Context, req *ChangePasswordRequest) (*ChangePasswordResponse, error) {
	start := time.Now()
	res, err := l.next.ChangePassword(ctx, req)
	duration := time.Since(start)

	if err != nil {
		l.logger.Error(ctx, "iam.ChangePassword failed",
			log.String("component", "iam"),
			log.String("operation", "ChangePassword"),
			log.Duration("duration", duration),
			log.Err(err),
		)
		return nil, err
	}

	l.logger.Info(ctx, "iam.ChangePassword completed",
		log.String("component", "iam"),
		log.String("operation", "ChangePassword"),
		log.Duration("duration", duration),
	)
	return res, nil
}

// UpdateProfile executes next.UpdateProfile and logs execution duration and errors.
func (l *LoggingCoordinator) UpdateProfile(ctx context.Context, req *UpdateProfileRequest) (*identity.User, error) {
	start := time.Now()
	res, err := l.next.UpdateProfile(ctx, req)
	duration := time.Since(start)

	if err != nil {
		l.logger.Error(ctx, "iam.UpdateProfile failed",
			log.String("component", "iam"),
			log.String("operation", "UpdateProfile"),
			log.Duration("duration", duration),
			log.Err(err),
		)
		return nil, err
	}

	l.logger.Info(ctx, "iam.UpdateProfile completed",
		log.String("component", "iam"),
		log.String("operation", "UpdateProfile"),
		log.Duration("duration", duration),
	)
	return res, nil
}

// ChangeEmail executes next.ChangeEmail and logs execution duration and errors.
func (l *LoggingCoordinator) ChangeEmail(ctx context.Context, req *ChangeEmailRequest) (*identity.User, error) {
	start := time.Now()
	res, err := l.next.ChangeEmail(ctx, req)
	duration := time.Since(start)

	if err != nil {
		l.logger.Error(ctx, "iam.ChangeEmail failed",
			log.String("component", "iam"),
			log.String("operation", "ChangeEmail"),
			log.Duration("duration", duration),
			log.Err(err),
		)
		return nil, err
	}

	l.logger.Info(ctx, "iam.ChangeEmail completed",
		log.String("component", "iam"),
		log.String("operation", "ChangeEmail"),
		log.Duration("duration", duration),
	)
	return res, nil
}

// DeleteAccount executes next.DeleteAccount and logs execution duration and errors.
func (l *LoggingCoordinator) DeleteAccount(ctx context.Context, req *DeleteAccountRequest) error {
	start := time.Now()
	err := l.next.DeleteAccount(ctx, req)
	duration := time.Since(start)

	if err != nil {
		l.logger.Error(ctx, "iam.DeleteAccount failed",
			log.String("component", "iam"),
			log.String("operation", "DeleteAccount"),
			log.Duration("duration", duration),
			log.Err(err),
		)
		return err
	}

	l.logger.Info(ctx, "iam.DeleteAccount completed",
		log.String("component", "iam"),
		log.String("operation", "DeleteAccount"),
		log.Duration("duration", duration),
	)
	return nil
}
