// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: saturn/space/v1/space.proto

package spacev1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Space represents a workspace.
type Space struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The workspace's unique identifier.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The workspace's name.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// The workspace's description.
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// The owner's user ID.
	OwnerId string `protobuf:"bytes,4,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	// The optimistic locking version.
	Version int64 `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"`
	// The creation timestamp.
	CreateTime *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	// The last update timestamp.
	UpdateTime    *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Space) Reset() {
	*x = Space{}
	mi := &file_saturn_space_v1_space_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Space) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Space) ProtoMessage() {}

func (x *Space) ProtoReflect() protoreflect.Message {
	mi := &file_saturn_space_v1_space_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Space.ProtoReflect.Descriptor instead.
func (*Space) Descriptor() ([]byte, []int) {
	return file_saturn_space_v1_space_proto_rawDescGZIP(), []int{0}
}

func (x *Space) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Space) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Space) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Space) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *Space) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Space) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *Space) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

// SpaceMember represents a member of a workspace.
type SpaceMember struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The workspace ID.
	SpaceId string `protobuf:"bytes,1,opt,name=space_id,json=spaceId,proto3" json:"space_id,omitempty"`
	// The member's user ID.
	UserId string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// The member's role within the workspace.
	Role string `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	// The creation timestamp.
	CreateTime *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	// The last update timestamp.
	UpdateTime    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	Profile       *SpaceMember_Profile   `protobuf:"bytes,6,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpaceMember) Reset() {
	*x = SpaceMember{}
	mi := &file_saturn_space_v1_space_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpaceMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpaceMember) ProtoMessage() {}

func (x *SpaceMember) ProtoReflect() protoreflect.Message {
	mi := &file_saturn_space_v1_space_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpaceMember.ProtoReflect.Descriptor instead.
func (*SpaceMember) Descriptor() ([]byte, []int) {
	return file_saturn_space_v1_space_proto_rawDescGZIP(), []int{1}
}

func (x *SpaceMember) GetSpaceId() string {
	if x != nil {
		return x.SpaceId
	}
	return ""
}

func (x *SpaceMember) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SpaceMember) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *SpaceMember) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *SpaceMember) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

func (x *SpaceMember) GetProfile() *SpaceMember_Profile {
	if x != nil {
		return x.Profile
	}
	return nil
}

// CreateSpaceRequest contains the fields for creating a new workspace.
type CreateSpaceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The workspace's name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The workspace's description.
	Description   string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSpaceRequest) Reset() {
	*x = CreateSpaceRequest{}
	mi := &file_saturn_space_v1_space_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSpaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSpaceRequest) ProtoMessage() {}

func (x *CreateSpaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_saturn_space_v1_space_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSpaceRequest.ProtoReflect.Descriptor instead.
func (*CreateSpaceRequest) Descriptor() ([]byte, []int) {
	return file_saturn_space_v1_space_proto_rawDescGZIP(), []int{2}
}

func (x *CreateSpaceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateSpaceRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// GetSpaceRequest contains the fields for retrieving a workspace.
type GetSpaceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The workspace ID.
	SpaceId       string `protobuf:"bytes,1,opt,name=space_id,json=spaceId,proto3" json:"space_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSpaceRequest) Reset() {
	*x = GetSpaceRequest{}
	mi := &file_saturn_space_v1_space_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSpaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSpaceRequest) ProtoMessage() {}

func (x *GetSpaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_saturn_space_v1_space_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSpaceRequest.ProtoReflect.Descriptor instead.
func (*GetSpaceRequest) Descriptor() ([]byte, []int) {
	return file_saturn_space_v1_space_proto_rawDescGZIP(), []int{3}
}

func (x *GetSpaceRequest) GetSpaceId() string {
	if x != nil {
		return x.SpaceId
	}
	return ""
}

// UpdateSpaceRequest contains the fields for updating a workspace.
type UpdateSpaceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The workspace ID.
	SpaceId string `protobuf:"bytes,1,opt,name=space_id,json=spaceId,proto3" json:"space_id,omitempty"`
	// The workspace's name.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// The workspace's description.
	Description   string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSpaceRequest) Reset() {
	*x = UpdateSpaceRequest{}
	mi := &file_saturn_space_v1_space_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSpaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSpaceRequest) ProtoMessage() {}

func (x *UpdateSpaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_saturn_space_v1_space_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSpaceRequest.ProtoReflect.Descriptor instead.
func (*UpdateSpaceRequest) Descriptor() ([]byte, []int) {
	return file_saturn_space_v1_space_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateSpaceRequest) GetSpaceId() string {
	if x != nil {
		return x.SpaceId
	}
	return ""
}

func (x *UpdateSpaceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateSpaceRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// DeleteSpaceRequest contains the fields for deleting a workspace.
type DeleteSpaceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The workspace ID.
	SpaceId       string `protobuf:"bytes,1,opt,name=space_id,json=spaceId,proto3" json:"space_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSpaceRequest) Reset() {
	*x = DeleteSpaceRequest{}
	mi := &file_saturn_space_v1_space_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSpaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSpaceRequest) ProtoMessage() {}

func (x *DeleteSpaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_saturn_space_v1_space_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSpaceRequest.ProtoReflect.Descriptor instead.
func (*DeleteSpaceRequest) Descriptor() ([]byte, []int) {
	return file_saturn_space_v1_space_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteSpaceRequest) GetSpaceId() string {
	if x != nil {
		return x.SpaceId
	}
	return ""
}

// DeleteSpaceResponse is empty on success.
type DeleteSpaceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSpaceResponse) Reset() {
	*x = DeleteSpaceResponse{}
	mi := &file_saturn_space_v1_space_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSpaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSpaceResponse) ProtoMessage() {}

func (x *DeleteSpaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_saturn_space_v1_space_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSpaceResponse.ProtoReflect.Descriptor instead.
func (*DeleteSpaceResponse) Descriptor() ([]byte, []int) {
	return file_saturn_space_v1_space_proto_rawDescGZIP(), []int{6}
}

// ListSpacesRequest contains the fields for listing user workspaces.
type ListSpacesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`                 // default 20, max 100
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"` // cursor-based pagination token
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSpacesRequest) Reset() {
	*x = ListSpacesRequest{}
	mi := &file_saturn_space_v1_space_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSpacesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSpacesRequest) ProtoMessage() {}

func (x *ListSpacesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_saturn_space_v1_space_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSpacesRequest.ProtoReflect.Descriptor instead.
func (*ListSpacesRequest) Descriptor() ([]byte, []int) {
	return file_saturn_space_v1_space_proto_rawDescGZIP(), []int{7}
}

func (x *ListSpacesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListSpacesRequest) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

// ListSpacesResponse contains the list of spaces and pagination token.
type ListSpacesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Spaces        []*Space               `protobuf:"bytes,1,rep,name=spaces,proto3" json:"spaces,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSpacesResponse) Reset() {
	*x = ListSpacesResponse{}
	mi := &file_saturn_space_v1_space_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSpacesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSpacesResponse) ProtoMessage() {}

func (x *ListSpacesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_saturn_space_v1_space_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSpacesResponse.ProtoReflect.Descriptor instead.
func (*ListSpacesResponse) Descriptor() ([]byte, []int) {
	return file_saturn_space_v1_space_proto_rawDescGZIP(), []int{8}
}

func (x *ListSpacesResponse) GetSpaces() []*Space {
	if x != nil {
		return x.Spaces
	}
	return nil
}

func (x *ListSpacesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

// AddSpaceMemberRequest contains the fields for adding a member.
type AddSpaceMemberRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The workspace ID.
	SpaceId string `protobuf:"bytes,1,opt,name=space_id,json=spaceId,proto3" json:"space_id,omitempty"`
	// The user ID to add as a member.
	UserId string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// The role to assign.
	Role          string `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddSpaceMemberRequest) Reset() {
	*x = AddSpaceMemberRequest{}
	mi := &file_saturn_space_v1_space_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddSpaceMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddSpaceMemberRequest) ProtoMessage() {}

func (x *AddSpaceMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_saturn_space_v1_space_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddSpaceMemberRequest.ProtoReflect.Descriptor instead.
func (*AddSpaceMemberRequest) Descriptor() ([]byte, []int) {
	return file_saturn_space_v1_space_proto_rawDescGZIP(), []int{9}
}

func (x *AddSpaceMemberRequest) GetSpaceId() string {
	if x != nil {
		return x.SpaceId
	}
	return ""
}

func (x *AddSpaceMemberRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AddSpaceMemberRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

// RemoveSpaceMemberRequest contains the fields for removing a member.
type RemoveSpaceMemberRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The workspace ID.
	SpaceId string `protobuf:"bytes,1,opt,name=space_id,json=spaceId,proto3" json:"space_id,omitempty"`
	// The user ID to remove.
	UserId        string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveSpaceMemberRequest) Reset() {
	*x = RemoveSpaceMemberRequest{}
	mi := &file_saturn_space_v1_space_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveSpaceMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveSpaceMemberRequest) ProtoMessage() {}

func (x *RemoveSpaceMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_saturn_space_v1_space_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveSpaceMemberRequest.ProtoReflect.Descriptor instead.
func (*RemoveSpaceMemberRequest) Descriptor() ([]byte, []int) {
	return file_saturn_space_v1_space_proto_rawDescGZIP(), []int{10}
}

func (x *RemoveSpaceMemberRequest) GetSpaceId() string {
	if x != nil {
		return x.SpaceId
	}
	return ""
}

func (x *RemoveSpaceMemberRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// RemoveSpaceMemberResponse is empty on success.
type RemoveSpaceMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveSpaceMemberResponse) Reset() {
	*x = RemoveSpaceMemberResponse{}
	mi := &file_saturn_space_v1_space_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveSpaceMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveSpaceMemberResponse) ProtoMessage() {}

func (x *RemoveSpaceMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_saturn_space_v1_space_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveSpaceMemberResponse.ProtoReflect.Descriptor instead.
func (*RemoveSpaceMemberResponse) Descriptor() ([]byte, []int) {
	return file_saturn_space_v1_space_proto_rawDescGZIP(), []int{11}
}

// UpdateSpaceMemberRoleRequest contains the fields for updating a member's role.
type UpdateSpaceMemberRoleRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The workspace ID.
	SpaceId string `protobuf:"bytes,1,opt,name=space_id,json=spaceId,proto3" json:"space_id,omitempty"`
	// The user ID.
	UserId string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// The new role.
	Role          string `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSpaceMemberRoleRequest) Reset() {
	*x = UpdateSpaceMemberRoleRequest{}
	mi := &file_saturn_space_v1_space_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSpaceMemberRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSpaceMemberRoleRequest) ProtoMessage() {}

func (x *UpdateSpaceMemberRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_saturn_space_v1_space_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSpaceMemberRoleRequest.ProtoReflect.Descriptor instead.
func (*UpdateSpaceMemberRoleRequest) Descriptor() ([]byte, []int) {
	return file_saturn_space_v1_space_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateSpaceMemberRoleRequest) GetSpaceId() string {
	if x != nil {
		return x.SpaceId
	}
	return ""
}

func (x *UpdateSpaceMemberRoleRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateSpaceMemberRoleRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

// ListSpaceMembersRequest contains the fields for listing workspace members.
type ListSpaceMembersRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The workspace ID.
	SpaceId       string `protobuf:"bytes,1,opt,name=space_id,json=spaceId,proto3" json:"space_id,omitempty"`
	PageSize      int32  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`                 // default 20, max 100
	NextPageToken string `protobuf:"bytes,3,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"` // cursor-based pagination token
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSpaceMembersRequest) Reset() {
	*x = ListSpaceMembersRequest{}
	mi := &file_saturn_space_v1_space_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSpaceMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSpaceMembersRequest) ProtoMessage() {}

func (x *ListSpaceMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_saturn_space_v1_space_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSpaceMembersRequest.ProtoReflect.Descriptor instead.
func (*ListSpaceMembersRequest) Descriptor() ([]byte, []int) {
	return file_saturn_space_v1_space_proto_rawDescGZIP(), []int{13}
}

func (x *ListSpaceMembersRequest) GetSpaceId() string {
	if x != nil {
		return x.SpaceId
	}
	return ""
}

func (x *ListSpaceMembersRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListSpaceMembersRequest) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

// ListSpaceMembersResponse contains the list of members and pagination token.
type ListSpaceMembersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Members       []*SpaceMember         `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSpaceMembersResponse) Reset() {
	*x = ListSpaceMembersResponse{}
	mi := &file_saturn_space_v1_space_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSpaceMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSpaceMembersResponse) ProtoMessage() {}

func (x *ListSpaceMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_saturn_space_v1_space_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSpaceMembersResponse.ProtoReflect.Descriptor instead.
func (*ListSpaceMembersResponse) Descriptor() ([]byte, []int) {
	return file_saturn_space_v1_space_proto_rawDescGZIP(), []int{14}
}

func (x *ListSpaceMembersResponse) GetMembers() []*SpaceMember {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *ListSpaceMembersResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

// The nested user profile details.
type SpaceMember_Profile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,3,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpaceMember_Profile) Reset() {
	*x = SpaceMember_Profile{}
	mi := &file_saturn_space_v1_space_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpaceMember_Profile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpaceMember_Profile) ProtoMessage() {}

func (x *SpaceMember_Profile) ProtoReflect() protoreflect.Message {
	mi := &file_saturn_space_v1_space_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpaceMember_Profile.ProtoReflect.Descriptor instead.
func (*SpaceMember_Profile) Descriptor() ([]byte, []int) {
	return file_saturn_space_v1_space_proto_rawDescGZIP(), []int{1, 0}
}

func (x *SpaceMember_Profile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SpaceMember_Profile) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *SpaceMember_Profile) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

var File_saturn_space_v1_space_proto protoreflect.FileDescriptor

const file_saturn_space_v1_space_proto_rawDesc = "" +
	"\n" +
	"\x1bsaturn/space/v1/space.proto\x12\x0fsaturn.space.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x90\x02\n" +
	"\x05Space\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tB\x03\xe0A\x03R\x02id\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tB\x03\xe0A\x02R\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1e\n" +
	"\bowner_id\x18\x04 \x01(\tB\x03\xe0A\x03R\aownerId\x12\x1d\n" +
	"\aversion\x18\x05 \x01(\x03B\x03\xe0A\x03R\aversion\x12;\n" +
	"\vcreate_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12;\n" +
	"\vupdate_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updateTime\"\xe9\x02\n" +
	"\vSpaceMember\x12\x19\n" +
	"\bspace_id\x18\x01 \x01(\tR\aspaceId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x12;\n" +
	"\vcreate_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12;\n" +
	"\vupdate_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updateTime\x12>\n" +
	"\aprofile\x18\x06 \x01(\v2$.saturn.space.v1.SpaceMember.ProfileR\aprofile\x1aX\n" +
	"\aProfile\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x03 \x01(\tR\tavatarUrl\"O\n" +
	"\x12CreateSpaceRequest\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\xe0A\x02R\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"1\n" +
	"\x0fGetSpaceRequest\x12\x1e\n" +
	"\bspace_id\x18\x01 \x01(\tB\x03\xe0A\x02R\aspaceId\"o\n" +
	"\x12UpdateSpaceRequest\x12\x1e\n" +
	"\bspace_id\x18\x01 \x01(\tB\x03\xe0A\x02R\aspaceId\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tB\x03\xe0A\x02R\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"4\n" +
	"\x12DeleteSpaceRequest\x12\x1e\n" +
	"\bspace_id\x18\x01 \x01(\tB\x03\xe0A\x02R\aspaceId\"\x15\n" +
	"\x13DeleteSpaceResponse\"X\n" +
	"\x11ListSpacesRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"l\n" +
	"\x12ListSpacesResponse\x12.\n" +
	"\x06spaces\x18\x01 \x03(\v2\x16.saturn.space.v1.SpaceR\x06spaces\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"n\n" +
	"\x15AddSpaceMemberRequest\x12\x1e\n" +
	"\bspace_id\x18\x01 \x01(\tB\x03\xe0A\x02R\aspaceId\x12\x1c\n" +
	"\auser_id\x18\x02 \x01(\tB\x03\xe0A\x02R\x06userId\x12\x17\n" +
	"\x04role\x18\x03 \x01(\tB\x03\xe0A\x02R\x04role\"X\n" +
	"\x18RemoveSpaceMemberRequest\x12\x1e\n" +
	"\bspace_id\x18\x01 \x01(\tB\x03\xe0A\x02R\aspaceId\x12\x1c\n" +
	"\auser_id\x18\x02 \x01(\tB\x03\xe0A\x02R\x06userId\"\x1b\n" +
	"\x19RemoveSpaceMemberResponse\"u\n" +
	"\x1cUpdateSpaceMemberRoleRequest\x12\x1e\n" +
	"\bspace_id\x18\x01 \x01(\tB\x03\xe0A\x02R\aspaceId\x12\x1c\n" +
	"\auser_id\x18\x02 \x01(\tB\x03\xe0A\x02R\x06userId\x12\x17\n" +
	"\x04role\x18\x03 \x01(\tB\x03\xe0A\x02R\x04role\"~\n" +
	"\x17ListSpaceMembersRequest\x12\x1e\n" +
	"\bspace_id\x18\x01 \x01(\tB\x03\xe0A\x02R\aspaceId\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12&\n" +
	"\x0fnext_page_token\x18\x03 \x01(\tR\rnextPageToken\"z\n" +
	"\x18ListSpaceMembersResponse\x126\n" +
	"\amembers\x18\x01 \x03(\v2\x1c.saturn.space.v1.SpaceMemberR\amembers\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken2\xef\b\n" +
	"\x06Spaces\x12a\n" +
	"\vCreateSpace\x12#.saturn.space.v1.CreateSpaceRequest\x1a\x16.saturn.space.v1.Space\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/v1/spaces\x12c\n" +
	"\bGetSpace\x12 .saturn.space.v1.GetSpaceRequest\x1a\x16.saturn.space.v1.Space\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/v1/spaces/{space_id}\x12l\n" +
	"\vUpdateSpace\x12#.saturn.space.v1.UpdateSpaceRequest\x1a\x16.saturn.space.v1.Space\" \x82\xd3\xe4\x93\x02\x1a:\x01*2\x15/v1/spaces/{space_id}\x12w\n" +
	"\vDeleteSpace\x12#.saturn.space.v1.DeleteSpaceRequest\x1a$.saturn.space.v1.DeleteSpaceResponse\"\x1d\x82\xd3\xe4\x93\x02\x17*\x15/v1/spaces/{space_id}\x12i\n" +
	"\n" +
	"ListSpaces\x12\".saturn.space.v1.ListSpacesRequest\x1a#.saturn.space.v1.ListSpacesResponse\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/v1/spaces\x12\x80\x01\n" +
	"\x0eAddSpaceMember\x12&.saturn.space.v1.AddSpaceMemberRequest\x1a\x1c.saturn.space.v1.SpaceMember\"(\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/v1/spaces/{space_id}/members\x12\x9b\x01\n" +
	"\x11RemoveSpaceMember\x12).saturn.space.v1.RemoveSpaceMemberRequest\x1a*.saturn.space.v1.RemoveSpaceMemberResponse\"/\x82\xd3\xe4\x93\x02)*'/v1/spaces/{space_id}/members/{user_id}\x12\x98\x01\n" +
	"\x15UpdateSpaceMemberRole\x12-.saturn.space.v1.UpdateSpaceMemberRoleRequest\x1a\x1c.saturn.space.v1.SpaceMember\"2\x82\xd3\xe4\x93\x02,:\x01*2'/v1/spaces/{space_id}/members/{user_id}\x12\x8e\x01\n" +
	"\x10ListSpaceMembers\x12(.saturn.space.v1.ListSpaceMembersRequest\x1a).saturn.space.v1.ListSpaceMembersResponse\"%\x82\xd3\xe4\x93\x02\x1f\x12\x1d/v1/spaces/{space_id}/membersB=Z;github.com/masterkeysrd/saturn/apis/saturn/space/v1;spacev1b\x06proto3"

var (
	file_saturn_space_v1_space_proto_rawDescOnce sync.Once
	file_saturn_space_v1_space_proto_rawDescData []byte
)

func file_saturn_space_v1_space_proto_rawDescGZIP() []byte {
	file_saturn_space_v1_space_proto_rawDescOnce.Do(func() {
		file_saturn_space_v1_space_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_saturn_space_v1_space_proto_rawDesc), len(file_saturn_space_v1_space_proto_rawDesc)))
	})
	return file_saturn_space_v1_space_proto_rawDescData
}

var file_saturn_space_v1_space_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_saturn_space_v1_space_proto_goTypes = []any{
	(*Space)(nil),                        // 0: saturn.space.v1.Space
	(*SpaceMember)(nil),                  // 1: saturn.space.v1.SpaceMember
	(*CreateSpaceRequest)(nil),           // 2: saturn.space.v1.CreateSpaceRequest
	(*GetSpaceRequest)(nil),              // 3: saturn.space.v1.GetSpaceRequest
	(*UpdateSpaceRequest)(nil),           // 4: saturn.space.v1.UpdateSpaceRequest
	(*DeleteSpaceRequest)(nil),           // 5: saturn.space.v1.DeleteSpaceRequest
	(*DeleteSpaceResponse)(nil),          // 6: saturn.space.v1.DeleteSpaceResponse
	(*ListSpacesRequest)(nil),            // 7: saturn.space.v1.ListSpacesRequest
	(*ListSpacesResponse)(nil),           // 8: saturn.space.v1.ListSpacesResponse
	(*AddSpaceMemberRequest)(nil),        // 9: saturn.space.v1.AddSpaceMemberRequest
	(*RemoveSpaceMemberRequest)(nil),     // 10: saturn.space.v1.RemoveSpaceMemberRequest
	(*RemoveSpaceMemberResponse)(nil),    // 11: saturn.space.v1.RemoveSpaceMemberResponse
	(*UpdateSpaceMemberRoleRequest)(nil), // 12: saturn.space.v1.UpdateSpaceMemberRoleRequest
	(*ListSpaceMembersRequest)(nil),      // 13: saturn.space.v1.ListSpaceMembersRequest
	(*ListSpaceMembersResponse)(nil),     // 14: saturn.space.v1.ListSpaceMembersResponse
	(*SpaceMember_Profile)(nil),          // 15: saturn.space.v1.SpaceMember.Profile
	(*timestamppb.Timestamp)(nil),        // 16: google.protobuf.Timestamp
}
var file_saturn_space_v1_space_proto_depIdxs = []int32{
	16, // 0: saturn.space.v1.Space.create_time:type_name -> google.protobuf.Timestamp
	16, // 1: saturn.space.v1.Space.update_time:type_name -> google.protobuf.Timestamp
	16, // 2: saturn.space.v1.SpaceMember.create_time:type_name -> google.protobuf.Timestamp
	16, // 3: saturn.space.v1.SpaceMember.update_time:type_name -> google.protobuf.Timestamp
	15, // 4: saturn.space.v1.SpaceMember.profile:type_name -> saturn.space.v1.SpaceMember.Profile
	0,  // 5: saturn.space.v1.ListSpacesResponse.spaces:type_name -> saturn.space.v1.Space
	1,  // 6: saturn.space.v1.ListSpaceMembersResponse.members:type_name -> saturn.space.v1.SpaceMember
	2,  // 7: saturn.space.v1.Spaces.CreateSpace:input_type -> saturn.space.v1.CreateSpaceRequest
	3,  // 8: saturn.space.v1.Spaces.GetSpace:input_type -> saturn.space.v1.GetSpaceRequest
	4,  // 9: saturn.space.v1.Spaces.UpdateSpace:input_type -> saturn.space.v1.UpdateSpaceRequest
	5,  // 10: saturn.space.v1.Spaces.DeleteSpace:input_type -> saturn.space.v1.DeleteSpaceRequest
	7,  // 11: saturn.space.v1.Spaces.ListSpaces:input_type -> saturn.space.v1.ListSpacesRequest
	9,  // 12: saturn.space.v1.Spaces.AddSpaceMember:input_type -> saturn.space.v1.AddSpaceMemberRequest
	10, // 13: saturn.space.v1.Spaces.RemoveSpaceMember:input_type -> saturn.space.v1.RemoveSpaceMemberRequest
	12, // 14: saturn.space.v1.Spaces.UpdateSpaceMemberRole:input_type -> saturn.space.v1.UpdateSpaceMemberRoleRequest
	13, // 15: saturn.space.v1.Spaces.ListSpaceMembers:input_type -> saturn.space.v1.ListSpaceMembersRequest
	0,  // 16: saturn.space.v1.Spaces.CreateSpace:output_type -> saturn.space.v1.Space
	0,  // 17: saturn.space.v1.Spaces.GetSpace:output_type -> saturn.space.v1.Space
	0,  // 18: saturn.space.v1.Spaces.UpdateSpace:output_type -> saturn.space.v1.Space
	6,  // 19: saturn.space.v1.Spaces.DeleteSpace:output_type -> saturn.space.v1.DeleteSpaceResponse
	8,  // 20: saturn.space.v1.Spaces.ListSpaces:output_type -> saturn.space.v1.ListSpacesResponse
	1,  // 21: saturn.space.v1.Spaces.AddSpaceMember:output_type -> saturn.space.v1.SpaceMember
	11, // 22: saturn.space.v1.Spaces.RemoveSpaceMember:output_type -> saturn.space.v1.RemoveSpaceMemberResponse
	1,  // 23: saturn.space.v1.Spaces.UpdateSpaceMemberRole:output_type -> saturn.space.v1.SpaceMember
	14, // 24: saturn.space.v1.Spaces.ListSpaceMembers:output_type -> saturn.space.v1.ListSpaceMembersResponse
	16, // [16:25] is the sub-list for method output_type
	7,  // [7:16] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_saturn_space_v1_space_proto_init() }
func file_saturn_space_v1_space_proto_init() {
	if File_saturn_space_v1_space_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_saturn_space_v1_space_proto_rawDesc), len(file_saturn_space_v1_space_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_saturn_space_v1_space_proto_goTypes,
		DependencyIndexes: file_saturn_space_v1_space_proto_depIdxs,
		MessageInfos:      file_saturn_space_v1_space_proto_msgTypes,
	}.Build()
	File_saturn_space_v1_space_proto = out.File
	file_saturn_space_v1_space_proto_goTypes = nil
	file_saturn_space_v1_space_proto_depIdxs = nil
}
