// Code generated by protoc-gen-go-sdk. DO NOT EDIT.
package adminidentityv1

import (
	"context"
	"fmt"
	"strings"

	"github.com/masterkeysrd/saturn/apis/saturn"
)

var (
	_ = fmt.Sprintf
	_ = strings.TrimSpace
)

// Client provides typed HTTP SDK operations for the AdminIdentity service.
type Client struct {
	base *saturn.Client
}

// NewClient creates a new AdminIdentity HTTP SDK client.
func NewClient(cfg saturn.Config) *Client {
	return &Client{base: saturn.NewClient(cfg)}
}

// ListUsers executes GET /api/v1/admin/identity/users.
func (c *Client) ListUsers(ctx context.Context, req *ListUsersRequest) (*ListUsersResponse, error) {
	var resp ListUsersResponse
	path := "/api/v1/admin/identity/users"
	var query []string
	if req.GetPageSize() != 0 {
		query = append(query, fmt.Sprintf("page_size=%d", req.GetPageSize()))
	}
	if req.GetNextPageToken() != "" {
		query = append(query, fmt.Sprintf("next_page_token=%s", req.GetNextPageToken()))
	}
	if req.GetStatusFilter() != 0 {
		query = append(query, fmt.Sprintf("status_filter=%s", req.GetStatusFilter().String()))
	}
	if req.GetSearchQuery() != "" {
		query = append(query, fmt.Sprintf("search_query=%s", req.GetSearchQuery()))
	}
	if len(query) > 0 {
		path += "?" + strings.Join(query, "&")
	}
	if err := c.base.Do(ctx, "GET", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// ApproveUser executes POST /api/v1/admin/identity/users/{user_id}:approve.
func (c *Client) ApproveUser(ctx context.Context, req *ApproveUserRequest) (*ApproveUserResponse, error) {
	var resp ApproveUserResponse
	path := fmt.Sprintf("/api/v1/admin/identity/users/%s:approve", req.GetUserId())
	var query []string
	if len(query) > 0 {
		path += "?" + strings.Join(query, "&")
	}
	if err := c.base.Do(ctx, "POST", path, req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// RejectUser executes POST /api/v1/admin/identity/users/{user_id}:reject.
func (c *Client) RejectUser(ctx context.Context, req *RejectUserRequest) (*ApproveUserResponse, error) {
	var resp ApproveUserResponse
	path := fmt.Sprintf("/api/v1/admin/identity/users/%s:reject", req.GetUserId())
	var query []string
	if len(query) > 0 {
		path += "?" + strings.Join(query, "&")
	}
	if err := c.base.Do(ctx, "POST", path, req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// UpdateUserRole executes PATCH /api/v1/admin/identity/users/{user_id}.
func (c *Client) UpdateUserRole(ctx context.Context, req *UpdateUserRoleRequest) (*UpdateUserRoleResponse, error) {
	var resp UpdateUserRoleResponse
	path := fmt.Sprintf("/api/v1/admin/identity/users/%s", req.GetUserId())
	var query []string
	if len(query) > 0 {
		path += "?" + strings.Join(query, "&")
	}
	if err := c.base.Do(ctx, "PATCH", path, req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// RevokeAllSessions executes POST /api/v1/admin/identity/users/{user_id}:revoke-sessions.
func (c *Client) RevokeAllSessions(ctx context.Context, req *RevokeAllSessionsRequest) (*RevokeAllSessionsResponse, error) {
	var resp RevokeAllSessionsResponse
	path := fmt.Sprintf("/api/v1/admin/identity/users/%s:revoke-sessions", req.GetUserId())
	var query []string
	if len(query) > 0 {
		path += "?" + strings.Join(query, "&")
	}
	if err := c.base.Do(ctx, "POST", path, req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// ListSecurityEvents executes GET /api/v1/admin/identity/security-events.
func (c *Client) ListSecurityEvents(ctx context.Context, req *ListSecurityEventsRequest) (*ListSecurityEventsResponse, error) {
	var resp ListSecurityEventsResponse
	path := "/api/v1/admin/identity/security-events"
	var query []string
	if req.GetEmail() != "" {
		query = append(query, fmt.Sprintf("email=%s", req.GetEmail()))
	}
	if req.GetEventType() != "" {
		query = append(query, fmt.Sprintf("event_type=%s", req.GetEventType()))
	}
	if req.GetLimit() != 0 {
		query = append(query, fmt.Sprintf("limit=%d", req.GetLimit()))
	}
	if req.GetNextPageToken() != "" {
		query = append(query, fmt.Sprintf("next_page_token=%s", req.GetNextPageToken()))
	}
	if len(query) > 0 {
		path += "?" + strings.Join(query, "&")
	}
	if err := c.base.Do(ctx, "GET", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}
