// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: saturn/finance/v1/finance.proto

package financev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Finance_ConfigureFinance_FullMethodName   = "/saturn.finance.v1.Finance/ConfigureFinance"
	Finance_GetFinanceSettings_FullMethodName = "/saturn.finance.v1.Finance/GetFinanceSettings"
	Finance_CreateBudget_FullMethodName       = "/saturn.finance.v1.Finance/CreateBudget"
	Finance_UpdateBudget_FullMethodName       = "/saturn.finance.v1.Finance/UpdateBudget"
	Finance_DeleteBudget_FullMethodName       = "/saturn.finance.v1.Finance/DeleteBudget"
	Finance_ListBudgets_FullMethodName        = "/saturn.finance.v1.Finance/ListBudgets"
	Finance_GetBudgetPeriod_FullMethodName    = "/saturn.finance.v1.Finance/GetBudgetPeriod"
	Finance_CreateExchangeRate_FullMethodName = "/saturn.finance.v1.Finance/CreateExchangeRate"
	Finance_ListExchangeRates_FullMethodName  = "/saturn.finance.v1.Finance/ListExchangeRates"
	Finance_DeleteExchangeRate_FullMethodName = "/saturn.finance.v1.Finance/DeleteExchangeRate"
	Finance_CreateExpense_FullMethodName      = "/saturn.finance.v1.Finance/CreateExpense"
	Finance_UpdateExpense_FullMethodName      = "/saturn.finance.v1.Finance/UpdateExpense"
	Finance_DeleteTransaction_FullMethodName  = "/saturn.finance.v1.Finance/DeleteTransaction"
	Finance_ListTransactions_FullMethodName   = "/saturn.finance.v1.Finance/ListTransactions"
	Finance_GetInsights_FullMethodName        = "/saturn.finance.v1.Finance/GetInsights"
)

// FinanceClient is the client API for Finance service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Finance provides budgeting and currency management operations for a workspace.
type FinanceClient interface {
	// ConfigureFinance sets up the default base currency for a workspace.
	ConfigureFinance(ctx context.Context, in *ConfigureFinanceRequest, opts ...grpc.CallOption) (*FinanceSettings, error)
	// GetFinanceSettings retrieves the finance settings for a workspace.
	GetFinanceSettings(ctx context.Context, in *GetFinanceSettingsRequest, opts ...grpc.CallOption) (*FinanceSettings, error)
	// CreateBudget creates a new budget template in a workspace.
	CreateBudget(ctx context.Context, in *CreateBudgetRequest, opts ...grpc.CallOption) (*Budget, error)
	// UpdateBudget updates a budget template.
	UpdateBudget(ctx context.Context, in *UpdateBudgetRequest, opts ...grpc.CallOption) (*Budget, error)
	// DeleteBudget deletes a budget template.
	DeleteBudget(ctx context.Context, in *DeleteBudgetRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// ListBudgets lists all budget templates in a workspace.
	ListBudgets(ctx context.Context, in *ListBudgetsRequest, opts ...grpc.CallOption) (*ListBudgetsResponse, error)
	// GetBudgetPeriod retrieves or generates the budget period for a specific date.
	GetBudgetPeriod(ctx context.Context, in *GetBudgetPeriodRequest, opts ...grpc.CallOption) (*BudgetPeriod, error)
	// CreateExchangeRate registers a new daily rate conversion rule.
	CreateExchangeRate(ctx context.Context, in *CreateExchangeRateRequest, opts ...grpc.CallOption) (*ExchangeRate, error)
	// ListExchangeRates lists all exchange rate rules in a workspace.
	ListExchangeRates(ctx context.Context, in *ListExchangeRatesRequest, opts ...grpc.CallOption) (*ListExchangeRatesResponse, error)
	// DeleteExchangeRate deletes a specific daily rate conversion rule.
	DeleteExchangeRate(ctx context.Context, in *DeleteExchangeRateRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// CreateExpense logs a new expense transaction.
	CreateExpense(ctx context.Context, in *CreateExpenseRequest, opts ...grpc.CallOption) (*Transaction, error)
	// UpdateExpense modifies an existing expense.
	UpdateExpense(ctx context.Context, in *UpdateExpenseRequest, opts ...grpc.CallOption) (*Transaction, error)
	// DeleteTransaction deletes any type of transaction.
	DeleteTransaction(ctx context.Context, in *DeleteTransactionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// ListTransactions lists paginated transactions for a workspace.
	ListTransactions(ctx context.Context, in *ListTransactionsRequest, opts ...grpc.CallOption) (*ListTransactionsResponse, error)
	// GetInsights aggregates workspace spent insights and statistics.
	GetInsights(ctx context.Context, in *GetInsightsRequest, opts ...grpc.CallOption) (*GetInsightsResponse, error)
}

type financeClient struct {
	cc grpc.ClientConnInterface
}

func NewFinanceClient(cc grpc.ClientConnInterface) FinanceClient {
	return &financeClient{cc}
}

func (c *financeClient) ConfigureFinance(ctx context.Context, in *ConfigureFinanceRequest, opts ...grpc.CallOption) (*FinanceSettings, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FinanceSettings)
	err := c.cc.Invoke(ctx, Finance_ConfigureFinance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financeClient) GetFinanceSettings(ctx context.Context, in *GetFinanceSettingsRequest, opts ...grpc.CallOption) (*FinanceSettings, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FinanceSettings)
	err := c.cc.Invoke(ctx, Finance_GetFinanceSettings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financeClient) CreateBudget(ctx context.Context, in *CreateBudgetRequest, opts ...grpc.CallOption) (*Budget, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Budget)
	err := c.cc.Invoke(ctx, Finance_CreateBudget_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financeClient) UpdateBudget(ctx context.Context, in *UpdateBudgetRequest, opts ...grpc.CallOption) (*Budget, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Budget)
	err := c.cc.Invoke(ctx, Finance_UpdateBudget_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financeClient) DeleteBudget(ctx context.Context, in *DeleteBudgetRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Finance_DeleteBudget_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financeClient) ListBudgets(ctx context.Context, in *ListBudgetsRequest, opts ...grpc.CallOption) (*ListBudgetsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBudgetsResponse)
	err := c.cc.Invoke(ctx, Finance_ListBudgets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financeClient) GetBudgetPeriod(ctx context.Context, in *GetBudgetPeriodRequest, opts ...grpc.CallOption) (*BudgetPeriod, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BudgetPeriod)
	err := c.cc.Invoke(ctx, Finance_GetBudgetPeriod_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financeClient) CreateExchangeRate(ctx context.Context, in *CreateExchangeRateRequest, opts ...grpc.CallOption) (*ExchangeRate, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExchangeRate)
	err := c.cc.Invoke(ctx, Finance_CreateExchangeRate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financeClient) ListExchangeRates(ctx context.Context, in *ListExchangeRatesRequest, opts ...grpc.CallOption) (*ListExchangeRatesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListExchangeRatesResponse)
	err := c.cc.Invoke(ctx, Finance_ListExchangeRates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financeClient) DeleteExchangeRate(ctx context.Context, in *DeleteExchangeRateRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Finance_DeleteExchangeRate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financeClient) CreateExpense(ctx context.Context, in *CreateExpenseRequest, opts ...grpc.CallOption) (*Transaction, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Transaction)
	err := c.cc.Invoke(ctx, Finance_CreateExpense_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financeClient) UpdateExpense(ctx context.Context, in *UpdateExpenseRequest, opts ...grpc.CallOption) (*Transaction, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Transaction)
	err := c.cc.Invoke(ctx, Finance_UpdateExpense_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financeClient) DeleteTransaction(ctx context.Context, in *DeleteTransactionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Finance_DeleteTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financeClient) ListTransactions(ctx context.Context, in *ListTransactionsRequest, opts ...grpc.CallOption) (*ListTransactionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTransactionsResponse)
	err := c.cc.Invoke(ctx, Finance_ListTransactions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financeClient) GetInsights(ctx context.Context, in *GetInsightsRequest, opts ...grpc.CallOption) (*GetInsightsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetInsightsResponse)
	err := c.cc.Invoke(ctx, Finance_GetInsights_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FinanceServer is the server API for Finance service.
// All implementations should embed UnimplementedFinanceServer
// for forward compatibility.
//
// Finance provides budgeting and currency management operations for a workspace.
type FinanceServer interface {
	// ConfigureFinance sets up the default base currency for a workspace.
	ConfigureFinance(context.Context, *ConfigureFinanceRequest) (*FinanceSettings, error)
	// GetFinanceSettings retrieves the finance settings for a workspace.
	GetFinanceSettings(context.Context, *GetFinanceSettingsRequest) (*FinanceSettings, error)
	// CreateBudget creates a new budget template in a workspace.
	CreateBudget(context.Context, *CreateBudgetRequest) (*Budget, error)
	// UpdateBudget updates a budget template.
	UpdateBudget(context.Context, *UpdateBudgetRequest) (*Budget, error)
	// DeleteBudget deletes a budget template.
	DeleteBudget(context.Context, *DeleteBudgetRequest) (*emptypb.Empty, error)
	// ListBudgets lists all budget templates in a workspace.
	ListBudgets(context.Context, *ListBudgetsRequest) (*ListBudgetsResponse, error)
	// GetBudgetPeriod retrieves or generates the budget period for a specific date.
	GetBudgetPeriod(context.Context, *GetBudgetPeriodRequest) (*BudgetPeriod, error)
	// CreateExchangeRate registers a new daily rate conversion rule.
	CreateExchangeRate(context.Context, *CreateExchangeRateRequest) (*ExchangeRate, error)
	// ListExchangeRates lists all exchange rate rules in a workspace.
	ListExchangeRates(context.Context, *ListExchangeRatesRequest) (*ListExchangeRatesResponse, error)
	// DeleteExchangeRate deletes a specific daily rate conversion rule.
	DeleteExchangeRate(context.Context, *DeleteExchangeRateRequest) (*emptypb.Empty, error)
	// CreateExpense logs a new expense transaction.
	CreateExpense(context.Context, *CreateExpenseRequest) (*Transaction, error)
	// UpdateExpense modifies an existing expense.
	UpdateExpense(context.Context, *UpdateExpenseRequest) (*Transaction, error)
	// DeleteTransaction deletes any type of transaction.
	DeleteTransaction(context.Context, *DeleteTransactionRequest) (*emptypb.Empty, error)
	// ListTransactions lists paginated transactions for a workspace.
	ListTransactions(context.Context, *ListTransactionsRequest) (*ListTransactionsResponse, error)
	// GetInsights aggregates workspace spent insights and statistics.
	GetInsights(context.Context, *GetInsightsRequest) (*GetInsightsResponse, error)
}

// UnimplementedFinanceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFinanceServer struct{}

func (UnimplementedFinanceServer) ConfigureFinance(context.Context, *ConfigureFinanceRequest) (*FinanceSettings, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfigureFinance not implemented")
}
func (UnimplementedFinanceServer) GetFinanceSettings(context.Context, *GetFinanceSettingsRequest) (*FinanceSettings, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFinanceSettings not implemented")
}
func (UnimplementedFinanceServer) CreateBudget(context.Context, *CreateBudgetRequest) (*Budget, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateBudget not implemented")
}
func (UnimplementedFinanceServer) UpdateBudget(context.Context, *UpdateBudgetRequest) (*Budget, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateBudget not implemented")
}
func (UnimplementedFinanceServer) DeleteBudget(context.Context, *DeleteBudgetRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteBudget not implemented")
}
func (UnimplementedFinanceServer) ListBudgets(context.Context, *ListBudgetsRequest) (*ListBudgetsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBudgets not implemented")
}
func (UnimplementedFinanceServer) GetBudgetPeriod(context.Context, *GetBudgetPeriodRequest) (*BudgetPeriod, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBudgetPeriod not implemented")
}
func (UnimplementedFinanceServer) CreateExchangeRate(context.Context, *CreateExchangeRateRequest) (*ExchangeRate, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateExchangeRate not implemented")
}
func (UnimplementedFinanceServer) ListExchangeRates(context.Context, *ListExchangeRatesRequest) (*ListExchangeRatesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListExchangeRates not implemented")
}
func (UnimplementedFinanceServer) DeleteExchangeRate(context.Context, *DeleteExchangeRateRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteExchangeRate not implemented")
}
func (UnimplementedFinanceServer) CreateExpense(context.Context, *CreateExpenseRequest) (*Transaction, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateExpense not implemented")
}
func (UnimplementedFinanceServer) UpdateExpense(context.Context, *UpdateExpenseRequest) (*Transaction, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateExpense not implemented")
}
func (UnimplementedFinanceServer) DeleteTransaction(context.Context, *DeleteTransactionRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteTransaction not implemented")
}
func (UnimplementedFinanceServer) ListTransactions(context.Context, *ListTransactionsRequest) (*ListTransactionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTransactions not implemented")
}
func (UnimplementedFinanceServer) GetInsights(context.Context, *GetInsightsRequest) (*GetInsightsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInsights not implemented")
}
func (UnimplementedFinanceServer) testEmbeddedByValue() {}

// UnsafeFinanceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FinanceServer will
// result in compilation errors.
type UnsafeFinanceServer interface {
	mustEmbedUnimplementedFinanceServer()
}

func RegisterFinanceServer(s grpc.ServiceRegistrar, srv FinanceServer) {
	// If the following call panics, it indicates UnimplementedFinanceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Finance_ServiceDesc, srv)
}

func _Finance_ConfigureFinance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigureFinanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinanceServer).ConfigureFinance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Finance_ConfigureFinance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinanceServer).ConfigureFinance(ctx, req.(*ConfigureFinanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Finance_GetFinanceSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFinanceSettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinanceServer).GetFinanceSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Finance_GetFinanceSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinanceServer).GetFinanceSettings(ctx, req.(*GetFinanceSettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Finance_CreateBudget_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBudgetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinanceServer).CreateBudget(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Finance_CreateBudget_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinanceServer).CreateBudget(ctx, req.(*CreateBudgetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Finance_UpdateBudget_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBudgetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinanceServer).UpdateBudget(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Finance_UpdateBudget_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinanceServer).UpdateBudget(ctx, req.(*UpdateBudgetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Finance_DeleteBudget_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBudgetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinanceServer).DeleteBudget(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Finance_DeleteBudget_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinanceServer).DeleteBudget(ctx, req.(*DeleteBudgetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Finance_ListBudgets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBudgetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinanceServer).ListBudgets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Finance_ListBudgets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinanceServer).ListBudgets(ctx, req.(*ListBudgetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Finance_GetBudgetPeriod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBudgetPeriodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinanceServer).GetBudgetPeriod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Finance_GetBudgetPeriod_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinanceServer).GetBudgetPeriod(ctx, req.(*GetBudgetPeriodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Finance_CreateExchangeRate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateExchangeRateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinanceServer).CreateExchangeRate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Finance_CreateExchangeRate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinanceServer).CreateExchangeRate(ctx, req.(*CreateExchangeRateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Finance_ListExchangeRates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListExchangeRatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinanceServer).ListExchangeRates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Finance_ListExchangeRates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinanceServer).ListExchangeRates(ctx, req.(*ListExchangeRatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Finance_DeleteExchangeRate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteExchangeRateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinanceServer).DeleteExchangeRate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Finance_DeleteExchangeRate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinanceServer).DeleteExchangeRate(ctx, req.(*DeleteExchangeRateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Finance_CreateExpense_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateExpenseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinanceServer).CreateExpense(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Finance_CreateExpense_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinanceServer).CreateExpense(ctx, req.(*CreateExpenseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Finance_UpdateExpense_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateExpenseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinanceServer).UpdateExpense(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Finance_UpdateExpense_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinanceServer).UpdateExpense(ctx, req.(*UpdateExpenseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Finance_DeleteTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinanceServer).DeleteTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Finance_DeleteTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinanceServer).DeleteTransaction(ctx, req.(*DeleteTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Finance_ListTransactions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTransactionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinanceServer).ListTransactions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Finance_ListTransactions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinanceServer).ListTransactions(ctx, req.(*ListTransactionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Finance_GetInsights_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInsightsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinanceServer).GetInsights(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Finance_GetInsights_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinanceServer).GetInsights(ctx, req.(*GetInsightsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Finance_ServiceDesc is the grpc.ServiceDesc for Finance service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Finance_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "saturn.finance.v1.Finance",
	HandlerType: (*FinanceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ConfigureFinance",
			Handler:    _Finance_ConfigureFinance_Handler,
		},
		{
			MethodName: "GetFinanceSettings",
			Handler:    _Finance_GetFinanceSettings_Handler,
		},
		{
			MethodName: "CreateBudget",
			Handler:    _Finance_CreateBudget_Handler,
		},
		{
			MethodName: "UpdateBudget",
			Handler:    _Finance_UpdateBudget_Handler,
		},
		{
			MethodName: "DeleteBudget",
			Handler:    _Finance_DeleteBudget_Handler,
		},
		{
			MethodName: "ListBudgets",
			Handler:    _Finance_ListBudgets_Handler,
		},
		{
			MethodName: "GetBudgetPeriod",
			Handler:    _Finance_GetBudgetPeriod_Handler,
		},
		{
			MethodName: "CreateExchangeRate",
			Handler:    _Finance_CreateExchangeRate_Handler,
		},
		{
			MethodName: "ListExchangeRates",
			Handler:    _Finance_ListExchangeRates_Handler,
		},
		{
			MethodName: "DeleteExchangeRate",
			Handler:    _Finance_DeleteExchangeRate_Handler,
		},
		{
			MethodName: "CreateExpense",
			Handler:    _Finance_CreateExpense_Handler,
		},
		{
			MethodName: "UpdateExpense",
			Handler:    _Finance_UpdateExpense_Handler,
		},
		{
			MethodName: "DeleteTransaction",
			Handler:    _Finance_DeleteTransaction_Handler,
		},
		{
			MethodName: "ListTransactions",
			Handler:    _Finance_ListTransactions_Handler,
		},
		{
			MethodName: "GetInsights",
			Handler:    _Finance_GetInsights_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "saturn/finance/v1/finance.proto",
}
