// Code generated by protoc-gen-go-sdk. DO NOT EDIT.
package financev1

import (
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

import (
	"context"
	"fmt"
	"strings"

	"github.com/masterkeysrd/saturn/apis/saturn"
)

var (
	_ = fmt.Sprintf
	_ = strings.TrimSpace
)

// Client provides typed HTTP SDK operations for the Finance service.
type Client struct {
	base *saturn.Client
}

// NewClient creates a new Finance HTTP SDK client.
func NewClient(cfg saturn.Config) *Client {
	return &Client{base: saturn.NewClient(cfg)}
}

// ConfigureFinance executes POST /api/v1/finance/settings.
func (c *Client) ConfigureFinance(ctx context.Context, req *ConfigureFinanceRequest) (*FinanceSettings, error) {
	var resp FinanceSettings
	path := "/api/v1/finance/settings"
	var query []string
	if len(query) > 0 {
		path += "?" + strings.Join(query, "&")
	}
	if err := c.base.Do(ctx, "POST", path, req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// GetFinanceSettings executes GET /api/v1/finance/settings.
func (c *Client) GetFinanceSettings(ctx context.Context, req *GetFinanceSettingsRequest) (*FinanceSettings, error) {
	var resp FinanceSettings
	path := "/api/v1/finance/settings"
	var query []string
	if len(query) > 0 {
		path += "?" + strings.Join(query, "&")
	}
	if err := c.base.Do(ctx, "GET", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// CreateBudget executes POST /api/v1/finance/budgets.
func (c *Client) CreateBudget(ctx context.Context, req *CreateBudgetRequest) (*Budget, error) {
	var resp Budget
	path := "/api/v1/finance/budgets"
	var query []string
	if len(query) > 0 {
		path += "?" + strings.Join(query, "&")
	}
	payload := req.GetBudget()
	if payload == nil {
		return nil, fmt.Errorf("budget payload is required")
	}
	if err := c.base.Do(ctx, "POST", path, payload, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// GetBudget executes GET /api/v1/finance/budgets/{id}.
func (c *Client) GetBudget(ctx context.Context, req *GetBudgetRequest) (*Budget, error) {
	var resp Budget
	path := fmt.Sprintf("/api/v1/finance/budgets/%s", req.GetId())
	var query []string
	if len(query) > 0 {
		path += "?" + strings.Join(query, "&")
	}
	if err := c.base.Do(ctx, "GET", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// UpdateBudget executes PATCH /api/v1/finance/budgets/{id}.
func (c *Client) UpdateBudget(ctx context.Context, req *UpdateBudgetRequest) (*Budget, error) {
	var resp Budget
	path := fmt.Sprintf("/api/v1/finance/budgets/%s", req.GetId())
	var query []string
	if req.Version != nil {
		query = append(query, fmt.Sprintf("version=%d", req.GetVersion()))
	}
	if req.UpdateMask != nil {
		for _, p := range req.GetUpdateMask().GetPaths() {
			query = append(query, fmt.Sprintf("update_mask.paths=%s", p))
		}
	}
	if len(query) > 0 {
		path += "?" + strings.Join(query, "&")
	}
	payload := req.GetBudget()
	if payload == nil {
		return nil, fmt.Errorf("budget payload is required")
	}
	if err := c.base.Do(ctx, "PATCH", path, payload, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// DeleteBudget executes DELETE /api/v1/finance/budgets/{id}.
func (c *Client) DeleteBudget(ctx context.Context, req *DeleteBudgetRequest) (*emptypb.Empty, error) {
	var resp emptypb.Empty
	path := fmt.Sprintf("/api/v1/finance/budgets/%s", req.GetId())
	var query []string
	if req.Version != nil {
		query = append(query, fmt.Sprintf("version=%d", req.GetVersion()))
	}
	if len(query) > 0 {
		path += "?" + strings.Join(query, "&")
	}
	if err := c.base.Do(ctx, "DELETE", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// ListBudgets executes GET /api/v1/finance/budgets.
func (c *Client) ListBudgets(ctx context.Context, req *ListBudgetsRequest) (*ListBudgetsResponse, error) {
	var resp ListBudgetsResponse
	path := "/api/v1/finance/budgets"
	var query []string
	if req.View != nil {
		query = append(query, "view="+req.GetView().String())
	}
	for _, st := range req.GetStatuses() {
		query = append(query, "statuses="+st.String())
	}
	if len(query) > 0 {
		path += "?" + strings.Join(query, "&")
	}
	if err := c.base.Do(ctx, "GET", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// GetBudgetPeriod executes GET /api/v1/finance/budgets/{budget_id}/period.
func (c *Client) GetBudgetPeriod(ctx context.Context, req *GetBudgetPeriodRequest) (*BudgetPeriod, error) {
	var resp BudgetPeriod
	path := fmt.Sprintf("/api/v1/finance/budgets/%s/period", req.GetBudgetId())
	var query []string
	if len(query) > 0 {
		path += "?" + strings.Join(query, "&")
	}
	if err := c.base.Do(ctx, "GET", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// CreateExchangeRate executes POST /api/v1/finance/exchange-rates.
func (c *Client) CreateExchangeRate(ctx context.Context, req *CreateExchangeRateRequest) (*ExchangeRate, error) {
	var resp ExchangeRate
	path := "/api/v1/finance/exchange-rates"
	var query []string
	if len(query) > 0 {
		path += "?" + strings.Join(query, "&")
	}
	payload := req.GetExchangeRate()
	if payload == nil {
		return nil, fmt.Errorf("exchange_rate payload is required")
	}
	if err := c.base.Do(ctx, "POST", path, payload, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// GetExchangeRate executes GET /api/v1/finance/exchange-rates/{id}.
func (c *Client) GetExchangeRate(ctx context.Context, req *GetExchangeRateRequest) (*ExchangeRate, error) {
	var resp ExchangeRate
	path := fmt.Sprintf("/api/v1/finance/exchange-rates/%s", req.GetId())
	var query []string
	if len(query) > 0 {
		path += "?" + strings.Join(query, "&")
	}
	if err := c.base.Do(ctx, "GET", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// UpdateExchangeRate executes PUT /api/v1/finance/exchange-rates/{id}.
func (c *Client) UpdateExchangeRate(ctx context.Context, req *UpdateExchangeRateRequest) (*ExchangeRate, error) {
	var resp ExchangeRate
	path := fmt.Sprintf("/api/v1/finance/exchange-rates/%s", req.GetId())
	var query []string
	if len(query) > 0 {
		path += "?" + strings.Join(query, "&")
	}
	payload := req.GetExchangeRate()
	if payload == nil {
		return nil, fmt.Errorf("exchange_rate payload is required")
	}
	if err := c.base.Do(ctx, "PUT", path, payload, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// ListExchangeRates executes GET /api/v1/finance/exchange-rates.
func (c *Client) ListExchangeRates(ctx context.Context, req *ListExchangeRatesRequest) (*ListExchangeRatesResponse, error) {
	var resp ListExchangeRatesResponse
	path := "/api/v1/finance/exchange-rates"
	var query []string
	if len(query) > 0 {
		path += "?" + strings.Join(query, "&")
	}
	if err := c.base.Do(ctx, "GET", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// DeleteExchangeRate executes DELETE /api/v1/finance/exchange-rates/{id}.
func (c *Client) DeleteExchangeRate(ctx context.Context, req *DeleteExchangeRateRequest) (*emptypb.Empty, error) {
	var resp emptypb.Empty
	path := fmt.Sprintf("/api/v1/finance/exchange-rates/%s", req.GetId())
	var query []string
	if len(query) > 0 {
		path += "?" + strings.Join(query, "&")
	}
	if err := c.base.Do(ctx, "DELETE", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// CreateExpense executes POST /api/v1/finance/expenses.
func (c *Client) CreateExpense(ctx context.Context, req *CreateExpenseRequest) (*Transaction, error) {
	var resp Transaction
	path := "/api/v1/finance/expenses"
	var query []string
	if len(query) > 0 {
		path += "?" + strings.Join(query, "&")
	}
	payload := req.GetExpense()
	if payload == nil {
		return nil, fmt.Errorf("expense payload is required")
	}
	if err := c.base.Do(ctx, "POST", path, payload, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// UpdateExpense executes PUT /api/v1/finance/expenses/{id}.
func (c *Client) UpdateExpense(ctx context.Context, req *UpdateExpenseRequest) (*Transaction, error) {
	var resp Transaction
	path := fmt.Sprintf("/api/v1/finance/expenses/%s", req.GetId())
	var query []string
	if len(query) > 0 {
		path += "?" + strings.Join(query, "&")
	}
	payload := req.GetExpense()
	if payload == nil {
		return nil, fmt.Errorf("expense payload is required")
	}
	if err := c.base.Do(ctx, "PUT", path, payload, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// CreateIncome executes POST /api/v1/finance/incomes.
func (c *Client) CreateIncome(ctx context.Context, req *CreateIncomeRequest) (*Transaction, error) {
	var resp Transaction
	path := "/api/v1/finance/incomes"
	var query []string
	if len(query) > 0 {
		path += "?" + strings.Join(query, "&")
	}
	payload := req.GetIncome()
	if payload == nil {
		return nil, fmt.Errorf("income payload is required")
	}
	if err := c.base.Do(ctx, "POST", path, payload, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// UpdateIncome executes PUT /api/v1/finance/incomes/{id}.
func (c *Client) UpdateIncome(ctx context.Context, req *UpdateIncomeRequest) (*Transaction, error) {
	var resp Transaction
	path := fmt.Sprintf("/api/v1/finance/incomes/%s", req.GetId())
	var query []string
	if len(query) > 0 {
		path += "?" + strings.Join(query, "&")
	}
	payload := req.GetIncome()
	if payload == nil {
		return nil, fmt.Errorf("income payload is required")
	}
	if err := c.base.Do(ctx, "PUT", path, payload, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// DeleteTransaction executes DELETE /api/v1/finance/transactions/{id}.
func (c *Client) DeleteTransaction(ctx context.Context, req *DeleteTransactionRequest) (*emptypb.Empty, error) {
	var resp emptypb.Empty
	path := fmt.Sprintf("/api/v1/finance/transactions/%s", req.GetId())
	var query []string
	if len(query) > 0 {
		path += "?" + strings.Join(query, "&")
	}
	if err := c.base.Do(ctx, "DELETE", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// ListTransactions executes GET /api/v1/finance/transactions.
func (c *Client) ListTransactions(ctx context.Context, req *ListTransactionsRequest) (*ListTransactionsResponse, error) {
	var resp ListTransactionsResponse
	path := "/api/v1/finance/transactions"
	var query []string
	if len(query) > 0 {
		path += "?" + strings.Join(query, "&")
	}
	if err := c.base.Do(ctx, "GET", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// GetTransaction executes GET /api/v1/finance/transactions/{id}.
func (c *Client) GetTransaction(ctx context.Context, req *GetTransactionRequest) (*Transaction, error) {
	var resp Transaction
	path := fmt.Sprintf("/api/v1/finance/transactions/%s", req.GetId())
	var query []string
	if len(query) > 0 {
		path += "?" + strings.Join(query, "&")
	}
	if err := c.base.Do(ctx, "GET", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// ListTransactionEvents executes GET /api/v1/finance/transactions/{txn_id}/events.
func (c *Client) ListTransactionEvents(ctx context.Context, req *ListTransactionEventsRequest) (*ListTransactionEventsResponse, error) {
	var resp ListTransactionEventsResponse
	path := fmt.Sprintf("/api/v1/finance/transactions/%s/events", req.GetTxnId())
	var query []string
	if len(query) > 0 {
		path += "?" + strings.Join(query, "&")
	}
	if err := c.base.Do(ctx, "GET", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// GetInsights executes GET /api/v1/finance/insights.
func (c *Client) GetInsights(ctx context.Context, req *GetInsightsRequest) (*GetInsightsResponse, error) {
	var resp GetInsightsResponse
	path := "/api/v1/finance/insights"
	var query []string
	if len(query) > 0 {
		path += "?" + strings.Join(query, "&")
	}
	if err := c.base.Do(ctx, "GET", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// CreateRecurringTransaction executes POST /api/v1/finance/recurring-transactions.
func (c *Client) CreateRecurringTransaction(ctx context.Context, req *CreateRecurringTransactionRequest) (*RecurringTransaction, error) {
	var resp RecurringTransaction
	path := "/api/v1/finance/recurring-transactions"
	var query []string
	if len(query) > 0 {
		path += "?" + strings.Join(query, "&")
	}
	payload := req.GetRecurringTransaction()
	if payload == nil {
		return nil, fmt.Errorf("recurring_transaction payload is required")
	}
	if err := c.base.Do(ctx, "POST", path, payload, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// UpdateRecurringTransaction executes PATCH /api/v1/finance/recurring-transactions/{id}.
func (c *Client) UpdateRecurringTransaction(ctx context.Context, req *UpdateRecurringTransactionRequest) (*RecurringTransaction, error) {
	var resp RecurringTransaction
	path := fmt.Sprintf("/api/v1/finance/recurring-transactions/%s", req.GetId())
	var query []string
	if req.Version != nil {
		query = append(query, fmt.Sprintf("version=%d", req.GetVersion()))
	}
	if req.UpdateMask != nil {
		for _, p := range req.GetUpdateMask().GetPaths() {
			query = append(query, fmt.Sprintf("update_mask.paths=%s", p))
		}
	}
	if len(query) > 0 {
		path += "?" + strings.Join(query, "&")
	}
	payload := req.GetRecurringTransaction()
	if payload == nil {
		return nil, fmt.Errorf("recurring_transaction payload is required")
	}
	if err := c.base.Do(ctx, "PATCH", path, payload, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// DeleteRecurringTransaction executes DELETE /api/v1/finance/recurring-transactions/{id}.
func (c *Client) DeleteRecurringTransaction(ctx context.Context, req *DeleteRecurringTransactionRequest) (*emptypb.Empty, error) {
	var resp emptypb.Empty
	path := fmt.Sprintf("/api/v1/finance/recurring-transactions/%s", req.GetId())
	var query []string
	if req.Version != nil {
		query = append(query, fmt.Sprintf("version=%d", req.GetVersion()))
	}
	if len(query) > 0 {
		path += "?" + strings.Join(query, "&")
	}
	if err := c.base.Do(ctx, "DELETE", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// ListRecurringTransactions executes GET /api/v1/finance/recurring-transactions.
func (c *Client) ListRecurringTransactions(ctx context.Context, req *ListRecurringTransactionsRequest) (*ListRecurringTransactionsResponse, error) {
	var resp ListRecurringTransactionsResponse
	path := "/api/v1/finance/recurring-transactions"
	var query []string
	if len(query) > 0 {
		path += "?" + strings.Join(query, "&")
	}
	if err := c.base.Do(ctx, "GET", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// ListScheduledTransactions executes GET /api/v1/finance/scheduled-transactions.
func (c *Client) ListScheduledTransactions(ctx context.Context, req *ListScheduledTransactionsRequest) (*ListScheduledTransactionsResponse, error) {
	var resp ListScheduledTransactionsResponse
	path := "/api/v1/finance/scheduled-transactions"
	var query []string
	if len(query) > 0 {
		path += "?" + strings.Join(query, "&")
	}
	if err := c.base.Do(ctx, "GET", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// GetScheduledTransaction executes GET /api/v1/finance/scheduled-transactions/{id}.
func (c *Client) GetScheduledTransaction(ctx context.Context, req *GetScheduledTransactionRequest) (*ScheduledTransaction, error) {
	var resp ScheduledTransaction
	path := fmt.Sprintf("/api/v1/finance/scheduled-transactions/%s", req.GetId())
	var query []string
	if len(query) > 0 {
		path += "?" + strings.Join(query, "&")
	}
	if err := c.base.Do(ctx, "GET", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// ConfirmScheduledTransaction executes POST /api/v1/finance/scheduled-transactions/{transaction_id}/confirm.
func (c *Client) ConfirmScheduledTransaction(ctx context.Context, req *ConfirmScheduledTransactionRequest) (*Transaction, error) {
	var resp Transaction
	path := fmt.Sprintf("/api/v1/finance/scheduled-transactions/%s/confirm", req.GetTransactionId())
	var query []string
	if len(query) > 0 {
		path += "?" + strings.Join(query, "&")
	}
	if err := c.base.Do(ctx, "POST", path, req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// MatchScheduledTransaction executes POST /api/v1/finance/scheduled-transactions/{transaction_id}/match.
func (c *Client) MatchScheduledTransaction(ctx context.Context, req *MatchScheduledTransactionRequest) (*Transaction, error) {
	var resp Transaction
	path := fmt.Sprintf("/api/v1/finance/scheduled-transactions/%s/match", req.GetTransactionId())
	var query []string
	if len(query) > 0 {
		path += "?" + strings.Join(query, "&")
	}
	if err := c.base.Do(ctx, "POST", path, req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// SkipScheduledTransaction executes POST /api/v1/finance/scheduled-transactions/{id}:skip.
func (c *Client) SkipScheduledTransaction(ctx context.Context, req *SkipScheduledTransactionRequest) (*ScheduledTransaction, error) {
	var resp ScheduledTransaction
	path := fmt.Sprintf("/api/v1/finance/scheduled-transactions/%s:skip", req.GetId())
	var query []string
	if len(query) > 0 {
		path += "?" + strings.Join(query, "&")
	}
	if err := c.base.Do(ctx, "POST", path, req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// CreateBorrowing executes POST /api/v1/finance/borrowings.
func (c *Client) CreateBorrowing(ctx context.Context, req *CreateBorrowingRequest) (*Borrowing, error) {
	var resp Borrowing
	path := "/api/v1/finance/borrowings"
	var query []string
	if len(query) > 0 {
		path += "?" + strings.Join(query, "&")
	}
	payload := req.GetBorrowing()
	if payload == nil {
		return nil, fmt.Errorf("borrowing payload is required")
	}
	if err := c.base.Do(ctx, "POST", path, payload, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// GetBorrowing executes GET /api/v1/finance/borrowings/{id}.
func (c *Client) GetBorrowing(ctx context.Context, req *GetBorrowingRequest) (*Borrowing, error) {
	var resp Borrowing
	path := fmt.Sprintf("/api/v1/finance/borrowings/%s", req.GetId())
	var query []string
	if len(query) > 0 {
		path += "?" + strings.Join(query, "&")
	}
	if err := c.base.Do(ctx, "GET", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// ListBorrowings executes GET /api/v1/finance/borrowings.
func (c *Client) ListBorrowings(ctx context.Context, req *ListBorrowingsRequest) (*ListBorrowingsResponse, error) {
	var resp ListBorrowingsResponse
	path := "/api/v1/finance/borrowings"
	var query []string
	if len(query) > 0 {
		path += "?" + strings.Join(query, "&")
	}
	if err := c.base.Do(ctx, "GET", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// UpdateBorrowing executes PATCH /api/v1/finance/borrowings/{id}.
func (c *Client) UpdateBorrowing(ctx context.Context, req *UpdateBorrowingRequest) (*Borrowing, error) {
	var resp Borrowing
	path := fmt.Sprintf("/api/v1/finance/borrowings/%s", req.GetId())
	var query []string
	if req.Version != nil {
		query = append(query, fmt.Sprintf("version=%d", req.GetVersion()))
	}
	if req.UpdateMask != nil {
		for _, p := range req.GetUpdateMask().GetPaths() {
			query = append(query, fmt.Sprintf("update_mask.paths=%s", p))
		}
	}
	if len(query) > 0 {
		path += "?" + strings.Join(query, "&")
	}
	payload := req.GetBorrowing()
	if payload == nil {
		return nil, fmt.Errorf("borrowing payload is required")
	}
	if err := c.base.Do(ctx, "PATCH", path, payload, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// DeleteBorrowing executes DELETE /api/v1/finance/borrowings/{id}.
func (c *Client) DeleteBorrowing(ctx context.Context, req *DeleteBorrowingRequest) (*emptypb.Empty, error) {
	var resp emptypb.Empty
	path := fmt.Sprintf("/api/v1/finance/borrowings/%s", req.GetId())
	var query []string
	if len(query) > 0 {
		path += "?" + strings.Join(query, "&")
	}
	if err := c.base.Do(ctx, "DELETE", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// LogBorrowingTransaction executes POST /api/v1/finance/borrowings/{borrowing_id}/transactions.
func (c *Client) LogBorrowingTransaction(ctx context.Context, req *LogBorrowingTransactionRequest) (*Transaction, error) {
	var resp Transaction
	path := fmt.Sprintf("/api/v1/finance/borrowings/%s/transactions", req.GetBorrowingId())
	var query []string
	if len(query) > 0 {
		path += "?" + strings.Join(query, "&")
	}
	payload := req.GetTransaction()
	if payload == nil {
		return nil, fmt.Errorf("transaction payload is required")
	}
	if err := c.base.Do(ctx, "POST", path, payload, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// UpdateBorrowingTransaction executes PUT /api/v1/finance/borrowings/{borrowing_id}/transactions/{transaction_id}.
func (c *Client) UpdateBorrowingTransaction(ctx context.Context, req *UpdateBorrowingTransactionRequest) (*Transaction, error) {
	var resp Transaction
	path := fmt.Sprintf("/api/v1/finance/borrowings/%s/transactions/%s", req.GetBorrowingId(), req.GetTransactionId())
	var query []string
	if len(query) > 0 {
		path += "?" + strings.Join(query, "&")
	}
	payload := req.GetTransaction()
	if payload == nil {
		return nil, fmt.Errorf("transaction payload is required")
	}
	if err := c.base.Do(ctx, "PUT", path, payload, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// DeleteBorrowingTransaction executes DELETE /api/v1/finance/borrowings/{borrowing_id}/transactions/{transaction_id}.
func (c *Client) DeleteBorrowingTransaction(ctx context.Context, req *DeleteBorrowingTransactionRequest) (*emptypb.Empty, error) {
	var resp emptypb.Empty
	path := fmt.Sprintf("/api/v1/finance/borrowings/%s/transactions/%s", req.GetBorrowingId(), req.GetTransactionId())
	var query []string
	if len(query) > 0 {
		path += "?" + strings.Join(query, "&")
	}
	if err := c.base.Do(ctx, "DELETE", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// AdjustBorrowingBalance executes POST /api/v1/finance/borrowings/{borrowing_id}/adjust.
func (c *Client) AdjustBorrowingBalance(ctx context.Context, req *AdjustBorrowingBalanceRequest) (*Borrowing, error) {
	var resp Borrowing
	path := fmt.Sprintf("/api/v1/finance/borrowings/%s/adjust", req.GetBorrowingId())
	var query []string
	if len(query) > 0 {
		path += "?" + strings.Join(query, "&")
	}
	if err := c.base.Do(ctx, "POST", path, req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// CreateAccount executes POST /api/v1/finance/accounts.
func (c *Client) CreateAccount(ctx context.Context, req *CreateAccountRequest) (*Account, error) {
	var resp Account
	path := "/api/v1/finance/accounts"
	var query []string
	if len(query) > 0 {
		path += "?" + strings.Join(query, "&")
	}
	payload := req.GetAccount()
	if payload == nil {
		return nil, fmt.Errorf("account payload is required")
	}
	if err := c.base.Do(ctx, "POST", path, payload, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// GetAccount executes GET /api/v1/finance/accounts/{id}.
func (c *Client) GetAccount(ctx context.Context, req *GetAccountRequest) (*Account, error) {
	var resp Account
	path := fmt.Sprintf("/api/v1/finance/accounts/%s", req.GetId())
	var query []string
	if len(query) > 0 {
		path += "?" + strings.Join(query, "&")
	}
	if err := c.base.Do(ctx, "GET", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// UpdateAccount executes PATCH /api/v1/finance/accounts/{id}.
func (c *Client) UpdateAccount(ctx context.Context, req *UpdateAccountRequest) (*Account, error) {
	var resp Account
	path := fmt.Sprintf("/api/v1/finance/accounts/%s", req.GetId())
	var query []string
	if req.Version != nil {
		query = append(query, fmt.Sprintf("version=%d", req.GetVersion()))
	}
	if req.UpdateMask != nil {
		for _, p := range req.GetUpdateMask().GetPaths() {
			query = append(query, fmt.Sprintf("update_mask.paths=%s", p))
		}
	}
	if len(query) > 0 {
		path += "?" + strings.Join(query, "&")
	}
	payload := req.GetAccount()
	if payload == nil {
		return nil, fmt.Errorf("account payload is required")
	}
	if err := c.base.Do(ctx, "PATCH", path, payload, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// AdjustAccountBalance executes POST /api/v1/finance/accounts/{account_id}:adjust-balance.
func (c *Client) AdjustAccountBalance(ctx context.Context, req *AdjustAccountBalanceRequest) (*Account, error) {
	var resp Account
	path := fmt.Sprintf("/api/v1/finance/accounts/%s:adjust-balance", req.GetAccountId())
	var query []string
	if len(query) > 0 {
		path += "?" + strings.Join(query, "&")
	}
	if err := c.base.Do(ctx, "POST", path, req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// DeleteAccount executes DELETE /api/v1/finance/accounts/{id}.
func (c *Client) DeleteAccount(ctx context.Context, req *DeleteAccountRequest) (*emptypb.Empty, error) {
	var resp emptypb.Empty
	path := fmt.Sprintf("/api/v1/finance/accounts/%s", req.GetId())
	var query []string
	if req.Version != nil {
		query = append(query, fmt.Sprintf("version=%d", req.GetVersion()))
	}
	if len(query) > 0 {
		path += "?" + strings.Join(query, "&")
	}
	if err := c.base.Do(ctx, "DELETE", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// ListAccounts executes GET /api/v1/finance/accounts.
func (c *Client) ListAccounts(ctx context.Context, req *ListAccountsRequest) (*ListAccountsResponse, error) {
	var resp ListAccountsResponse
	path := "/api/v1/finance/accounts"
	var query []string
	if len(query) > 0 {
		path += "?" + strings.Join(query, "&")
	}
	if err := c.base.Do(ctx, "GET", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// CreateInstitution executes POST /api/v1/finance/institutions.
func (c *Client) CreateInstitution(ctx context.Context, req *CreateInstitutionRequest) (*Institution, error) {
	var resp Institution
	path := "/api/v1/finance/institutions"
	var query []string
	if len(query) > 0 {
		path += "?" + strings.Join(query, "&")
	}
	payload := req.GetInstitution()
	if payload == nil {
		return nil, fmt.Errorf("institution payload is required")
	}
	if err := c.base.Do(ctx, "POST", path, payload, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// UpdateInstitution executes PATCH /api/v1/finance/institutions/{id}.
func (c *Client) UpdateInstitution(ctx context.Context, req *UpdateInstitutionRequest) (*Institution, error) {
	var resp Institution
	path := fmt.Sprintf("/api/v1/finance/institutions/%s", req.GetId())
	var query []string
	if req.Version != nil {
		query = append(query, fmt.Sprintf("version=%d", req.GetVersion()))
	}
	if req.UpdateMask != nil {
		for _, p := range req.GetUpdateMask().GetPaths() {
			query = append(query, fmt.Sprintf("update_mask.paths=%s", p))
		}
	}
	if len(query) > 0 {
		path += "?" + strings.Join(query, "&")
	}
	payload := req.GetInstitution()
	if payload == nil {
		return nil, fmt.Errorf("institution payload is required")
	}
	if err := c.base.Do(ctx, "PATCH", path, payload, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// DeleteInstitution executes DELETE /api/v1/finance/institutions/{id}.
func (c *Client) DeleteInstitution(ctx context.Context, req *DeleteInstitutionRequest) (*emptypb.Empty, error) {
	var resp emptypb.Empty
	path := fmt.Sprintf("/api/v1/finance/institutions/%s", req.GetId())
	var query []string
	if req.Version != nil {
		query = append(query, fmt.Sprintf("version=%d", req.GetVersion()))
	}
	if len(query) > 0 {
		path += "?" + strings.Join(query, "&")
	}
	if err := c.base.Do(ctx, "DELETE", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// ListInstitutions executes GET /api/v1/finance/institutions.
func (c *Client) ListInstitutions(ctx context.Context, req *ListInstitutionsRequest) (*ListInstitutionsResponse, error) {
	var resp ListInstitutionsResponse
	path := "/api/v1/finance/institutions"
	var query []string
	if len(query) > 0 {
		path += "?" + strings.Join(query, "&")
	}
	if err := c.base.Do(ctx, "GET", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// ResolveInstitution executes GET /api/v1/finance/institutions:resolve.
func (c *Client) ResolveInstitution(ctx context.Context, req *ResolveInstitutionRequest) (*ResolveInstitutionResponse, error) {
	var resp ResolveInstitutionResponse
	path := "/api/v1/finance/institutions:resolve"
	var query []string
	if len(query) > 0 {
		path += "?" + strings.Join(query, "&")
	}
	if err := c.base.Do(ctx, "GET", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// CreateTransfer executes POST /api/v1/finance/transfers.
func (c *Client) CreateTransfer(ctx context.Context, req *CreateTransferRequest) (*Transfer, error) {
	var resp Transfer
	path := "/api/v1/finance/transfers"
	var query []string
	if len(query) > 0 {
		path += "?" + strings.Join(query, "&")
	}
	if err := c.base.Do(ctx, "POST", path, req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// ListTransfers executes GET /api/v1/finance/transfers.
func (c *Client) ListTransfers(ctx context.Context, req *ListTransfersRequest) (*ListTransfersResponse, error) {
	var resp ListTransfersResponse
	path := "/api/v1/finance/transfers"
	var query []string
	if len(query) > 0 {
		path += "?" + strings.Join(query, "&")
	}
	if err := c.base.Do(ctx, "GET", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// ListCurrencies executes GET /api/v1/finance/currencies.
func (c *Client) ListCurrencies(ctx context.Context, req *ListCurrenciesRequest) (*ListCurrenciesResponse, error) {
	var resp ListCurrenciesResponse
	path := "/api/v1/finance/currencies"
	var query []string
	if len(query) > 0 {
		path += "?" + strings.Join(query, "&")
	}
	if err := c.base.Do(ctx, "GET", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// ListInboxItems executes GET /api/v1/finance/inbox-items.
func (c *Client) ListInboxItems(ctx context.Context, req *ListInboxItemsRequest) (*ListInboxItemsResponse, error) {
	var resp ListInboxItemsResponse
	path := "/api/v1/finance/inbox-items"
	var query []string
	if req.Status != nil {
		query = append(query, fmt.Sprintf("status=%s", req.GetStatus().String()))
	}
	if req.DocType != nil {
		query = append(query, fmt.Sprintf("doc_type=%s", req.GetDocType().String()))
	}
	if len(query) > 0 {
		path += "?" + strings.Join(query, "&")
	}
	if err := c.base.Do(ctx, "GET", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// UpdateInboxItem executes PUT /api/v1/finance/inbox-items/{id}.
func (c *Client) UpdateInboxItem(ctx context.Context, req *UpdateInboxItemRequest) (*InboxItem, error) {
	var resp InboxItem
	path := fmt.Sprintf("/api/v1/finance/inbox-items/%s", req.GetId())
	var query []string
	if len(query) > 0 {
		path += "?" + strings.Join(query, "&")
	}
	payload := req.GetInboxItem()
	if payload == nil {
		return nil, fmt.Errorf("inbox_item payload is required")
	}
	if err := c.base.Do(ctx, "PUT", path, payload, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// ApproveInboxItem executes POST /api/v1/finance/inbox-items/{id}:approve.
func (c *Client) ApproveInboxItem(ctx context.Context, req *ApproveInboxItemRequest) (*InboxItem, error) {
	var resp InboxItem
	path := fmt.Sprintf("/api/v1/finance/inbox-items/%s:approve", req.GetId())
	var query []string
	if len(query) > 0 {
		path += "?" + strings.Join(query, "&")
	}
	if err := c.base.Do(ctx, "POST", path, req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// DiscardInboxItem executes DELETE /api/v1/finance/inbox-items/{id}.
func (c *Client) DiscardInboxItem(ctx context.Context, req *DiscardInboxItemRequest) (*emptypb.Empty, error) {
	var resp emptypb.Empty
	path := fmt.Sprintf("/api/v1/finance/inbox-items/%s", req.GetId())
	var query []string
	if len(query) > 0 {
		path += "?" + strings.Join(query, "&")
	}
	if err := c.base.Do(ctx, "DELETE", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// ImportStatement executes POST /api/v1/finance/accounts/{account_id}/statements:import.
func (c *Client) ImportStatement(ctx context.Context, req *ImportStatementRequest) (*Statement, error) {
	var resp Statement
	path := fmt.Sprintf("/api/v1/finance/accounts/%s/statements:import", req.GetAccountId())
	var query []string
	if len(query) > 0 {
		path += "?" + strings.Join(query, "&")
	}
	if err := c.base.Do(ctx, "POST", path, req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// GetStatement executes GET /api/v1/finance/statements/{id}.
func (c *Client) GetStatement(ctx context.Context, req *GetStatementRequest) (*Statement, error) {
	var resp Statement
	path := fmt.Sprintf("/api/v1/finance/statements/%s", req.GetId())
	var query []string
	if len(query) > 0 {
		path += "?" + strings.Join(query, "&")
	}
	if err := c.base.Do(ctx, "GET", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// DeleteStatement executes DELETE /api/v1/finance/statements/{id}.
func (c *Client) DeleteStatement(ctx context.Context, req *DeleteStatementRequest) (*emptypb.Empty, error) {
	var resp emptypb.Empty
	path := fmt.Sprintf("/api/v1/finance/statements/%s", req.GetId())
	var query []string
	if req.Version != nil {
		query = append(query, fmt.Sprintf("version=%d", req.GetVersion()))
	}
	if len(query) > 0 {
		path += "?" + strings.Join(query, "&")
	}
	if err := c.base.Do(ctx, "DELETE", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// ListStatements executes GET /api/v1/finance/statements.
func (c *Client) ListStatements(ctx context.Context, req *ListStatementsRequest) (*ListStatementsResponse, error) {
	var resp ListStatementsResponse
	path := "/api/v1/finance/statements"
	var query []string
	if len(query) > 0 {
		path += "?" + strings.Join(query, "&")
	}
	if err := c.base.Do(ctx, "GET", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// ListStatementLines executes GET /api/v1/finance/statements/{statement_id}/lines.
func (c *Client) ListStatementLines(ctx context.Context, req *ListStatementLinesRequest) (*ListStatementLinesResponse, error) {
	var resp ListStatementLinesResponse
	path := fmt.Sprintf("/api/v1/finance/statements/%s/lines", req.GetStatementId())
	var query []string
	if len(query) > 0 {
		path += "?" + strings.Join(query, "&")
	}
	if err := c.base.Do(ctx, "GET", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// UpdateStatementLine executes PATCH /api/v1/finance/statement-lines/{id}.
func (c *Client) UpdateStatementLine(ctx context.Context, req *UpdateStatementLineRequest) (*StatementLine, error) {
	var resp StatementLine
	path := fmt.Sprintf("/api/v1/finance/statement-lines/%s", req.GetId())
	var query []string
	if req.Version != nil {
		query = append(query, fmt.Sprintf("version=%d", req.GetVersion()))
	}
	if req.UpdateMask != nil {
		for _, p := range req.GetUpdateMask().GetPaths() {
			query = append(query, fmt.Sprintf("update_mask.paths=%s", p))
		}
	}
	if len(query) > 0 {
		path += "?" + strings.Join(query, "&")
	}
	payload := req.GetStatementLine()
	if payload == nil {
		return nil, fmt.Errorf("statement_line payload is required")
	}
	if err := c.base.Do(ctx, "PATCH", path, payload, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// UpdateStatement executes PATCH /api/v1/finance/statements/{id}.
func (c *Client) UpdateStatement(ctx context.Context, req *UpdateStatementRequest) (*Statement, error) {
	var resp Statement
	path := fmt.Sprintf("/api/v1/finance/statements/%s", req.GetId())
	var query []string
	if req.Version != nil {
		query = append(query, fmt.Sprintf("version=%d", req.GetVersion()))
	}
	if req.UpdateMask != nil {
		for _, p := range req.GetUpdateMask().GetPaths() {
			query = append(query, fmt.Sprintf("update_mask.paths=%s", p))
		}
	}
	if len(query) > 0 {
		path += "?" + strings.Join(query, "&")
	}
	payload := req.GetStatement()
	if payload == nil {
		return nil, fmt.Errorf("statement payload is required")
	}
	if err := c.base.Do(ctx, "PATCH", path, payload, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// CompleteStatement executes POST /api/v1/finance/statements/{id}:complete.
func (c *Client) CompleteStatement(ctx context.Context, req *CompleteStatementRequest) (*Statement, error) {
	var resp Statement
	path := fmt.Sprintf("/api/v1/finance/statements/%s:complete", req.GetId())
	var query []string
	if len(query) > 0 {
		path += "?" + strings.Join(query, "&")
	}
	if err := c.base.Do(ctx, "POST", path, req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}
