---
name: saturn

services:
  saturn:
    build:
      context: ../..
      dockerfile: build/saturn/Dockerfile
    image: saturn:latest
    restart: unless-stopped
    ports:
         - "8080:8080"
    environment:
      SATURN_GATEWAY_ADDR: ":8080"
      SATURN_LOG_LEVEL: info
    volumes:
         - saturn-data:/data
    develop:
      watch:
         - action: rebuild
           path: cmd
           target: /usr/local/bin/saturn
         - action: rebuild
           path: go.mod
           target: /usr/local/bin/saturn
         - action: rebuild
           path: go.sum
           target: /usr/local/bin/saturn

volumes:
  saturn-data:
