// Code generated by protoc-gen-go-sdk. DO NOT EDIT.
package identityv1

import (
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

import (
	"context"
	"fmt"
	"strings"

	"github.com/masterkeysrd/saturn/apis/saturn"
)

var (
	_ = fmt.Sprintf
	_ = strings.TrimSpace
)

// Client provides typed HTTP SDK operations for the Identity service.
type Client struct {
	base *saturn.Client
}

// NewClient creates a new Identity HTTP SDK client.
func NewClient(cfg saturn.Config) *Client {
	return &Client{base: saturn.NewClient(cfg)}
}

// LoginUser executes POST /api/v1/identity/users:login.
func (c *Client) LoginUser(ctx context.Context, req *LoginUserRequest) (*LoginUserResponse, error) {
	var resp LoginUserResponse
	path := "/api/v1/identity/users:login"
	var query []string
	if len(query) > 0 {
		path += "?" + strings.Join(query, "&")
	}
	if err := c.base.Do(ctx, "POST", path, req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// RegisterUser executes POST /api/v1/identity/users:register.
func (c *Client) RegisterUser(ctx context.Context, req *RegisterUserRequest) (*User, error) {
	var resp User
	path := "/api/v1/identity/users:register"
	var query []string
	if len(query) > 0 {
		path += "?" + strings.Join(query, "&")
	}
	if err := c.base.Do(ctx, "POST", path, req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// RefreshSession executes POST /api/v1/identity/sessions:refresh.
func (c *Client) RefreshSession(ctx context.Context, req *RefreshSessionRequest) (*RefreshSessionResponse, error) {
	var resp RefreshSessionResponse
	path := "/api/v1/identity/sessions:refresh"
	var query []string
	if len(query) > 0 {
		path += "?" + strings.Join(query, "&")
	}
	if err := c.base.Do(ctx, "POST", path, req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// Logout executes POST /api/v1/identity/sessions:logout.
func (c *Client) Logout(ctx context.Context, req *LogoutRequest) (*LogoutResponse, error) {
	var resp LogoutResponse
	path := "/api/v1/identity/sessions:logout"
	var query []string
	if len(query) > 0 {
		path += "?" + strings.Join(query, "&")
	}
	if err := c.base.Do(ctx, "POST", path, req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// GetCurrentUser executes GET /api/v1/identity/users/me.
func (c *Client) GetCurrentUser(ctx context.Context, req *GetCurrentUserRequest) (*User, error) {
	var resp User
	path := "/api/v1/identity/users/me"
	var query []string
	if len(query) > 0 {
		path += "?" + strings.Join(query, "&")
	}
	if err := c.base.Do(ctx, "GET", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// ListActiveSessions executes GET /api/v1/identity/sessions.
func (c *Client) ListActiveSessions(ctx context.Context, req *ListActiveSessionsRequest) (*ListActiveSessionsResponse, error) {
	var resp ListActiveSessionsResponse
	path := "/api/v1/identity/sessions"
	var query []string
	if len(query) > 0 {
		path += "?" + strings.Join(query, "&")
	}
	if err := c.base.Do(ctx, "GET", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// RevokeSession executes POST /api/v1/identity/sessions/{session_id}:revoke.
func (c *Client) RevokeSession(ctx context.Context, req *RevokeSessionRequest) (*RevokeSessionResponse, error) {
	var resp RevokeSessionResponse
	path := fmt.Sprintf("/api/v1/identity/sessions/%s:revoke", req.GetSessionId())
	var query []string
	if len(query) > 0 {
		path += "?" + strings.Join(query, "&")
	}
	if err := c.base.Do(ctx, "POST", path, req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// RevokeAllSessions executes POST /api/v1/identity/sessions:revoke-all.
func (c *Client) RevokeAllSessions(ctx context.Context, req *RevokeAllSessionsRequest) (*RevokeAllSessionsResponse, error) {
	var resp RevokeAllSessionsResponse
	path := "/api/v1/identity/sessions:revoke-all"
	var query []string
	if len(query) > 0 {
		path += "?" + strings.Join(query, "&")
	}
	if err := c.base.Do(ctx, "POST", path, req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// ListMySecurityEvents executes GET /api/v1/identity/users/me/security-events.
func (c *Client) ListMySecurityEvents(ctx context.Context, req *ListMySecurityEventsRequest) (*ListMySecurityEventsResponse, error) {
	var resp ListMySecurityEventsResponse
	path := "/api/v1/identity/users/me/security-events"
	var query []string
	if req.GetLimit() != 0 {
		query = append(query, fmt.Sprintf("limit=%d", req.GetLimit()))
	}
	if req.GetNextPageToken() != "" {
		query = append(query, fmt.Sprintf("next_page_token=%s", req.GetNextPageToken()))
	}
	if len(query) > 0 {
		path += "?" + strings.Join(query, "&")
	}
	if err := c.base.Do(ctx, "GET", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// ListMFAFactors executes GET /api/v1/identity/mfa/factors.
func (c *Client) ListMFAFactors(ctx context.Context, req *ListMFAFactorsRequest) (*ListMFAFactorsResponse, error) {
	var resp ListMFAFactorsResponse
	path := "/api/v1/identity/mfa/factors"
	var query []string
	if len(query) > 0 {
		path += "?" + strings.Join(query, "&")
	}
	if err := c.base.Do(ctx, "GET", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// DeleteMFAFactor executes DELETE /api/v1/identity/mfa/factors/{factor_id}.
func (c *Client) DeleteMFAFactor(ctx context.Context, req *DeleteMFAFactorRequest) (*emptypb.Empty, error) {
	var resp emptypb.Empty
	path := fmt.Sprintf("/api/v1/identity/mfa/factors/%s", req.GetFactorId())
	var query []string
	if len(query) > 0 {
		path += "?" + strings.Join(query, "&")
	}
	if err := c.base.Do(ctx, "DELETE", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// SetPrimaryMFAFactor executes POST /api/v1/identity/mfa/factors/{factor_id}:set-primary.
func (c *Client) SetPrimaryMFAFactor(ctx context.Context, req *SetPrimaryMFAFactorRequest) (*emptypb.Empty, error) {
	var resp emptypb.Empty
	path := fmt.Sprintf("/api/v1/identity/mfa/factors/%s:set-primary", req.GetFactorId())
	var query []string
	if len(query) > 0 {
		path += "?" + strings.Join(query, "&")
	}
	if err := c.base.Do(ctx, "POST", path, req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// SetupTOTP executes POST /api/v1/identity/mfa/totp:setup.
func (c *Client) SetupTOTP(ctx context.Context, req *SetupTOTPRequest) (*SetupTOTPResponse, error) {
	var resp SetupTOTPResponse
	path := "/api/v1/identity/mfa/totp:setup"
	var query []string
	if len(query) > 0 {
		path += "?" + strings.Join(query, "&")
	}
	if err := c.base.Do(ctx, "POST", path, req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// ConfirmTOTP executes POST /api/v1/identity/mfa/totp:confirm.
func (c *Client) ConfirmTOTP(ctx context.Context, req *ConfirmTOTPRequest) (*ConfirmTOTPResponse, error) {
	var resp ConfirmTOTPResponse
	path := "/api/v1/identity/mfa/totp:confirm"
	var query []string
	if len(query) > 0 {
		path += "?" + strings.Join(query, "&")
	}
	if err := c.base.Do(ctx, "POST", path, req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// RegenerateBackupCodes executes POST /api/v1/identity/mfa/backup-codes:regenerate.
func (c *Client) RegenerateBackupCodes(ctx context.Context, req *RegenerateBackupCodesRequest) (*RegenerateBackupCodesResponse, error) {
	var resp RegenerateBackupCodesResponse
	path := "/api/v1/identity/mfa/backup-codes:regenerate"
	var query []string
	if len(query) > 0 {
		path += "?" + strings.Join(query, "&")
	}
	if err := c.base.Do(ctx, "POST", path, req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}
