// Code generated by protoc-gen-go-sdk. DO NOT EDIT.
package identityv1

import (
	"context"
	"fmt"
	"strings"

	"github.com/masterkeysrd/saturn/apis/saturn"
)

var (
	_ = fmt.Sprintf
	_ = strings.TrimSpace
)

// Client provides typed HTTP SDK operations for the Identity service.
type Client struct {
	base *saturn.Client
}

// NewClient creates a new Identity HTTP SDK client.
func NewClient(cfg saturn.Config) *Client {
	return &Client{base: saturn.NewClient(cfg)}
}

// LoginUser executes POST /api/v1/identity/users:login.
func (c *Client) LoginUser(ctx context.Context, req *LoginUserRequest) (*LoginUserResponse, error) {
	var resp LoginUserResponse
	path := "/api/v1/identity/users:login"
	if err := c.base.Do(ctx, "POST", path, req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// RegisterUser executes POST /api/v1/identity/users:register.
func (c *Client) RegisterUser(ctx context.Context, req *RegisterUserRequest) (*User, error) {
	var resp User
	path := "/api/v1/identity/users:register"
	if err := c.base.Do(ctx, "POST", path, req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// RefreshSession executes POST /api/v1/identity/sessions:refresh.
func (c *Client) RefreshSession(ctx context.Context, req *RefreshSessionRequest) (*RefreshSessionResponse, error) {
	var resp RefreshSessionResponse
	path := "/api/v1/identity/sessions:refresh"
	if err := c.base.Do(ctx, "POST", path, req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// Logout executes POST /api/v1/identity/sessions:logout.
func (c *Client) Logout(ctx context.Context, req *LogoutRequest) (*LogoutResponse, error) {
	var resp LogoutResponse
	path := "/api/v1/identity/sessions:logout"
	if err := c.base.Do(ctx, "POST", path, req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// GetCurrentUser executes GET /api/v1/identity/users/me.
func (c *Client) GetCurrentUser(ctx context.Context, req *GetCurrentUserRequest) (*User, error) {
	var resp User
	path := "/api/v1/identity/users/me"
	if err := c.base.Do(ctx, "GET", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// ListActiveSessions executes GET /api/v1/identity/sessions.
func (c *Client) ListActiveSessions(ctx context.Context, req *ListActiveSessionsRequest) (*ListActiveSessionsResponse, error) {
	var resp ListActiveSessionsResponse
	path := "/api/v1/identity/sessions"
	if err := c.base.Do(ctx, "GET", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// RevokeSession executes POST /api/v1/identity/sessions/{session_id}:revoke.
func (c *Client) RevokeSession(ctx context.Context, req *RevokeSessionRequest) (*RevokeSessionResponse, error) {
	var resp RevokeSessionResponse
	path := fmt.Sprintf("/api/v1/identity/sessions/%s:revoke", req.GetSessionId())
	if err := c.base.Do(ctx, "POST", path, req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// RevokeAllSessions executes POST /api/v1/identity/sessions:revoke-all.
func (c *Client) RevokeAllSessions(ctx context.Context, req *RevokeAllSessionsRequest) (*RevokeAllSessionsResponse, error) {
	var resp RevokeAllSessionsResponse
	path := "/api/v1/identity/sessions:revoke-all"
	if err := c.base.Do(ctx, "POST", path, req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// ListMySecurityEvents executes GET /api/v1/identity/users/me/security-events.
func (c *Client) ListMySecurityEvents(ctx context.Context, req *ListMySecurityEventsRequest) (*ListMySecurityEventsResponse, error) {
	var resp ListMySecurityEventsResponse
	path := "/api/v1/identity/users/me/security-events"
	if err := c.base.Do(ctx, "GET", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}
