// Code generated by loggen. DO NOT EDIT.

package financeapp

import (
	"context"
	agentapp "github.com/masterkeysrd/saturn/internal/application/agent"
	"github.com/masterkeysrd/saturn/internal/domain/finance"
	"github.com/masterkeysrd/saturn/internal/platform/log"
	"time"
)

// LoggingCoordinator wraps a Coordinator and logs operation durations and errors.
type LoggingCoordinator struct {
	next   Coordinator
	logger log.Logger
}

// NewLoggingCoordinator creates a new LoggingCoordinator decorator.
func NewLoggingCoordinator(next Coordinator, logger log.Logger) *LoggingCoordinator {
	return &LoggingCoordinator{
		next:   next,
		logger: logger,
	}
}

// Compile-time interface assertion.
var _ Coordinator = (*LoggingCoordinator)(nil)

// ConfigureFinance executes next.ConfigureFinance and logs execution duration and errors.
func (l *LoggingCoordinator) ConfigureFinance(ctx context.Context, req *ConfigureFinanceRequest) (*finance.FinanceSettings, error) {
	start := time.Now()
	res, err := l.next.ConfigureFinance(ctx, req)
	duration := time.Since(start)

	if err != nil {
		l.logger.Error(ctx, "finance.ConfigureFinance failed",
			log.String("component", "finance"),
			log.String("operation", "ConfigureFinance"),
			log.Duration("duration", duration),
			log.Err(err),
		)
		return nil, err
	}

	l.logger.Info(ctx, "finance.ConfigureFinance completed",
		log.String("component", "finance"),
		log.String("operation", "ConfigureFinance"),
		log.Duration("duration", duration),
	)
	return res, nil
}

// GetFinanceSettings executes next.GetFinanceSettings and logs execution duration and errors.
func (l *LoggingCoordinator) GetFinanceSettings(ctx context.Context) (*finance.FinanceSettings, error) {
	start := time.Now()
	res, err := l.next.GetFinanceSettings(ctx)
	duration := time.Since(start)

	if err != nil {
		l.logger.Error(ctx, "finance.GetFinanceSettings failed",
			log.String("component", "finance"),
			log.String("operation", "GetFinanceSettings"),
			log.Duration("duration", duration),
			log.Err(err),
		)
		return nil, err
	}

	l.logger.Info(ctx, "finance.GetFinanceSettings completed",
		log.String("component", "finance"),
		log.String("operation", "GetFinanceSettings"),
		log.Duration("duration", duration),
	)
	return res, nil
}

// ListCurrencies executes next.ListCurrencies and logs execution duration and errors.
func (l *LoggingCoordinator) ListCurrencies(ctx context.Context) ([]finance.CurrencyInfo, error) {
	start := time.Now()
	res, err := l.next.ListCurrencies(ctx)
	duration := time.Since(start)

	if err != nil {
		l.logger.Error(ctx, "finance.ListCurrencies failed",
			log.String("component", "finance"),
			log.String("operation", "ListCurrencies"),
			log.Duration("duration", duration),
			log.Err(err),
		)
		return nil, err
	}

	l.logger.Info(ctx, "finance.ListCurrencies completed",
		log.String("component", "finance"),
		log.String("operation", "ListCurrencies"),
		log.Duration("duration", duration),
	)
	return res, nil
}

// ImportStatement executes next.ImportStatement and logs execution duration and errors.
func (l *LoggingCoordinator) ImportStatement(ctx context.Context, accountID finance.AccountID, stmt *finance.Statement) (*finance.Statement, error) {
	start := time.Now()
	res, err := l.next.ImportStatement(ctx, accountID, stmt)
	duration := time.Since(start)

	if err != nil {
		l.logger.Error(ctx, "finance.ImportStatement failed",
			log.String("component", "finance"),
			log.String("operation", "ImportStatement"),
			log.Duration("duration", duration),
			log.Err(err),
		)
		return nil, err
	}

	l.logger.Info(ctx, "finance.ImportStatement completed",
		log.String("component", "finance"),
		log.String("operation", "ImportStatement"),
		log.Duration("duration", duration),
	)
	return res, nil
}

// DeleteStatement executes next.DeleteStatement and logs execution duration and errors.
func (l *LoggingCoordinator) DeleteStatement(ctx context.Context, id finance.StatementID, opts finance.DeleteOptions) error {
	start := time.Now()
	err := l.next.DeleteStatement(ctx, id, opts)
	duration := time.Since(start)

	if err != nil {
		l.logger.Error(ctx, "finance.DeleteStatement failed",
			log.String("component", "finance"),
			log.String("operation", "DeleteStatement"),
			log.Duration("duration", duration),
			log.Err(err),
		)
		return err
	}

	l.logger.Info(ctx, "finance.DeleteStatement completed",
		log.String("component", "finance"),
		log.String("operation", "DeleteStatement"),
		log.Duration("duration", duration),
	)
	return nil
}

// UpdateStatement executes next.UpdateStatement and logs execution duration and errors.
func (l *LoggingCoordinator) UpdateStatement(ctx context.Context, stmt *finance.Statement, mask []string) (*finance.Statement, error) {
	start := time.Now()
	res, err := l.next.UpdateStatement(ctx, stmt, mask)
	duration := time.Since(start)

	if err != nil {
		l.logger.Error(ctx, "finance.UpdateStatement failed",
			log.String("component", "finance"),
			log.String("operation", "UpdateStatement"),
			log.Duration("duration", duration),
			log.Err(err),
		)
		return nil, err
	}

	l.logger.Info(ctx, "finance.UpdateStatement completed",
		log.String("component", "finance"),
		log.String("operation", "UpdateStatement"),
		log.Duration("duration", duration),
	)
	return res, nil
}

// UpdateStatementLine executes next.UpdateStatementLine and logs execution duration and errors.
func (l *LoggingCoordinator) UpdateStatementLine(ctx context.Context, line *finance.StatementLine, mask []string) (*finance.StatementLine, error) {
	start := time.Now()
	res, err := l.next.UpdateStatementLine(ctx, line, mask)
	duration := time.Since(start)

	if err != nil {
		l.logger.Error(ctx, "finance.UpdateStatementLine failed",
			log.String("component", "finance"),
			log.String("operation", "UpdateStatementLine"),
			log.Duration("duration", duration),
			log.Err(err),
		)
		return nil, err
	}

	l.logger.Info(ctx, "finance.UpdateStatementLine completed",
		log.String("component", "finance"),
		log.String("operation", "UpdateStatementLine"),
		log.Duration("duration", duration),
	)
	return res, nil
}

// CompleteStatement executes next.CompleteStatement and logs execution duration and errors.
func (l *LoggingCoordinator) CompleteStatement(ctx context.Context, id finance.StatementID) (*finance.Statement, error) {
	start := time.Now()
	res, err := l.next.CompleteStatement(ctx, id)
	duration := time.Since(start)

	if err != nil {
		l.logger.Error(ctx, "finance.CompleteStatement failed",
			log.String("component", "finance"),
			log.String("operation", "CompleteStatement"),
			log.Duration("duration", duration),
			log.Err(err),
		)
		return nil, err
	}

	l.logger.Info(ctx, "finance.CompleteStatement completed",
		log.String("component", "finance"),
		log.String("operation", "CompleteStatement"),
		log.Duration("duration", duration),
	)
	return res, nil
}

// InvertStatementSigns executes next.InvertStatementSigns and logs execution duration and errors.
func (l *LoggingCoordinator) InvertStatementSigns(ctx context.Context, id finance.StatementID) (*finance.Statement, []*finance.StatementLine, error) {
	start := time.Now()
	res1, res2, err := l.next.InvertStatementSigns(ctx, id)
	duration := time.Since(start)

	if err != nil {
		l.logger.Error(ctx, "finance.InvertStatementSigns failed",
			log.String("component", "finance"),
			log.String("operation", "InvertStatementSigns"),
			log.Duration("duration", duration),
			log.Err(err),
		)
		return nil, nil, err
	}

	l.logger.Info(ctx, "finance.InvertStatementSigns completed",
		log.String("component", "finance"),
		log.String("operation", "InvertStatementSigns"),
		log.Duration("duration", duration),
	)
	return res1, res2, nil
}

// IngestStatementDocument executes next.IngestStatementDocument and logs execution duration and errors.
func (l *LoggingCoordinator) IngestStatementDocument(ctx context.Context, req *StatementDocumentRequest) (*IngestStatementResult, error) {
	start := time.Now()
	res, err := l.next.IngestStatementDocument(ctx, req)
	duration := time.Since(start)

	if err != nil {
		l.logger.Error(ctx, "finance.IngestStatementDocument failed",
			log.String("component", "finance"),
			log.String("operation", "IngestStatementDocument"),
			log.Duration("duration", duration),
			log.Err(err),
		)
		return nil, err
	}

	l.logger.Info(ctx, "finance.IngestStatementDocument completed",
		log.String("component", "finance"),
		log.String("operation", "IngestStatementDocument"),
		log.Duration("duration", duration),
	)
	return res, nil
}

// AnalyzeStatementDocument executes next.AnalyzeStatementDocument and logs execution duration and errors.
func (l *LoggingCoordinator) AnalyzeStatementDocument(ctx context.Context, req *StatementDocumentRequest) (*StatementIngestionState, error) {
	start := time.Now()
	res, err := l.next.AnalyzeStatementDocument(ctx, req)
	duration := time.Since(start)

	if err != nil {
		l.logger.Error(ctx, "finance.AnalyzeStatementDocument failed",
			log.String("component", "finance"),
			log.String("operation", "AnalyzeStatementDocument"),
			log.Duration("duration", duration),
			log.Err(err),
		)
		return nil, err
	}

	l.logger.Info(ctx, "finance.AnalyzeStatementDocument completed",
		log.String("component", "finance"),
		log.String("operation", "AnalyzeStatementDocument"),
		log.Duration("duration", duration),
	)
	return res, nil
}

// CreateAccount executes next.CreateAccount and logs execution duration and errors.
func (l *LoggingCoordinator) CreateAccount(ctx context.Context, req *CreateAccountRequest) (*finance.Account, error) {
	start := time.Now()
	res, err := l.next.CreateAccount(ctx, req)
	duration := time.Since(start)

	if err != nil {
		l.logger.Error(ctx, "finance.CreateAccount failed",
			log.String("component", "finance"),
			log.String("operation", "CreateAccount"),
			log.Duration("duration", duration),
			log.Err(err),
		)
		return nil, err
	}

	l.logger.Info(ctx, "finance.CreateAccount completed",
		log.String("component", "finance"),
		log.String("operation", "CreateAccount"),
		log.Duration("duration", duration),
	)
	return res, nil
}

// UpdateAccount executes next.UpdateAccount and logs execution duration and errors.
func (l *LoggingCoordinator) UpdateAccount(ctx context.Context, req *UpdateAccountRequest) (*finance.Account, error) {
	start := time.Now()
	res, err := l.next.UpdateAccount(ctx, req)
	duration := time.Since(start)

	if err != nil {
		l.logger.Error(ctx, "finance.UpdateAccount failed",
			log.String("component", "finance"),
			log.String("operation", "UpdateAccount"),
			log.Duration("duration", duration),
			log.Err(err),
		)
		return nil, err
	}

	l.logger.Info(ctx, "finance.UpdateAccount completed",
		log.String("component", "finance"),
		log.String("operation", "UpdateAccount"),
		log.Duration("duration", duration),
	)
	return res, nil
}

// DeleteAccount executes next.DeleteAccount and logs execution duration and errors.
func (l *LoggingCoordinator) DeleteAccount(ctx context.Context, id finance.AccountID, opts finance.DeleteOptions) error {
	start := time.Now()
	err := l.next.DeleteAccount(ctx, id, opts)
	duration := time.Since(start)

	if err != nil {
		l.logger.Error(ctx, "finance.DeleteAccount failed",
			log.String("component", "finance"),
			log.String("operation", "DeleteAccount"),
			log.Duration("duration", duration),
			log.Err(err),
		)
		return err
	}

	l.logger.Info(ctx, "finance.DeleteAccount completed",
		log.String("component", "finance"),
		log.String("operation", "DeleteAccount"),
		log.Duration("duration", duration),
	)
	return nil
}

// AdjustAccountBalance executes next.AdjustAccountBalance and logs execution duration and errors.
func (l *LoggingCoordinator) AdjustAccountBalance(ctx context.Context, id finance.AccountID, targetBalance int64, adjustmentDate string, note string) (*finance.Account, error) {
	start := time.Now()
	res, err := l.next.AdjustAccountBalance(ctx, id, targetBalance, adjustmentDate, note)
	duration := time.Since(start)

	if err != nil {
		l.logger.Error(ctx, "finance.AdjustAccountBalance failed",
			log.String("component", "finance"),
			log.String("operation", "AdjustAccountBalance"),
			log.Duration("duration", duration),
			log.Err(err),
		)
		return nil, err
	}

	l.logger.Info(ctx, "finance.AdjustAccountBalance completed",
		log.String("component", "finance"),
		log.String("operation", "AdjustAccountBalance"),
		log.Duration("duration", duration),
	)
	return res, nil
}

// CreateBorrowing executes next.CreateBorrowing and logs execution duration and errors.
func (l *LoggingCoordinator) CreateBorrowing(ctx context.Context, req *CreateBorrowingRequest) (*finance.Borrowing, error) {
	start := time.Now()
	res, err := l.next.CreateBorrowing(ctx, req)
	duration := time.Since(start)

	if err != nil {
		l.logger.Error(ctx, "finance.CreateBorrowing failed",
			log.String("component", "finance"),
			log.String("operation", "CreateBorrowing"),
			log.Duration("duration", duration),
			log.Err(err),
		)
		return nil, err
	}

	l.logger.Info(ctx, "finance.CreateBorrowing completed",
		log.String("component", "finance"),
		log.String("operation", "CreateBorrowing"),
		log.Duration("duration", duration),
	)
	return res, nil
}

// UpdateBorrowing executes next.UpdateBorrowing and logs execution duration and errors.
func (l *LoggingCoordinator) UpdateBorrowing(ctx context.Context, req *UpdateBorrowingRequest) (*finance.Borrowing, error) {
	start := time.Now()
	res, err := l.next.UpdateBorrowing(ctx, req)
	duration := time.Since(start)

	if err != nil {
		l.logger.Error(ctx, "finance.UpdateBorrowing failed",
			log.String("component", "finance"),
			log.String("operation", "UpdateBorrowing"),
			log.Duration("duration", duration),
			log.Err(err),
		)
		return nil, err
	}

	l.logger.Info(ctx, "finance.UpdateBorrowing completed",
		log.String("component", "finance"),
		log.String("operation", "UpdateBorrowing"),
		log.Duration("duration", duration),
	)
	return res, nil
}

// DeleteBorrowing executes next.DeleteBorrowing and logs execution duration and errors.
func (l *LoggingCoordinator) DeleteBorrowing(ctx context.Context, id finance.BorrowingID) error {
	start := time.Now()
	err := l.next.DeleteBorrowing(ctx, id)
	duration := time.Since(start)

	if err != nil {
		l.logger.Error(ctx, "finance.DeleteBorrowing failed",
			log.String("component", "finance"),
			log.String("operation", "DeleteBorrowing"),
			log.Duration("duration", duration),
			log.Err(err),
		)
		return err
	}

	l.logger.Info(ctx, "finance.DeleteBorrowing completed",
		log.String("component", "finance"),
		log.String("operation", "DeleteBorrowing"),
		log.Duration("duration", duration),
	)
	return nil
}

// AdjustBorrowingBalance executes next.AdjustBorrowingBalance and logs execution duration and errors.
func (l *LoggingCoordinator) AdjustBorrowingBalance(ctx context.Context, req *AdjustBorrowingBalanceRequest) (*finance.Borrowing, error) {
	start := time.Now()
	res, err := l.next.AdjustBorrowingBalance(ctx, req)
	duration := time.Since(start)

	if err != nil {
		l.logger.Error(ctx, "finance.AdjustBorrowingBalance failed",
			log.String("component", "finance"),
			log.String("operation", "AdjustBorrowingBalance"),
			log.Duration("duration", duration),
			log.Err(err),
		)
		return nil, err
	}

	l.logger.Info(ctx, "finance.AdjustBorrowingBalance completed",
		log.String("component", "finance"),
		log.String("operation", "AdjustBorrowingBalance"),
		log.Duration("duration", duration),
	)
	return res, nil
}

// LogBorrowingTransaction executes next.LogBorrowingTransaction and logs execution duration and errors.
func (l *LoggingCoordinator) LogBorrowingTransaction(ctx context.Context, req *LogBorrowingTransactionRequest) (*finance.Transaction, error) {
	start := time.Now()
	res, err := l.next.LogBorrowingTransaction(ctx, req)
	duration := time.Since(start)

	if err != nil {
		l.logger.Error(ctx, "finance.LogBorrowingTransaction failed",
			log.String("component", "finance"),
			log.String("operation", "LogBorrowingTransaction"),
			log.Duration("duration", duration),
			log.Err(err),
		)
		return nil, err
	}

	l.logger.Info(ctx, "finance.LogBorrowingTransaction completed",
		log.String("component", "finance"),
		log.String("operation", "LogBorrowingTransaction"),
		log.Duration("duration", duration),
	)
	return res, nil
}

// UpdateBorrowingTransaction executes next.UpdateBorrowingTransaction and logs execution duration and errors.
func (l *LoggingCoordinator) UpdateBorrowingTransaction(ctx context.Context, req *UpdateBorrowingTransactionRequest) (*finance.Transaction, error) {
	start := time.Now()
	res, err := l.next.UpdateBorrowingTransaction(ctx, req)
	duration := time.Since(start)

	if err != nil {
		l.logger.Error(ctx, "finance.UpdateBorrowingTransaction failed",
			log.String("component", "finance"),
			log.String("operation", "UpdateBorrowingTransaction"),
			log.Duration("duration", duration),
			log.Err(err),
		)
		return nil, err
	}

	l.logger.Info(ctx, "finance.UpdateBorrowingTransaction completed",
		log.String("component", "finance"),
		log.String("operation", "UpdateBorrowingTransaction"),
		log.Duration("duration", duration),
	)
	return res, nil
}

// DeleteBorrowingTransaction executes next.DeleteBorrowingTransaction and logs execution duration and errors.
func (l *LoggingCoordinator) DeleteBorrowingTransaction(ctx context.Context, req *DeleteBorrowingTransactionRequest) error {
	start := time.Now()
	err := l.next.DeleteBorrowingTransaction(ctx, req)
	duration := time.Since(start)

	if err != nil {
		l.logger.Error(ctx, "finance.DeleteBorrowingTransaction failed",
			log.String("component", "finance"),
			log.String("operation", "DeleteBorrowingTransaction"),
			log.Duration("duration", duration),
			log.Err(err),
		)
		return err
	}

	l.logger.Info(ctx, "finance.DeleteBorrowingTransaction completed",
		log.String("component", "finance"),
		log.String("operation", "DeleteBorrowingTransaction"),
		log.Duration("duration", duration),
	)
	return nil
}

// CreateBudget executes next.CreateBudget and logs execution duration and errors.
func (l *LoggingCoordinator) CreateBudget(ctx context.Context, req *CreateBudgetRequest) (*finance.Budget, error) {
	start := time.Now()
	res, err := l.next.CreateBudget(ctx, req)
	duration := time.Since(start)

	if err != nil {
		l.logger.Error(ctx, "finance.CreateBudget failed",
			log.String("component", "finance"),
			log.String("operation", "CreateBudget"),
			log.Duration("duration", duration),
			log.Err(err),
		)
		return nil, err
	}

	l.logger.Info(ctx, "finance.CreateBudget completed",
		log.String("component", "finance"),
		log.String("operation", "CreateBudget"),
		log.Duration("duration", duration),
	)
	return res, nil
}

// UpdateBudget executes next.UpdateBudget and logs execution duration and errors.
func (l *LoggingCoordinator) UpdateBudget(ctx context.Context, req *UpdateBudgetRequest) (*finance.Budget, error) {
	start := time.Now()
	res, err := l.next.UpdateBudget(ctx, req)
	duration := time.Since(start)

	if err != nil {
		l.logger.Error(ctx, "finance.UpdateBudget failed",
			log.String("component", "finance"),
			log.String("operation", "UpdateBudget"),
			log.Duration("duration", duration),
			log.Err(err),
		)
		return nil, err
	}

	l.logger.Info(ctx, "finance.UpdateBudget completed",
		log.String("component", "finance"),
		log.String("operation", "UpdateBudget"),
		log.Duration("duration", duration),
	)
	return res, nil
}

// GetBudget executes next.GetBudget and logs execution duration and errors.
func (l *LoggingCoordinator) GetBudget(ctx context.Context, id finance.BudgetID) (*finance.Budget, error) {
	start := time.Now()
	res, err := l.next.GetBudget(ctx, id)
	duration := time.Since(start)

	if err != nil {
		l.logger.Error(ctx, "finance.GetBudget failed",
			log.String("component", "finance"),
			log.String("operation", "GetBudget"),
			log.Duration("duration", duration),
			log.Err(err),
		)
		return nil, err
	}

	l.logger.Info(ctx, "finance.GetBudget completed",
		log.String("component", "finance"),
		log.String("operation", "GetBudget"),
		log.Duration("duration", duration),
	)
	return res, nil
}

// DeleteBudget executes next.DeleteBudget and logs execution duration and errors.
func (l *LoggingCoordinator) DeleteBudget(ctx context.Context, req *DeleteBudgetRequest) error {
	start := time.Now()
	err := l.next.DeleteBudget(ctx, req)
	duration := time.Since(start)

	if err != nil {
		l.logger.Error(ctx, "finance.DeleteBudget failed",
			log.String("component", "finance"),
			log.String("operation", "DeleteBudget"),
			log.Duration("duration", duration),
			log.Err(err),
		)
		return err
	}

	l.logger.Info(ctx, "finance.DeleteBudget completed",
		log.String("component", "finance"),
		log.String("operation", "DeleteBudget"),
		log.Duration("duration", duration),
	)
	return nil
}

// GetInsights executes next.GetInsights and logs execution duration and errors.
func (l *LoggingCoordinator) GetInsights(ctx context.Context, req *GetInsightsRequest) (*finance.Insights, error) {
	start := time.Now()
	res, err := l.next.GetInsights(ctx, req)
	duration := time.Since(start)

	if err != nil {
		l.logger.Error(ctx, "finance.GetInsights failed",
			log.String("component", "finance"),
			log.String("operation", "GetInsights"),
			log.Duration("duration", duration),
			log.Err(err),
		)
		return nil, err
	}

	l.logger.Info(ctx, "finance.GetInsights completed",
		log.String("component", "finance"),
		log.String("operation", "GetInsights"),
		log.Duration("duration", duration),
	)
	return res, nil
}

// CreateInstitution executes next.CreateInstitution and logs execution duration and errors.
func (l *LoggingCoordinator) CreateInstitution(ctx context.Context, inst *finance.Institution) (*finance.Institution, error) {
	start := time.Now()
	res, err := l.next.CreateInstitution(ctx, inst)
	duration := time.Since(start)

	if err != nil {
		l.logger.Error(ctx, "finance.CreateInstitution failed",
			log.String("component", "finance"),
			log.String("operation", "CreateInstitution"),
			log.Duration("duration", duration),
			log.Err(err),
		)
		return nil, err
	}

	l.logger.Info(ctx, "finance.CreateInstitution completed",
		log.String("component", "finance"),
		log.String("operation", "CreateInstitution"),
		log.Duration("duration", duration),
	)
	return res, nil
}

// UpdateInstitution executes next.UpdateInstitution and logs execution duration and errors.
func (l *LoggingCoordinator) UpdateInstitution(ctx context.Context, inst *finance.Institution, mask []string) (*finance.Institution, error) {
	start := time.Now()
	res, err := l.next.UpdateInstitution(ctx, inst, mask)
	duration := time.Since(start)

	if err != nil {
		l.logger.Error(ctx, "finance.UpdateInstitution failed",
			log.String("component", "finance"),
			log.String("operation", "UpdateInstitution"),
			log.Duration("duration", duration),
			log.Err(err),
		)
		return nil, err
	}

	l.logger.Info(ctx, "finance.UpdateInstitution completed",
		log.String("component", "finance"),
		log.String("operation", "UpdateInstitution"),
		log.Duration("duration", duration),
	)
	return res, nil
}

// DeleteInstitution executes next.DeleteInstitution and logs execution duration and errors.
func (l *LoggingCoordinator) DeleteInstitution(ctx context.Context, id finance.InstitutionID, opts finance.DeleteOptions) error {
	start := time.Now()
	err := l.next.DeleteInstitution(ctx, id, opts)
	duration := time.Since(start)

	if err != nil {
		l.logger.Error(ctx, "finance.DeleteInstitution failed",
			log.String("component", "finance"),
			log.String("operation", "DeleteInstitution"),
			log.Duration("duration", duration),
			log.Err(err),
		)
		return err
	}

	l.logger.Info(ctx, "finance.DeleteInstitution completed",
		log.String("component", "finance"),
		log.String("operation", "DeleteInstitution"),
		log.Duration("duration", duration),
	)
	return nil
}

// ResolveInstitution executes next.ResolveInstitution and logs execution duration and errors.
func (l *LoggingCoordinator) ResolveInstitution(ctx context.Context, name string) (*finance.ResolveInstitutionResult, error) {
	start := time.Now()
	res, err := l.next.ResolveInstitution(ctx, name)
	duration := time.Since(start)

	if err != nil {
		l.logger.Error(ctx, "finance.ResolveInstitution failed",
			log.String("component", "finance"),
			log.String("operation", "ResolveInstitution"),
			log.Duration("duration", duration),
			log.Err(err),
		)
		return nil, err
	}

	l.logger.Info(ctx, "finance.ResolveInstitution completed",
		log.String("component", "finance"),
		log.String("operation", "ResolveInstitution"),
		log.Duration("duration", duration),
	)
	return res, nil
}

// CreateExchangeRate executes next.CreateExchangeRate and logs execution duration and errors.
func (l *LoggingCoordinator) CreateExchangeRate(ctx context.Context, req *CreateExchangeRateRequest) (*finance.ExchangeRate, error) {
	start := time.Now()
	res, err := l.next.CreateExchangeRate(ctx, req)
	duration := time.Since(start)

	if err != nil {
		l.logger.Error(ctx, "finance.CreateExchangeRate failed",
			log.String("component", "finance"),
			log.String("operation", "CreateExchangeRate"),
			log.Duration("duration", duration),
			log.Err(err),
		)
		return nil, err
	}

	l.logger.Info(ctx, "finance.CreateExchangeRate completed",
		log.String("component", "finance"),
		log.String("operation", "CreateExchangeRate"),
		log.Duration("duration", duration),
	)
	return res, nil
}

// GetExchangeRate executes next.GetExchangeRate and logs execution duration and errors.
func (l *LoggingCoordinator) GetExchangeRate(ctx context.Context, req *GetExchangeRateRequest) (*finance.ExchangeRate, error) {
	start := time.Now()
	res, err := l.next.GetExchangeRate(ctx, req)
	duration := time.Since(start)

	if err != nil {
		l.logger.Error(ctx, "finance.GetExchangeRate failed",
			log.String("component", "finance"),
			log.String("operation", "GetExchangeRate"),
			log.Duration("duration", duration),
			log.Err(err),
		)
		return nil, err
	}

	l.logger.Info(ctx, "finance.GetExchangeRate completed",
		log.String("component", "finance"),
		log.String("operation", "GetExchangeRate"),
		log.Duration("duration", duration),
	)
	return res, nil
}

// UpdateExchangeRate executes next.UpdateExchangeRate and logs execution duration and errors.
func (l *LoggingCoordinator) UpdateExchangeRate(ctx context.Context, req *UpdateExchangeRateRequest) (*finance.ExchangeRate, error) {
	start := time.Now()
	res, err := l.next.UpdateExchangeRate(ctx, req)
	duration := time.Since(start)

	if err != nil {
		l.logger.Error(ctx, "finance.UpdateExchangeRate failed",
			log.String("component", "finance"),
			log.String("operation", "UpdateExchangeRate"),
			log.Duration("duration", duration),
			log.Err(err),
		)
		return nil, err
	}

	l.logger.Info(ctx, "finance.UpdateExchangeRate completed",
		log.String("component", "finance"),
		log.String("operation", "UpdateExchangeRate"),
		log.Duration("duration", duration),
	)
	return res, nil
}

// ListExchangeRates executes next.ListExchangeRates and logs execution duration and errors.
func (l *LoggingCoordinator) ListExchangeRates(ctx context.Context, req *ListExchangeRatesRequest) ([]*finance.ExchangeRate, string, error) {
	start := time.Now()
	res1, res2, err := l.next.ListExchangeRates(ctx, req)
	duration := time.Since(start)

	if err != nil {
		l.logger.Error(ctx, "finance.ListExchangeRates failed",
			log.String("component", "finance"),
			log.String("operation", "ListExchangeRates"),
			log.Duration("duration", duration),
			log.Err(err),
		)
		return nil, "", err
	}

	l.logger.Info(ctx, "finance.ListExchangeRates completed",
		log.String("component", "finance"),
		log.String("operation", "ListExchangeRates"),
		log.Duration("duration", duration),
	)
	return res1, res2, nil
}

// DeleteExchangeRate executes next.DeleteExchangeRate and logs execution duration and errors.
func (l *LoggingCoordinator) DeleteExchangeRate(ctx context.Context, req *DeleteExchangeRateRequest) error {
	start := time.Now()
	err := l.next.DeleteExchangeRate(ctx, req)
	duration := time.Since(start)

	if err != nil {
		l.logger.Error(ctx, "finance.DeleteExchangeRate failed",
			log.String("component", "finance"),
			log.String("operation", "DeleteExchangeRate"),
			log.Duration("duration", duration),
			log.Err(err),
		)
		return err
	}

	l.logger.Info(ctx, "finance.DeleteExchangeRate completed",
		log.String("component", "finance"),
		log.String("operation", "DeleteExchangeRate"),
		log.Duration("duration", duration),
	)
	return nil
}

// CreateRecurringTransaction executes next.CreateRecurringTransaction and logs execution duration and errors.
func (l *LoggingCoordinator) CreateRecurringTransaction(ctx context.Context, req *CreateRecurringTransactionRequest) (*finance.RecurringTransaction, error) {
	start := time.Now()
	res, err := l.next.CreateRecurringTransaction(ctx, req)
	duration := time.Since(start)

	if err != nil {
		l.logger.Error(ctx, "finance.CreateRecurringTransaction failed",
			log.String("component", "finance"),
			log.String("operation", "CreateRecurringTransaction"),
			log.Duration("duration", duration),
			log.Err(err),
		)
		return nil, err
	}

	l.logger.Info(ctx, "finance.CreateRecurringTransaction completed",
		log.String("component", "finance"),
		log.String("operation", "CreateRecurringTransaction"),
		log.Duration("duration", duration),
	)
	return res, nil
}

// UpdateRecurringTransaction executes next.UpdateRecurringTransaction and logs execution duration and errors.
func (l *LoggingCoordinator) UpdateRecurringTransaction(ctx context.Context, req *UpdateRecurringTransactionRequest) (*finance.RecurringTransaction, error) {
	start := time.Now()
	res, err := l.next.UpdateRecurringTransaction(ctx, req)
	duration := time.Since(start)

	if err != nil {
		l.logger.Error(ctx, "finance.UpdateRecurringTransaction failed",
			log.String("component", "finance"),
			log.String("operation", "UpdateRecurringTransaction"),
			log.Duration("duration", duration),
			log.Err(err),
		)
		return nil, err
	}

	l.logger.Info(ctx, "finance.UpdateRecurringTransaction completed",
		log.String("component", "finance"),
		log.String("operation", "UpdateRecurringTransaction"),
		log.Duration("duration", duration),
	)
	return res, nil
}

// DeleteRecurringTransaction executes next.DeleteRecurringTransaction and logs execution duration and errors.
func (l *LoggingCoordinator) DeleteRecurringTransaction(ctx context.Context, id finance.RecurringTransactionID, opts finance.DeleteOptions) error {
	start := time.Now()
	err := l.next.DeleteRecurringTransaction(ctx, id, opts)
	duration := time.Since(start)

	if err != nil {
		l.logger.Error(ctx, "finance.DeleteRecurringTransaction failed",
			log.String("component", "finance"),
			log.String("operation", "DeleteRecurringTransaction"),
			log.Duration("duration", duration),
			log.Err(err),
		)
		return err
	}

	l.logger.Info(ctx, "finance.DeleteRecurringTransaction completed",
		log.String("component", "finance"),
		log.String("operation", "DeleteRecurringTransaction"),
		log.Duration("duration", duration),
	)
	return nil
}

// ConfirmScheduledTransaction executes next.ConfirmScheduledTransaction and logs execution duration and errors.
func (l *LoggingCoordinator) ConfirmScheduledTransaction(ctx context.Context, req *ConfirmScheduledTransactionRequest) (*finance.Transaction, error) {
	start := time.Now()
	res, err := l.next.ConfirmScheduledTransaction(ctx, req)
	duration := time.Since(start)

	if err != nil {
		l.logger.Error(ctx, "finance.ConfirmScheduledTransaction failed",
			log.String("component", "finance"),
			log.String("operation", "ConfirmScheduledTransaction"),
			log.Duration("duration", duration),
			log.Err(err),
		)
		return nil, err
	}

	l.logger.Info(ctx, "finance.ConfirmScheduledTransaction completed",
		log.String("component", "finance"),
		log.String("operation", "ConfirmScheduledTransaction"),
		log.Duration("duration", duration),
	)
	return res, nil
}

// MatchScheduledTransaction executes next.MatchScheduledTransaction and logs execution duration and errors.
func (l *LoggingCoordinator) MatchScheduledTransaction(ctx context.Context, req *MatchScheduledTransactionRequest) (*finance.Transaction, error) {
	start := time.Now()
	res, err := l.next.MatchScheduledTransaction(ctx, req)
	duration := time.Since(start)

	if err != nil {
		l.logger.Error(ctx, "finance.MatchScheduledTransaction failed",
			log.String("component", "finance"),
			log.String("operation", "MatchScheduledTransaction"),
			log.Duration("duration", duration),
			log.Err(err),
		)
		return nil, err
	}

	l.logger.Info(ctx, "finance.MatchScheduledTransaction completed",
		log.String("component", "finance"),
		log.String("operation", "MatchScheduledTransaction"),
		log.Duration("duration", duration),
	)
	return res, nil
}

// SkipScheduledTransaction executes next.SkipScheduledTransaction and logs execution duration and errors.
func (l *LoggingCoordinator) SkipScheduledTransaction(ctx context.Context, id finance.ScheduledTransactionID) (*finance.ScheduledTransaction, error) {
	start := time.Now()
	res, err := l.next.SkipScheduledTransaction(ctx, id)
	duration := time.Since(start)

	if err != nil {
		l.logger.Error(ctx, "finance.SkipScheduledTransaction failed",
			log.String("component", "finance"),
			log.String("operation", "SkipScheduledTransaction"),
			log.Duration("duration", duration),
			log.Err(err),
		)
		return nil, err
	}

	l.logger.Info(ctx, "finance.SkipScheduledTransaction completed",
		log.String("component", "finance"),
		log.String("operation", "SkipScheduledTransaction"),
		log.Duration("duration", duration),
	)
	return res, nil
}

// GetScheduledTransaction executes next.GetScheduledTransaction and logs execution duration and errors.
func (l *LoggingCoordinator) GetScheduledTransaction(ctx context.Context, id finance.ScheduledTransactionID) (*finance.ScheduledTransaction, error) {
	start := time.Now()
	res, err := l.next.GetScheduledTransaction(ctx, id)
	duration := time.Since(start)

	if err != nil {
		l.logger.Error(ctx, "finance.GetScheduledTransaction failed",
			log.String("component", "finance"),
			log.String("operation", "GetScheduledTransaction"),
			log.Duration("duration", duration),
			log.Err(err),
		)
		return nil, err
	}

	l.logger.Info(ctx, "finance.GetScheduledTransaction completed",
		log.String("component", "finance"),
		log.String("operation", "GetScheduledTransaction"),
		log.Duration("duration", duration),
	)
	return res, nil
}

// GenerateScheduledTransactions executes next.GenerateScheduledTransactions and logs execution duration and errors.
func (l *LoggingCoordinator) GenerateScheduledTransactions(ctx context.Context) error {
	start := time.Now()
	err := l.next.GenerateScheduledTransactions(ctx)
	duration := time.Since(start)

	if err != nil {
		l.logger.Error(ctx, "finance.GenerateScheduledTransactions failed",
			log.String("component", "finance"),
			log.String("operation", "GenerateScheduledTransactions"),
			log.Duration("duration", duration),
			log.Err(err),
		)
		return err
	}

	l.logger.Info(ctx, "finance.GenerateScheduledTransactions completed",
		log.String("component", "finance"),
		log.String("operation", "GenerateScheduledTransactions"),
		log.Duration("duration", duration),
	)
	return nil
}

// CreateExpense executes next.CreateExpense and logs execution duration and errors.
func (l *LoggingCoordinator) CreateExpense(ctx context.Context, req *CreateExpenseRequest) (*finance.Transaction, error) {
	start := time.Now()
	res, err := l.next.CreateExpense(ctx, req)
	duration := time.Since(start)

	if err != nil {
		l.logger.Error(ctx, "finance.CreateExpense failed",
			log.String("component", "finance"),
			log.String("operation", "CreateExpense"),
			log.Duration("duration", duration),
			log.Err(err),
		)
		return nil, err
	}

	l.logger.Info(ctx, "finance.CreateExpense completed",
		log.String("component", "finance"),
		log.String("operation", "CreateExpense"),
		log.Duration("duration", duration),
	)
	return res, nil
}

// CreateIncome executes next.CreateIncome and logs execution duration and errors.
func (l *LoggingCoordinator) CreateIncome(ctx context.Context, req *CreateIncomeRequest) (*finance.Transaction, error) {
	start := time.Now()
	res, err := l.next.CreateIncome(ctx, req)
	duration := time.Since(start)

	if err != nil {
		l.logger.Error(ctx, "finance.CreateIncome failed",
			log.String("component", "finance"),
			log.String("operation", "CreateIncome"),
			log.Duration("duration", duration),
			log.Err(err),
		)
		return nil, err
	}

	l.logger.Info(ctx, "finance.CreateIncome completed",
		log.String("component", "finance"),
		log.String("operation", "CreateIncome"),
		log.Duration("duration", duration),
	)
	return res, nil
}

// UpdateExpense executes next.UpdateExpense and logs execution duration and errors.
func (l *LoggingCoordinator) UpdateExpense(ctx context.Context, req *UpdateExpenseRequest) (*finance.Transaction, error) {
	start := time.Now()
	res, err := l.next.UpdateExpense(ctx, req)
	duration := time.Since(start)

	if err != nil {
		l.logger.Error(ctx, "finance.UpdateExpense failed",
			log.String("component", "finance"),
			log.String("operation", "UpdateExpense"),
			log.Duration("duration", duration),
			log.Err(err),
		)
		return nil, err
	}

	l.logger.Info(ctx, "finance.UpdateExpense completed",
		log.String("component", "finance"),
		log.String("operation", "UpdateExpense"),
		log.Duration("duration", duration),
	)
	return res, nil
}

// UpdateIncome executes next.UpdateIncome and logs execution duration and errors.
func (l *LoggingCoordinator) UpdateIncome(ctx context.Context, req *UpdateIncomeRequest) (*finance.Transaction, error) {
	start := time.Now()
	res, err := l.next.UpdateIncome(ctx, req)
	duration := time.Since(start)

	if err != nil {
		l.logger.Error(ctx, "finance.UpdateIncome failed",
			log.String("component", "finance"),
			log.String("operation", "UpdateIncome"),
			log.Duration("duration", duration),
			log.Err(err),
		)
		return nil, err
	}

	l.logger.Info(ctx, "finance.UpdateIncome completed",
		log.String("component", "finance"),
		log.String("operation", "UpdateIncome"),
		log.Duration("duration", duration),
	)
	return res, nil
}

// DeleteTransaction executes next.DeleteTransaction and logs execution duration and errors.
func (l *LoggingCoordinator) DeleteTransaction(ctx context.Context, id finance.TransactionID) error {
	start := time.Now()
	err := l.next.DeleteTransaction(ctx, id)
	duration := time.Since(start)

	if err != nil {
		l.logger.Error(ctx, "finance.DeleteTransaction failed",
			log.String("component", "finance"),
			log.String("operation", "DeleteTransaction"),
			log.Duration("duration", duration),
			log.Err(err),
		)
		return err
	}

	l.logger.Info(ctx, "finance.DeleteTransaction completed",
		log.String("component", "finance"),
		log.String("operation", "DeleteTransaction"),
		log.Duration("duration", duration),
	)
	return nil
}

// ListTransactionEvents executes next.ListTransactionEvents and logs execution duration and errors.
func (l *LoggingCoordinator) ListTransactionEvents(ctx context.Context, req *ListTransactionEventsRequest) ([]*finance.TransactionEvent, error) {
	start := time.Now()
	res, err := l.next.ListTransactionEvents(ctx, req)
	duration := time.Since(start)

	if err != nil {
		l.logger.Error(ctx, "finance.ListTransactionEvents failed",
			log.String("component", "finance"),
			log.String("operation", "ListTransactionEvents"),
			log.Duration("duration", duration),
			log.Err(err),
		)
		return nil, err
	}

	l.logger.Info(ctx, "finance.ListTransactionEvents completed",
		log.String("component", "finance"),
		log.String("operation", "ListTransactionEvents"),
		log.Duration("duration", duration),
	)
	return res, nil
}

// CreateTransfer executes next.CreateTransfer and logs execution duration and errors.
func (l *LoggingCoordinator) CreateTransfer(ctx context.Context, req *CreateTransferRequest) (*finance.Transfer, error) {
	start := time.Now()
	res, err := l.next.CreateTransfer(ctx, req)
	duration := time.Since(start)

	if err != nil {
		l.logger.Error(ctx, "finance.CreateTransfer failed",
			log.String("component", "finance"),
			log.String("operation", "CreateTransfer"),
			log.Duration("duration", duration),
			log.Err(err),
		)
		return nil, err
	}

	l.logger.Info(ctx, "finance.CreateTransfer completed",
		log.String("component", "finance"),
		log.String("operation", "CreateTransfer"),
		log.Duration("duration", duration),
	)
	return res, nil
}

// GetTransfer executes next.GetTransfer and logs execution duration and errors.
func (l *LoggingCoordinator) GetTransfer(ctx context.Context, id finance.TransferID) (*finance.Transfer, error) {
	start := time.Now()
	res, err := l.next.GetTransfer(ctx, id)
	duration := time.Since(start)

	if err != nil {
		l.logger.Error(ctx, "finance.GetTransfer failed",
			log.String("component", "finance"),
			log.String("operation", "GetTransfer"),
			log.Duration("duration", duration),
			log.Err(err),
		)
		return nil, err
	}

	l.logger.Info(ctx, "finance.GetTransfer completed",
		log.String("component", "finance"),
		log.String("operation", "GetTransfer"),
		log.Duration("duration", duration),
	)
	return res, nil
}

// DeleteTransfer executes next.DeleteTransfer and logs execution duration and errors.
func (l *LoggingCoordinator) DeleteTransfer(ctx context.Context, id finance.TransferID) error {
	start := time.Now()
	err := l.next.DeleteTransfer(ctx, id)
	duration := time.Since(start)

	if err != nil {
		l.logger.Error(ctx, "finance.DeleteTransfer failed",
			log.String("component", "finance"),
			log.String("operation", "DeleteTransfer"),
			log.Duration("duration", duration),
			log.Err(err),
		)
		return err
	}

	l.logger.Info(ctx, "finance.DeleteTransfer completed",
		log.String("component", "finance"),
		log.String("operation", "DeleteTransfer"),
		log.Duration("duration", duration),
	)
	return nil
}

// ListTransfers executes next.ListTransfers and logs execution duration and errors.
func (l *LoggingCoordinator) ListTransfers(ctx context.Context, req *ListTransfersRequest) ([]*finance.Transfer, string, error) {
	start := time.Now()
	res1, res2, err := l.next.ListTransfers(ctx, req)
	duration := time.Since(start)

	if err != nil {
		l.logger.Error(ctx, "finance.ListTransfers failed",
			log.String("component", "finance"),
			log.String("operation", "ListTransfers"),
			log.Duration("duration", duration),
			log.Err(err),
		)
		return nil, "", err
	}

	l.logger.Info(ctx, "finance.ListTransfers completed",
		log.String("component", "finance"),
		log.String("operation", "ListTransfers"),
		log.Duration("duration", duration),
	)
	return res1, res2, nil
}

// IngestEmail executes next.IngestEmail and logs execution duration and errors.
func (l *LoggingCoordinator) IngestEmail(ctx context.Context, spaceID string, integrationID string, sender string, subject string, body string) (*finance.InboxItem, error) {
	start := time.Now()
	res, err := l.next.IngestEmail(ctx, spaceID, integrationID, sender, subject, body)
	duration := time.Since(start)

	if err != nil {
		l.logger.Error(ctx, "finance.IngestEmail failed",
			log.String("component", "finance"),
			log.String("operation", "IngestEmail"),
			log.Duration("duration", duration),
			log.Err(err),
		)
		return nil, err
	}

	l.logger.Info(ctx, "finance.IngestEmail completed",
		log.String("component", "finance"),
		log.String("operation", "IngestEmail"),
		log.Duration("duration", duration),
	)
	return res, nil
}

// DiscardInboxItem executes next.DiscardInboxItem and logs execution duration and errors.
func (l *LoggingCoordinator) DiscardInboxItem(ctx context.Context, id string) error {
	start := time.Now()
	err := l.next.DiscardInboxItem(ctx, id)
	duration := time.Since(start)

	if err != nil {
		l.logger.Error(ctx, "finance.DiscardInboxItem failed",
			log.String("component", "finance"),
			log.String("operation", "DiscardInboxItem"),
			log.Duration("duration", duration),
			log.Err(err),
		)
		return err
	}

	l.logger.Info(ctx, "finance.DiscardInboxItem completed",
		log.String("component", "finance"),
		log.String("operation", "DiscardInboxItem"),
		log.Duration("duration", duration),
	)
	return nil
}

// GetTransactionSuggestions executes next.GetTransactionSuggestions and logs execution duration and errors.
func (l *LoggingCoordinator) GetTransactionSuggestions(ctx context.Context, req *IngestionRequest) (*SignalSuggestion, error) {
	start := time.Now()
	res, err := l.next.GetTransactionSuggestions(ctx, req)
	duration := time.Since(start)

	if err != nil {
		l.logger.Error(ctx, "finance.GetTransactionSuggestions failed",
			log.String("component", "finance"),
			log.String("operation", "GetTransactionSuggestions"),
			log.Duration("duration", duration),
			log.Err(err),
		)
		return nil, err
	}

	l.logger.Info(ctx, "finance.GetTransactionSuggestions completed",
		log.String("component", "finance"),
		log.String("operation", "GetTransactionSuggestions"),
		log.Duration("duration", duration),
	)
	return res, nil
}

// ProcessSuggestions executes next.ProcessSuggestions and logs execution duration and errors.
func (l *LoggingCoordinator) ProcessSuggestions(ctx context.Context, spaceID string, req *agentapp.SuggestionRequest) (map[string]any, error) {
	start := time.Now()
	res, err := l.next.ProcessSuggestions(ctx, spaceID, req)
	duration := time.Since(start)

	if err != nil {
		l.logger.Error(ctx, "finance.ProcessSuggestions failed",
			log.String("component", "finance"),
			log.String("operation", "ProcessSuggestions"),
			log.Duration("duration", duration),
			log.Err(err),
		)
		return nil, err
	}

	l.logger.Info(ctx, "finance.ProcessSuggestions completed",
		log.String("component", "finance"),
		log.String("operation", "ProcessSuggestions"),
		log.Duration("duration", duration),
	)
	return res, nil
}

// UpdateInboxItem executes next.UpdateInboxItem and logs execution duration and errors.
func (l *LoggingCoordinator) UpdateInboxItem(ctx context.Context, item *finance.InboxItem) (*finance.InboxItem, error) {
	start := time.Now()
	res, err := l.next.UpdateInboxItem(ctx, item)
	duration := time.Since(start)

	if err != nil {
		l.logger.Error(ctx, "finance.UpdateInboxItem failed",
			log.String("component", "finance"),
			log.String("operation", "UpdateInboxItem"),
			log.Duration("duration", duration),
			log.Err(err),
		)
		return nil, err
	}

	l.logger.Info(ctx, "finance.UpdateInboxItem completed",
		log.String("component", "finance"),
		log.String("operation", "UpdateInboxItem"),
		log.Duration("duration", duration),
	)
	return res, nil
}

// ApproveInboxItem executes next.ApproveInboxItem and logs execution duration and errors.
func (l *LoggingCoordinator) ApproveInboxItem(ctx context.Context, id string) (*finance.InboxItem, error) {
	start := time.Now()
	res, err := l.next.ApproveInboxItem(ctx, id)
	duration := time.Since(start)

	if err != nil {
		l.logger.Error(ctx, "finance.ApproveInboxItem failed",
			log.String("component", "finance"),
			log.String("operation", "ApproveInboxItem"),
			log.Duration("duration", duration),
			log.Err(err),
		)
		return nil, err
	}

	l.logger.Info(ctx, "finance.ApproveInboxItem completed",
		log.String("component", "finance"),
		log.String("operation", "ApproveInboxItem"),
		log.Duration("duration", duration),
	)
	return res, nil
}

// ProcessSignalPipeline executes next.ProcessSignalPipeline and logs execution duration and errors.
func (l *LoggingCoordinator) ProcessSignalPipeline(ctx context.Context, spaceID string, req *IngestionRequest) (*IngestionState, error) {
	start := time.Now()
	res, err := l.next.ProcessSignalPipeline(ctx, spaceID, req)
	duration := time.Since(start)

	if err != nil {
		l.logger.Error(ctx, "finance.ProcessSignalPipeline failed",
			log.String("component", "finance"),
			log.String("operation", "ProcessSignalPipeline"),
			log.Duration("duration", duration),
			log.Err(err),
		)
		return nil, err
	}

	l.logger.Info(ctx, "finance.ProcessSignalPipeline completed",
		log.String("component", "finance"),
		log.String("operation", "ProcessSignalPipeline"),
		log.Duration("duration", duration),
	)
	return res, nil
}

// GetSignalSuggestions executes next.GetSignalSuggestions and logs execution duration and errors.
func (l *LoggingCoordinator) GetSignalSuggestions(ctx context.Context, spaceID string, req *IngestionRequest) (*SignalSuggestion, error) {
	start := time.Now()
	res, err := l.next.GetSignalSuggestions(ctx, spaceID, req)
	duration := time.Since(start)

	if err != nil {
		l.logger.Error(ctx, "finance.GetSignalSuggestions failed",
			log.String("component", "finance"),
			log.String("operation", "GetSignalSuggestions"),
			log.Duration("duration", duration),
			log.Err(err),
		)
		return nil, err
	}

	l.logger.Info(ctx, "finance.GetSignalSuggestions completed",
		log.String("component", "finance"),
		log.String("operation", "GetSignalSuggestions"),
		log.Duration("duration", duration),
	)
	return res, nil
}
