// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

// Budget A budget to track expenses
type Budget struct {
	// Amount The amount of the budget in cents (e.g. $10.00 is 1000)
	Amount int     `json:"amount"`
	Id     *string `json:"id,omitempty"`
	Name   string  `json:"name"`
}

// ListBudgetsResponse Response of list of budgets.
type ListBudgetsResponse struct {
	Budgets *[]Budget `json:"budgets,omitempty"`
}

// BudgetCreateBudgetJSONRequestBody defines body for BudgetCreateBudget for application/json ContentType.
type BudgetCreateBudgetJSONRequestBody = Budget
