package main

import (
	"fmt"
	"path/filepath"
	"regexp"
	"strings"

	"google.golang.org/genproto/googleapis/api/annotations"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/reflect/protoreflect"
)

var pathParamRegex = regexp.MustCompile(`\{([^}]+)\}`)

func main() {
	protogen.Options{}.Run(func(gen *protogen.Plugin) error {
		for _, f := range gen.Files {
			if !f.Generate {
				continue
			}
			generateFile(gen, f)
		}
		return nil
	})
}

func generateFile(gen *protogen.Plugin, f *protogen.File) {
	tsPath := strings.TrimSuffix(f.Desc.Path(), ".proto") + ".ts"
	g := gen.NewGeneratedFile(tsPath, "")

	g.P("// Code generated by protoc-gen-ts-simple. DO NOT EDIT.")
	g.P("// Source: ", filepath.Base(f.Desc.Path()))
	g.P()

	hasQueries := false
	hasMutations := false
	for _, service := range f.Services {
		for _, method := range service.Methods {
			options := method.Desc.Options()
			if !proto.HasExtension(options, annotations.E_Http) {
				continue
			}
			httpRule := proto.GetExtension(options, annotations.E_Http).(*annotations.HttpRule)
			if httpRule.GetGet() != "" {
				hasQueries = true
			} else if httpRule.GetPost() != "" || httpRule.GetPut() != "" || httpRule.GetDelete() != "" || httpRule.GetPatch() != "" {
				hasMutations = true
			}
		}
	}

	if len(f.Services) > 0 {
		g.P("import { request } from \"@/lib/api-client\";")
		var rqImports []string
		if hasQueries {
			rqImports = append(rqImports, "useQuery", "type UseQueryOptions")
		}
		if hasMutations {
			rqImports = append(rqImports, "useMutation", "type UseMutationOptions")
		}
		if len(rqImports) > 0 {
			g.P("import { ", strings.Join(rqImports, ", "), " } from \"@tanstack/react-query\";")
		}
		g.P()
	}

	// Generate Enums in this file
	for _, enum := range f.Enums {
		generateEnum(g, enum)
	}
	for _, msg := range f.Messages {
		generateNestedEnums(g, msg)
	}

	// Generate Messages in this file
	for _, msg := range f.Messages {
		generateMessage(g, msg)
	}

	// Generate Services in this file
	for _, service := range f.Services {
		writeComments(g, service.Comments)
		for _, method := range service.Methods {
			generateMethod(g, method)
		}
	}
}

func generateEnum(g *protogen.GeneratedFile, enum *protogen.Enum) {
	writeComments(g, enum.Comments)
	g.P("export type ", enum.GoIdent.GoName, " = ")
	for _, val := range enum.Values {
		name := string(val.Desc.Name())
		writeComments(g, val.Comments)
		g.P("  | ", fmt.Sprintf("%q", name))
	}
	g.P(";")
	g.P()
}

func generateNestedEnums(g *protogen.GeneratedFile, msg *protogen.Message) {
	for _, enum := range msg.Enums {
		parentPrefix := getNestedPrefixForEnumParent(enum.Desc.Parent())
		name := parentPrefix + string(enum.Desc.Name())
		writeComments(g, enum.Comments)
		g.P("export type ", name, " = ")
		for _, val := range enum.Values {
			valName := string(val.Desc.Name())
			writeComments(g, val.Comments)
			g.P("  | ", fmt.Sprintf("%q", valName))
		}
		g.P(";")
		g.P()
	}
	for _, nestedMsg := range msg.Messages {
		generateNestedEnums(g, nestedMsg)
	}
}

func generateMessage(g *protogen.GeneratedFile, msg *protogen.Message) {
	if msg.Desc.IsMapEntry() {
		return
	}

	name := getNestedPrefix(msg) + string(msg.Desc.Name())

	writeComments(g, msg.Comments)
	if len(msg.Fields) == 0 {
		g.P("export type ", name, " = Record<string, never>;")
		g.P()
	} else {
		g.P("export interface ", name, " {")

		for _, field := range msg.Fields {
			fieldName := field.Desc.JSONName()
			tsType := mapType(field)

			isOptional := field.Desc.HasOptionalKeyword() || field.Oneof != nil

			writeFieldComments(g, field.Comments)
			suffix := ""
			if isOptional {
				suffix = "?"
			}
			g.P("  ", fieldName, suffix, ": ", tsType, ";")
		}

		g.P("}")
		g.P()
	}

	for _, nestedMsg := range msg.Messages {
		if !nestedMsg.Desc.IsMapEntry() {
			generateMessage(g, nestedMsg)
		}
	}
}

func generateMethod(g *protogen.GeneratedFile, method *protogen.Method) {
	options := method.Desc.Options()
	if !proto.HasExtension(options, annotations.E_Http) {
		return
	}
	httpRule := proto.GetExtension(options, annotations.E_Http).(*annotations.HttpRule)

	var httpMethod string
	var path string

	if get := httpRule.GetGet(); get != "" {
		httpMethod = "GET"
		path = get
	} else if post := httpRule.GetPost(); post != "" {
		httpMethod = "POST"
		path = post
	} else if put := httpRule.GetPut(); put != "" {
		httpMethod = "PUT"
		path = put
	} else if deleteVal := httpRule.GetDelete(); deleteVal != "" {
		httpMethod = "DELETE"
		path = deleteVal
	} else if patch := httpRule.GetPatch(); patch != "" {
		httpMethod = "PATCH"
		path = patch
	}

	if httpMethod == "" {
		return
	}

	// Extract path parameters
	matches := pathParamRegex.FindAllStringSubmatch(path, -1)
	var pathParams []string
	for _, m := range matches {
		pathParams = append(pathParams, m[1])
	}

	// Build TypeScript function name (camelCase of Method Name)
	methodName := strings.ToLower(method.GoName[:1]) + method.GoName[1:]

	reqType := mapMessageName(method.Input)
	resType := mapMessageName(method.Output)

	writeComments(g, method.Comments)

	// Build parameters list
	var paramsList []string
	for _, p := range pathParams {
		paramsList = append(paramsList, fmt.Sprintf("%s: string", p))
	}
	reqSuffix := ""
	if len(method.Input.Fields) == 0 {
		reqSuffix = "?"
	}
	paramsList = append(paramsList, fmt.Sprintf("req%s: %s", reqSuffix, reqType))

	// Generate plain fetch wrapper function
	g.P("export async function ", methodName, "(", strings.Join(paramsList, ", "), "): Promise<", resType, "> {")

	var urlStr string
	if len(pathParams) > 0 {
		urlStr = "`" + "/api" + strings.ReplaceAll(strings.ReplaceAll(path, "{", "${"), "}", "}") + "`"
	} else {
		urlStr = fmt.Sprintf("%q", "/api"+path)
	}

	g.P("  return request<", resType, ">({")
	g.P("    method: ", fmt.Sprintf("%q", httpMethod), ",")
	g.P("    url: ", urlStr, ",")
	if httpMethod == "GET" || httpMethod == "DELETE" {
		g.P("    params: req,")
	} else {
		bodyField := httpRule.GetBody()
		if bodyField != "" && bodyField != "*" {
			jsonBodyField := bodyField
			for _, f := range method.Input.Fields {
				if string(f.Desc.Name()) == bodyField {
					jsonBodyField = f.Desc.JSONName()
					break
				}
			}
			g.P("    data: req.", jsonBodyField, ",")
		} else {
			g.P("    data: req,")
		}
	}
	g.P("  });")
	g.P("}")
	g.P()

	// Map path parameters to their camelCased JSON name from the input message fields
	var pathParamJSONNames []string
	for _, p := range pathParams {
		jsonName := p // fallback
		for _, f := range method.Input.Fields {
			if string(f.Desc.Name()) == p {
				jsonName = f.Desc.JSONName()
				break
			}
		}
		pathParamJSONNames = append(pathParamJSONNames, jsonName)
	}

	// Generate TanStack React Query Hooks wrapper
	if httpMethod == "GET" {
		hookName := "use" + method.GoName + "Query"
		var hookUrlStr string
		var queryFnCall string
		if len(pathParams) > 0 {
			hPath := path
			var args []string
			for i, p := range pathParams {
				jsonName := pathParamJSONNames[i]
				hPath = strings.ReplaceAll(hPath, "{"+p+"}", "${req."+jsonName+"}")
				args = append(args, "req."+jsonName)
			}
			args = append(args, "req")
			hookUrlStr = "`" + "/api" + hPath + "`"
			queryFnCall = methodName + "(" + strings.Join(args, ", ") + ")"
		} else {
			hookUrlStr = fmt.Sprintf("%q", "/api"+path)
			queryFnCall = methodName + "(req)"
		}

		g.P("export function ", hookName, "(")
		g.P("  req: ", reqType, ",")
		g.P("  options?: Omit<UseQueryOptions<", resType, ", Error>, \"queryKey\" | \"queryFn\">")
		g.P(") {")
		g.P("  return useQuery<", resType, ", Error>({")
		g.P("    queryKey: [", hookUrlStr, ", req],")
		g.P("    queryFn: () => ", queryFnCall, ",")
		g.P("    ...options,")
		g.P("  });")
		g.P("}")
		g.P()
	} else {
		hookName := "use" + method.GoName + "Mutation"

		var varsType string
		var varsDestruct string
		var varsArgs string

		if len(pathParams) > 0 {
			var fields []string
			var destruct []string
			var args []string
			for _, p := range pathParams {
				fields = append(fields, fmt.Sprintf("%s: string", p))
				destruct = append(destruct, p)
				args = append(args, p)
			}
			fields = append(fields, fmt.Sprintf("req: %s", reqType))
			destruct = append(destruct, "req")
			args = append(args, "req")

			varsType = "{" + strings.Join(fields, "; ") + "}"
			varsDestruct = "{" + strings.Join(destruct, ", ") + "}"
			varsArgs = strings.Join(args, ", ")
		} else {
			varsType = reqType
			varsDestruct = "req"
			varsArgs = "req"
		}

		g.P("export function ", hookName, "(")
		g.P("  options?: UseMutationOptions<", resType, ", Error, ", varsType, ">")
		g.P(") {")
		g.P("  return useMutation<", resType, ", Error, ", varsType, ">({")
		g.P("    mutationFn: (", varsDestruct, ") => ", methodName, "(", varsArgs, "),")
		g.P("    ...options,")
		g.P("  });")
		g.P("}")
		g.P()
	}
}

func getNestedPrefix(msg *protogen.Message) string {
	var parts []string
	curr := msg.Desc.Parent()
	for curr != nil {
		if _, ok := curr.(protoreflect.MessageDescriptor); ok {
			parts = append([]string{string(curr.Name())}, parts...)
			curr = curr.Parent()
		} else {
			break
		}
	}
	if len(parts) == 0 {
		return ""
	}
	return strings.Join(parts, "_") + "_"
}

func getNestedPrefixForEnumParent(parent protoreflect.Descriptor) string {
	var parts []string
	curr := parent
	for curr != nil {
		if _, ok := curr.(protoreflect.MessageDescriptor); ok {
			parts = append([]string{string(curr.Name())}, parts...)
			curr = curr.Parent()
		} else {
			break
		}
	}
	if len(parts) == 0 {
		return ""
	}
	return strings.Join(parts, "_") + "_"
}

func writeComments(g *protogen.GeneratedFile, comments protogen.CommentSet) {
	leading := strings.TrimSpace(string(comments.Leading))
	if leading == "" {
		return
	}
	g.P("/**")
	for _, line := range strings.Split(leading, "\n") {
		g.P(" * ", strings.TrimSpace(strings.TrimPrefix(line, "//")))
	}
	g.P(" */")
}

func writeFieldComments(g *protogen.GeneratedFile, comments protogen.CommentSet) {
	leading := strings.TrimSpace(string(comments.Leading))
	trailing := strings.TrimSpace(string(comments.Trailing))
	if leading == "" && trailing == "" {
		return
	}
	g.P("  /**")
	if leading != "" {
		for _, line := range strings.Split(leading, "\n") {
			g.P("   * ", strings.TrimSpace(strings.TrimPrefix(line, "//")))
		}
	}
	if trailing != "" {
		g.P("   * ")
		g.P("   * @description ", strings.TrimPrefix(trailing, "//"))
	}
	g.P("   */")
}

func mapType(field *protogen.Field) string {
	if field.Desc.IsMap() {
		keyType := mapBaseTypeForKind(field.Desc.MapKey().Kind(), nil)
		valType := mapBaseTypeForKind(field.Desc.MapValue().Kind(), field.Desc.MapValue().Message())
		return fmt.Sprintf("Record<%s, %s>", keyType, valType)
	}

	baseType := mapBaseType(field)
	if field.Desc.IsList() {
		return baseType + "[]"
	}
	return baseType
}

func mapMessageName(msg *protogen.Message) string {
	fullName := string(msg.Desc.FullName())
	if fullName == "google.protobuf.Timestamp" {
		return "string"
	}
	if fullName == "google.protobuf.Empty" {
		return "Record<string, never>"
	}
	return getNestedPrefix(msg) + string(msg.Desc.Name())
}

func mapBaseType(field *protogen.Field) string {
	switch field.Desc.Kind() {
	case protoreflect.EnumKind:
		var parentPrefix string
		if parentDesc := field.Enum.Desc.Parent(); parentDesc != nil {
			parentPrefix = getNestedPrefixForEnumParent(parentDesc)
		}
		return parentPrefix + string(field.Enum.Desc.Name())
	case protoreflect.MessageKind:
		return mapMessageName(field.Message)
	default:
		return mapBaseTypeForKind(field.Desc.Kind(), nil)
	}
}

func mapBaseTypeForKind(kind protoreflect.Kind, msg protoreflect.MessageDescriptor) string {
	switch kind {
	case protoreflect.BoolKind:
		return "boolean"
	case protoreflect.StringKind, protoreflect.BytesKind:
		return "string"
	case protoreflect.Int64Kind, protoreflect.Uint64Kind,
		protoreflect.Sint64Kind, protoreflect.Fixed64Kind, protoreflect.Sfixed64Kind:
		return "string"
	case protoreflect.Int32Kind, protoreflect.Uint32Kind, protoreflect.Sint32Kind,
		protoreflect.Fixed32Kind, protoreflect.Sfixed32Kind,
		protoreflect.DoubleKind, protoreflect.FloatKind:
		return "number"
	case protoreflect.MessageKind:
		if msg != nil {
			if string(msg.FullName()) == "google.protobuf.Timestamp" {
				return "string"
			}
			return string(msg.Name())
		}
		return "any"
	default:
		return "any"
	}
}
