import { StyleSheet } from "react-native"
import { theme } from "@/lib/theme"

export const sheetStyles = StyleSheet.create({
  sheetListContent: {
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 24,
    gap: 8,
  },
  accountListItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    padding: 12,
    borderRadius: theme.radius.lg,
    backgroundColor: theme.colors.surfaceElevated,
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  accountListItemActive: {
    borderColor: theme.colors.primary,
    backgroundColor: theme.colors.primarySubtle,
  },
  accountIconBadge: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: theme.colors.background,
    alignItems: "center",
    justifyContent: "center",
  },
  accountItemTitle: {
    fontSize: 14,
    fontWeight: "600",
    color: theme.colors.textPrimary,
  },
  accountItemSubtitle: {
    fontSize: 12,
    color: theme.colors.textMuted,
    marginTop: 1,
  },
  emptySheetBox: {
    paddingVertical: 32,
    alignItems: "center",
    justifyContent: "center",
  },
  emptySheetText: {
    fontSize: 13,
    color: theme.colors.textMuted,
  },
  budgetListItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    padding: 12,
    borderRadius: theme.radius.lg,
    backgroundColor: theme.colors.surfaceElevated,
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  budgetIconBadge: {
    width: 38,
    height: 38,
    borderRadius: 19,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  budgetDetailsCol: {
    flex: 1,
    gap: 4,
  },
  budgetNameRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  budgetListItemTitle: {
    fontSize: 14,
    fontWeight: "600",
    color: theme.colors.textPrimary,
    flexShrink: 1,
  },
  budgetIntervalBadge: {
    paddingHorizontal: 5,
    paddingVertical: 1,
    borderRadius: 4,
    backgroundColor: theme.colors.background,
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  budgetIntervalText: {
    fontSize: 9,
    fontWeight: "700",
    color: theme.colors.textMuted,
    textTransform: "uppercase",
  },
  budgetRemainingText: {
    fontSize: 12,
    fontWeight: "700",
    color: theme.colors.success,
  },
  budgetOverText: {
    color: theme.colors.destructive,
  },
  miniProgressTrack: {
    height: 4,
    borderRadius: 2,
    backgroundColor: theme.colors.background,
    overflow: "hidden",
    marginTop: 2,
  },
  miniProgressBar: {
    height: "100%",
    borderRadius: 2,
  },
  budgetMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 1,
  },
  budgetMetaText: {
    fontSize: 11,
    color: theme.colors.textMuted,
  },
  budgetPercentText: {
    fontSize: 11,
    fontWeight: "600",
    color: theme.colors.textMuted,
  },
  budgetCheckBadge: {
    width: 24,
    height: 24,
    alignItems: "center",
    justifyContent: "center",
    marginLeft: 4,
  },
  currencySearchContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginHorizontal: 16,
    marginBottom: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: theme.colors.surfaceElevated,
    borderRadius: theme.radius.md,
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  currencySearchInput: {
    flex: 1,
    fontSize: 14,
    color: theme.colors.textPrimary,
    padding: 0,
  },
  currencyBadgeCode: {
    width: 44,
    height: 32,
    borderRadius: 8,
    backgroundColor: theme.colors.primarySubtle,
    alignItems: "center",
    justifyContent: "center",
  },
  currencyBadgeCodeText: {
    fontSize: 12,
    fontWeight: "700",
    color: theme.colors.primary,
  },
  scheduledItemAmount: {
    fontSize: 15,
    fontWeight: "700",
    color: theme.colors.textPrimary,
  },
})
